### ISSUE TITLE
Can't create business account for personal accounts

### ISSUE THREAD

**Issue by sukafia** [woocommerce/pinterest-for-woocommerce#1005]
### Describe the bug:

When personal account users with no existing Pinterest Business account attempt the setup, the "Create business account" functionality doesn't create a business account for them on the setup screen. This makes it impossible for personal account users to complete the setup

![Lxueb2.png](https://github.com/woocommerce/pinterest-for-woocommerce/assets/60121732/b0281f2d-f230-4d29-b3d2-e6f6df91a3df)

### Steps to reproduce:

1. Attempt to connect a personal Pinterest account with no existing business account
2. Attempt to create a new business account during the setup by clicking "Create business account" and granting the required permission.
3. Notice you're redirected back to the setup without a business account being created.

### Expected behavior:

A new business account should be created for the setup.

**Comment by budzanowski** [comment]
@sukafia which version of Pinterest is this issue for?

**Comment by sukafia** [comment]
> @sukafia which version of Pinterest is this issue for?

Latest public version 1.3.24.

**Comment by rawdreeg** [comment]
@sukafia . The issue should now be resolved. We fixed the connection flow in the new api.woocommerce.com connector.

Can you please check?

cc: @budzanowski

**Comment by sukafia** [comment]
@rawdreeg it works now. Thanks for the quick fix! 😄 

By the way, I noticed it seems to be converting personal accounts to a business account. Shouldn't it be creating a business account for the personal account? Here's the difference based on the Pinterest doc:


* [Create a linked business account](https://help.pinterest.com/en/business/article/get-a-business-account#section-17831) - I expected it to do this. 
* [Convert your personal account into a business account](https://help.pinterest.com/en/business/article/get-a-business-account#section-15096) - It seems to be doing this.

**Comment by rawdreeg** [comment]
Thanks @sukafia 

Not sure what's the expected flow. but what I experienced:

Connected my account:
<img width="1113" alt="Screenshot 2024-04-17 at 13 29 17" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/4209011/f944a70f-d075-44d7-a53d-f7e320b6db32">

Clicked on create business account, got redirected to Pinterest
<img width="713" alt="Screenshot 2024-04-17 at 13 29 28" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/4209011/34cfa2f8-8333-4597-a349-39df01174423">

Created a linked business, then clicked on Connect:
<img width="1097" alt="Screenshot 2024-04-17 at 13 30 18" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/4209011/b644de13-a6ef-4e28-8d83-8d374bda187d">

Then:
<img width="1141" alt="Screenshot 2024-04-17 at 13 30 36" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/4209011/959b1770-9514-4d7a-bda6-6ec18902c440">

It did not convert my account. I have 2 linked account:

<img width="300" alt="Screenshot 2024-04-17 at 13 34 37" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/4209011/5d855b93-61d0-4c58-ae53-49c54a0f0b86">

**Comment by sukafia** [comment]
Your experience is what I was expecting but it's not what I got. In my case, it converted the account into a business account instead of creating a linked business account as in your case.

I need to create a new account to test again. I'll let you know what I find.

**Comment by rawdreeg** [comment]
Any news on this @sukafia . Let me know if we can mark this as resolved.

**Comment by sukafia** [comment]
@rawdreeg thanks for the nudge. I checked again with a new account and got the expected behaviour. However, I noticed a few odd things:

1. During my initial setup, I wasn't presented with the "create a linked business account" flow. I clicked "Create business account" granted access and was just taken back to the same page. (the create business account page)
2. On the 2nd attempt it worked as expected. However, after clicking "Create a linked business account" and granting access, it just kept moving me through Pinterest flow. I expected to be redirected back to the setup screen to continue the setup. To clarify, it did create and associate the business account on the setup tab - but since the flow opened a new tab, I couldn't tell that was done and expected to be redirected to the setup screen. 

I recorded a video of the 2nd attempt: 
https://github.com/woocommerce/pinterest-for-woocommerce/assets/60121732/3d987a88-fff6-47ee-8b5a-c5ee1c58ab7d

**Comment by rawdreeg** [comment]
Good point. @message-dimke, do you happen to know if this is expected behavior?

I believe this is unrelated to the original issue and should be investigated separately. I suggest we close this one and track the "Create a linked business account" flow issue separately.

**Comment by rawdreeg** [comment]
following up on this,

@message-dimke, I'm not sure you got the chance to look at this.

**Comment by message-dimke** [comment]
Hey, folks!

@sukafia I went through the flow as you and @rawdreeg did. Yes, Pinterest rides you on a carousel, but we do not have any control on that flow. Must collaborate with them to break this loop.

New version does everything during the connection flow to avoid this.

<img width="575" alt="Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/6576c8ed-5523-4a29-986f-5c2e6d398a91">

1.3.24 however, can not provide this.

I went through the flow like @rawdreeg did and my experience was the same as you both had.

<img width="1728" alt="Onboarding_Guide_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/80391dee-e877-4ac2-a240-fb2dbc271328">

<img width="1728" alt="Pinterest-2" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/33a97592-88c9-4420-9c85-c530666a9c49">

<img width="1728" alt="Pinterest-3" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/cbef5125-7834-4615-bf69-fd54551143e8">

<img width="1728" alt="Pinterest-4" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/2527abcc-3a46-44c2-b1c4-1a11f9d9fa76">

<img width="1728" alt="Pinterest-5" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/02327fbd-dbf0-4a33-911d-3a982e201da2">

<img width="1728" alt="Pinterest-6" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/e73e42c3-92e4-4ba0-ab06-27a8229706c4">

<img width="1728" alt="Onboarding_Guide_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce-2" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/90c6a3ad-6fe7-4587-b8b5-a2407626558a">

<img width="1728" alt="Pinterest-7" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/6a8c59ea-8949-498c-8125-2700f8e5019c">

<img width="1728" alt="WooCommerce_Connect_-_Connecting_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/50626a6e-ba27-44e4-a4d4-874572ac17de">

<img width="1728" alt="Onboarding_Guide_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce-3" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/22cd383d-703f-4e46-baac-c1f0f0e2203c">

Not sure if it makes things clearer, but at least we verified the flow once more.

Also, I hope, v 1.3.x is going to be replaced soon and we will have a more advanced Pinterest onboarding wizard.

**Comment by sukafia** [comment]
Sounds good to me @message-dimke. I think it's okay to close the issue - there's no further feedback from my end.
