### ISSUE TITLE
Pinterest landing page displays "Not allowed" with WordPress 6.6

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#1031]
### Describe the bug:

I'm doing WordPress 6.6 compatibility testing in issue https://github.com/woocommerce/pinterest-for-woocommerce/issues/1030. 

I found that when we are using [WordPress 6.6-RC2](https://wordpress.org/news/2024/07/wordpress-6-6-rc2/), the Pinterest plugin admin landing page (`/wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Flanding`) shows "Sorry, you are not allowed to access this page."

![image](https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/a584bfd1-5162-474b-8f64-b7a1420eaf32)

There is also a console error:

![image](https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/f11bf1d3-6db0-47f9-9285-354b212a3550)

```
setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1 Uncaught TypeError: Cannot read properties of undefined (reading 'mark')
    at Module.<anonymous> (setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1:285178)
    at a (setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1:774)
    at r (setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1:643)
    at setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1:1713
    at setup-guide.js?ver=32b64018a91d8be20cc4e58862df4f99:1:1717
```

I have a feeling that this is related to conflict with WordPress packages (e.g. `@wordpress/data` package, dependency extraction).

This issue does not happen when I downgrade to WordPress version 6.5.

### Steps to reproduce:

1. Use WordPress 6.6-RC2. 
2. Go to Pinterest plugin.

### Expected behavior:

Pinterest plugin should show landing page.

### Actual behavior:

Pinterest plugin will show error message as per screenshot above.

**Comment by message-dimke** [comment]
This is what I had recently. Looks like a problem with some folder permissions when installing. JS calls the script which is not accessible.

**Comment by ecgan** [comment]
> Looks like a problem with some folder permissions when installing.

@message-dimke , this is not the case for this issue here. This issue does not happen when we use WordPress 6.5; it happens when we use WordPress 6.6.

**Comment by ecgan** [comment]
The cause of the issue is due to some breaking changes in WordPress 6.6.

References:

- [WP 6.6 RC1: plugin breaks after update](https://github.com/WordPress/gutenberg/issues/62923#top)
- https://make.wordpress.org/core/2024/06/25/miscellaneous-developer-changes-in-wordpress-6-6/#obsolete-polyfills-dependencies-have-been-removed
- https://core.trac.wordpress.org/ticket/60962

This can be fixed by adding `regenerator-runtime` as a dependency explicitly. I'll come up with a PR shortly.
