### ISSUE TITLE
`25` Feed Deletion Failed messages

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/pinterest-for-woocommerce#1060]
### Describe the bug:

A message from the forum thread https://wordpress.org/support/topic/pinterest-for-woocommerce-feed-deletion-failed/#post-17982223

> _I’ve got the same message. In fact I have 25 of them. It does not help to dismiss them. They just come back on next reload…_

![ViG9EQx](https://github.com/user-attachments/assets/165ff57d-8835-47be-af89-495910397ef8)

**Comment by hayley-king** [comment]
8666046-zen

**Comment by shohanhossainnab** [comment]
8673402-zen

**Comment by shohanhossainnab** [comment]
8699462-zen

**Comment by rynaldos** [comment]
8702275-zen

**Comment by mriyazuddin** [comment]
8660184-zen

**Comment by mriyazuddin** [comment]
8721046-zen
