### ISSUE TITLE
Retry failed calls to create_commerce_partner_merchant

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#1068]
### Describe the bug:

During upgrade process from v3>v5 app, about 1000 calls to endpoint https://developers.pinterest.com/docs/api/v5/integrations_commerce-post failed due to backend error on pinterest

secondly, there is a partner_metadata field on the above API which receives metadata about app version number distribution to help us in debugging and understand rolllout stats. 

We should create a background job (or use an existing one) to sync (UPSERT) data for the above API once in 7 days.

https://a8c.slack.com/archives/C04QQLX04MC/p1724792521968899

**Comment by message-dimke** [comment]
Introduced with #1078
