### ISSUE TITLE
Feed Deletion failed message

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#1069]
A feed deletion could fail during disconnection process when pinterest does not delete the feed due to various reasons. 

When that happens show a notification to the user saying (1) feed deletion failed (2) Reason for failure. You can use the reason returned from the API. (3) to contact pinterest for this feed to be deleted or fix the problem shown (like ending campaign)

https://a8c.slack.com/archives/C04QQLX04MC/p1724838314349369

**Comment by message-dimke** [comment]
Fixed with #1067 and released with 1.4.9-1.4.10 versions.
