### ISSUE TITLE
Catalog should not be created when user selected not to create the catalog

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#1070]
### Describe the bug:
When the user disconnected their account and failed to delete a feed due to active promos. Then, the user reconnected and picked "Catalogue is already connected" but got a new feed created and now they say there is a conflict of catalogs they have.

![image](https://github.com/user-attachments/assets/0ff56877-ebb0-4117-92ce-3f36a47abee4)

### Expected behavior:
When the connected 2nd time no new feed should be created or registered.

The old feed is now orphaned. They must contact pinterest to disconnect them

A warning message must be shown to users

https://a8c.slack.com/archives/C04QQLX04MC/p1724763549634719

**Comment by message-dimke** [comment]
Selecting the "Catalogue is already connected" option turns Product Sync off. If you have no feeds with Pinterest then no feed is going to be added. 
In case you already have a feed with Pinterest (for some reason) and it is served from the same domain as your current website, then the plugin will attempt to reuse it.
