### ISSUE TITLE
Woo site domain formatted like copy text in onboarding

### ISSUE THREAD

**Issue by haszari** [woocommerce/pinterest-for-woocommerce#110]
### Describe the bug:
<img width="1415" alt="Screen Shot 2021-07-29 at 3 55 21 PM" src="https://user-images.githubusercontent.com/4167300/127430627-982ac799-5b84-4d5c-a637-b8534177f642.png">

In the `Claim your website` onboarding step, the site url/domain has no special formatting, which looks a little strange.

@shivanarrthine Can you advise how this should look? I'm thinking the type/style should be slightly different from the regular copy in some way.

### Steps to reproduce:
1. Fresh woo site & pinterest account – ensure the domain has not been claimed.
2. Install Pinterest for WooCommerce and start onboarding. Note this was observed on the branch for PR #108 (may be on `develop` too).

**Comment by findingsimple** [comment]
Project figma file contains detailed designs
