### ISSUE TITLE
Enable debug logging based on WP_DEBUG

### ISSUE THREAD

**Issue by ksere** [woocommerce/pinterest-for-woocommerce#116]
### Is your feature request related to a problem? 

As by default debug logging is [disabled](https://github.com/saucal/pinterest-for-woocommerce/blob/3598d1886e0baa6583b4c2d2b00fc4978727d375/class-pinterest-for-woocommerce.php#L64) any potential issues during the onboarding - for example on API requests to Pinterest - are not caught.
The user needs to complete onboarding and enable debug logging in the settings, which may not be possible if there is an error during onboarding. 

#### How to reproduce the problem

1. Start the onboarding process.
2. Connect your account.
3. Revoke auth of "App" through your Pinterest dashboard or using any other way make the API calls fail.

### Describe the solution you'd like 
This could be solved by always logging if WP_DEBUG is true, as if the `enable_debug_logging` was enabled. [Log method](https://github.com/saucal/pinterest-for-woocommerce/blob/feature/refactor-plugin-navigation/src/Logger.php#L46)

### Describe alternatives you've considered 

We could also 
- just have `enable_debug_logging` enabled by default, but it will result in the whole userbase logging API calls for no reason. 
- Enable logging regardless of the plugin setting when not yet fully onboarded.

**Comment by findingsimple** [comment]
@budzanowski do you have any thoughts on best approach here?

**Comment by budzanowski** [comment]
@jconroy @ksere I was playing with the code to understand what would work and I have tested the very simple https://github.com/woocommerce/pinterest-for-woocommerce/pull/355 I think that this works and it works out of the box.
It has the added benefit of starting the logging in case the connection between the plugin and the service is misconfigured for some reason.

**Comment by ksere** [comment]
> @jconroy @ksere I was playing with the code to understand what would work and I have tested the very simple #355 I think that this works and it works out of the box. It has the added benefit of starting the logging in case the connection between the plugin and the service is misconfigured for some reason.

Hey @budzanowski !
This would work, has the benefit that you can get logs from users for that initial stage without having them enable debugging. [This](https://github.com/woocommerce/pinterest-for-woocommerce/pull/356/files) is what I had in mind (and had on a local branch collecting dust 😄)
