### ISSUE TITLE
The Site cannot be verified on the onboarding process

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#154]
### Describe the bug:
![Captura de pantalla de 2021-08-13 16-15-14](https://user-images.githubusercontent.com/43881685/129410801-17598776-b82d-4b94-86da-4767bec0174f.png)

### Steps to reproduce:
1- Install and activate the plugin
2- do the onbarding
3- Login with the Pitnerest account on onboarding
4- Verify Site on the onboarding
Same steps with 0.9.0 works as expected

#### Expected behavior
Verify site works ok

#### Actual behavior
error message is showing

**Comment by ecgan** [comment]
@ChristianAF , is there a HTTP request debug log that you can attached to this issue, similar to https://github.com/woocommerce/pinterest-for-woocommerce/issues/160? That would help to pinpoint which part of the code is causing the issue.

I tried googling for the error message in the screenshot `"your website is in the process of being claimed and should be verified shortly"` but couldn't find anything useful.

**Comment by ghost** [comment]
Do we have any steps to reproduce this issue? We added more logging on our side so that we debug this but we cant reproduce this issue. If you are still facing this issue you can try again and provide domain from which you are seeing the issue. we will be able to track on pinterest side.

**Comment by findingsimple** [comment]
> Do we have any steps to reproduce this issue?

@niketpins my understanding is the most recent occurrences that have been seen of this were during your beta user testing.
