### ISSUE TITLE
Document key user flows

### ISSUE THREAD

**Issue by haszari** [woocommerce/pinterest-for-woocommerce#173]
As we prepare for beta-test and soft launch, we should have a doc somewhere that outlines the key user flows – the typical, recommended path to setting up the main features. This will help us triage issues and will be useful starting point for user documentation.

There's a start on this doc here: https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/docs/testing-flows.md

**Comment by alexiglesias31** [comment]
@jconroy, should we build the documentation using a flowchart or text documentation?

**Comment by findingsimple** [comment]
Both would be ideal - but I'd say text + screenshots as needed at a minimum

If we did flowchart I think it would need to be a google doc
