### ISSUE TITLE
Do not store progress as translated strings in the database

### ISSUE THREAD

**Issue by msaggiorato** [woocommerce/pinterest-for-woocommerce#178]
While working on #158, it became relevant that there's strings that are stored in the database to mark things like progress. These are stored translated (and after changes implemented in #163) with HTML markup even.

One particular example is the progress status for the feed generation (Wrote %s out of %s to file). 

I'm opening up this issue by request of @haszari to reinforce this:

- Markup / UI text should be generated as late as possible. 
- State should not be cached unless there's a specific need. If stats/data needs to be stored  for later display in UI (e.g. num products in feed so far, feed generation time, feed file size), store in transients so it's clear it's derived, temporary data. Store raw values, not generated markup. Prefer one value per transient, rather than storing a large nested structure.

**Comment by findingsimple** [comment]
> (Wrote %s out of %s to file)

For a specific example - refer to the `pinterest_for_woocommerce_data` option - within the serialized data there will be key "progress" with value like "wrote 38 out of 38 products to <a href="https://xxxxxpppp.io/wp-content/uploads/pinterest-for-woocommerce-XXXXX.xml" target="_blank">feed file</a>."
