### ISSUE TITLE
Code should check status of the actually generated feed, not the most recent one.

### ISSUE THREAD

**Issue by msaggiorato** [woocommerce/pinterest-for-woocommerce#183]
### Describe the bug:
Feed issues are fetched by merchant id, not filtering the feed profile (stored in the database). This can cause inconsistencies.

### Steps to reproduce:
Given a merchant with more than one ingestion feed profile, the feed ingestion status might not be the real status.

#### Expected behavior
Feed status matches the information (or a summarized version of it) to the one displayed in Pinterest.

#### Actual behavior
Inconsistent behaviour in the case of multiple ingestion feed profiles.

**Comment by findingsimple** [comment]
Possible related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/193 and https://github.com/woocommerce/pinterest-for-woocommerce/issues/197
