### ISSUE TITLE
Include essential request details in error logs

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#187]
### Describe the bug:

This issue is slightly related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/186.

When I go to the WooCommerce logs page (`/wp-admin/admin.php?page=wc-status&tab=logs`), I see many "ERROR Error Processing Request: Invalid parameters." with no error details:

![image](https://user-images.githubusercontent.com/417342/130504855-da763850-d68d-4919-8bcc-3bf621c8ba14.png)

Without error details (e.g. which request, which parameters are invalid) and stack trace, the logs here are not really helpful to troubleshoot issues. The logs are one of the main things that our customer support (Happiness Engineer) use to help the users.

### Steps to reproduce:

Pre-condition: follow the steps to reproduce in https://github.com/woocommerce/pinterest-for-woocommerce/issues/186. 

1. Go to the WooCommerce logs page (`/wp-admin/admin.php?page=wc-status&tab=logs`)
2. Select Pinterest log file and click on the View button.

#### Expected behavior

- In verbose/debug mode, more details and possibly a stack trace should be displayed. Ideally, for `Invalid parameters`, it should be possible to find out what parameters are invalid 🕵️.
- In normal/production mode, each log should include enough info to be useful, e.g. request details and response code.

#### Actual behavior

Logs contain a raw error message with no context - e.g. `Error Processing Request: Invalid parameters`.

**Comment by alexiglesias31** [comment]
@jconroy, wrapping up a bit the above discussion. The intended solution is aligned with this comment:

(behavior when debug logging is disabled)
> As a minimum, for failed HTTP requests, the log should include:
The request, e.g. method and endpoint/path.
The response status code.

In addition, adding the stack trace only if debug logging is enabled.
Do you have a second thought on this?
