### ISSUE TITLE
Improve Domain Verification process

### ISSUE THREAD

**Issue by msaggiorato** [woocommerce/pinterest-for-woocommerce#190]
### Is your feature request related to a problem? 
Domain verification could use a refactor to be more easily to maintain and review. Currently the process relies mostly on [this API](https://developers.pinterest.com/docs/redoc/#operation/v3_verify_domain_realtime_POST), which is not well documented, but can return a "Working on it. Try Later." kind of response, which is not really predictable about how much time it can take.

In order to solve this, the code is doing a couple of retries (with some delay in between) until getting a success, or running out of retries.

This works, but is somewhat a bad UX in case Pinterest is experiencing extra load.

There might be a better way to do this verification, but we'd need help from Pinterest side pointing to the right APIs (or use of them).

---

The idea to improve this came up in #156.

**Comment by findingsimple** [comment]
Making a note - new domain verification endpoint is being proposed for v2 which may help address the core of this issue

**Comment by findingsimple** [comment]
Check fix for #154 may already be taking care of this.

**Comment by message-dimke** [comment]
This one is too old, closing it. Current Pinterest API is v5 version already.
