### ISSUE TITLE
Enhanced Match is not enabled by default

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#191]
### Describe the bug:

After installing the plugin and going through the setup onboarding flow in a brand new site, I go to the settings page and I noticed that the Enhanced Match support is not enabled by default.

![image](https://user-images.githubusercontent.com/417342/130679729-81c615df-f797-4864-bcab-7e455bb345f6.png)

I think it would be better to have it enabled by default (a sensible default). If the merchants do not want it, they can disable it in settings after the onboarding flow. This is also the same as what @garymurray mentioned in a Slack message some time ago.

I am not sure if there is a downside to have it enabled by default. I think, if I am a merchant and I want to track conversion (which is already enabled by default), I would want to have Enhanced Match too.

### Steps to reproduce:

1. Install the plugin on a brand new site (so that there isn't any previous old Pinterest plugin data).
2. Go through the setup onboarding flow.
3. Go to the settings page.

#### Expected behavior

Enhanced Match is enabled by default just like other settings.

#### Actual behavior

Enhanced Match is not enabled by default, I have to check it and click on the "Save changes" button.

**Comment by findingsimple** [comment]
Confirmed that enhanced match should ideally be enabled by default.

The feature itself sends through additional customer info (hashed email addresses) we could possible look to add some placeholder info to the WP Privacy Page template etc. https://wordpress.org/support/article/settings-privacy-screen/ as a follow-up.

**Comment by findingsimple** [comment]
@ianlin just assigned you so others don't double up on the work

**Comment by ksere** [comment]
Hey @ianlin, since I got this handy, the only change needed is switching [this](https://github.com/woocommerce/pinterest-for-woocommerce/blob/9d5cd583a5decc4a8342d1e48f14a0a581332387/class-pinterest-for-woocommerce.php#L98) to `true`.
