### ISSUE TITLE
[Related 183?] "Remote sync status" shows incorrect info based on wrong feed from old site

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#193]
### Describe the bug:

Version tested: https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.0-beta.2

I have an existing site connected to an existing Pinterest account. I setup a brand new site with a new URL domain, went through the setup onboarding flow successfully, connected to the same existing Pinterest account, using the same advertiser and tracking tag.

When the setup onboarding is complete, I go to the Catalog tab, this is what I see:

![image](https://user-images.githubusercontent.com/417342/130839340-b1a43a38-4057-4490-982c-9a231c46d101.png)

It says "XML Feed: Successfully generated 56 mins ago". However, in "Remote sync status", it says "last pulled: 2 hours ago", which does not make sense - how can it pull the feed when the feed was not generated yet?

Also, when I go to Pinterest Catalogs page, I see this:

![image](https://user-images.githubusercontent.com/417342/130840743-53dc58a6-3167-41ce-b2aa-7a459603ae9d.png)

![image](https://user-images.githubusercontent.com/417342/130845712-3f7926eb-e341-47c4-ace6-52db9eb7d9e7.png)

In the feed for the new site, the status is "pending", which means Pinterest hasn't pulled the feed from the new site yet. When I expand the old site info, and hover my mouse over the "Date" field, the tooltip shows the exact date and time, which roughly corresponds to the "2 hours ago" stated in "Remote sync status".

I suspect that the "Remote sync status" is getting wrong info from the old feed. It should be getting the info from the new feed.

### Steps to reproduce:

Pre-condition: Have an existing website connected to an existing Pinterest account.

1. Setup a new website with new URL.
2. Go through setup onboarding, connect to existing Pinterest account, use the same advertiser and tracking tag.
3. Go to Catalog page: /wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fcatalog and look at the "remote sync status" field.
4. Go to [Pinterest Catalogs page](https://www.pinterest.com/product-catalogs/data-source/) and check the status of the feed for the new site and old site.

#### Expected behavior

The "remote sync status" should match the feed status for the new site in Pinterest.

#### Actual behavior

The "remote sync status" seems to be getting the feed status for the old site, not the new site.

### Additional details:

Note that this issue is quite time sensitive - you should check the Pinterest Catalog page as soon as the feed registration is done, and periodically refresh the plugin catalog page and Pinterest Catalog page.

**Comment by findingsimple** [comment]
> I suspect that the "Remote sync status" is getting wrong info from the old feed. It should be getting the info from the new feed.

Possibly related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/183

**Comment by nima-karimi** [comment]
I can confirm that this issue is now fixed by https://github.com/woocommerce/pinterest-for-woocommerce/pull/222. Closing.
