### ISSUE TITLE
[Related 183?] Issues section is missing with error in API calls after connecting new site to existing Pinterest account

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#197]
### Describe the bug:

Version tested: https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.0-beta.2.

This is possibly related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/193.

I have an existing site connected to an existing Pinterest account. I setup a brand new site with a new URL domain, went through the setup onboarding flow successfully, connected to the same existing Pinterest account, using the same advertiser and tracking tag.

In the Catalog tab, this is what I see:

![image](https://user-images.githubusercontent.com/417342/131175905-dd4f5a62-f28f-40c5-aba5-8814b05d4a40.png)

In the Overview section, I have 48 warnings. There is supposed to be an Issues table below, but it is missing. 

When I look into network panel in dev tools, I see this: 

![image](https://user-images.githubusercontent.com/417342/131176454-53404222-ddac-41c3-94b4-ca8b6791ab49.png)

The `GET /wp-json/pinterest/v1/feed_issues?paged=1&per_page=25&_locale=user` returns HTTP status 200 OK, and in the response body, there is a `message: "Could not get current feed&#039;s issues. [Call to a member function get_parent_id() on bool]"`. There isn't any related message in the UI.

When I go [Pinterest Catalog page](https://www.pinterest.com/product-catalogs/data-source/) and view the product feed issues for my new site, there are 48 issues (though note that my old site also has 48 issues): 

![image](https://user-images.githubusercontent.com/417342/131177407-e79c7c28-c02a-41ff-8186-a55c19f6ef6a.png)

So there are a few issues here: 

- In the `GET /wp-json/pinterest/v1/feed_issues?paged=1&per_page=25&_locale=user` request, if there is a Pinterest API error, then the response should return HTTP error code, not HTTP status 200 OK. Subsequently, the UI should display a related error message. 
- Why does the request not returning the list of issues? I suspect this is because I am connecting a new site to an existing Pinterest account. My Pinterest account has more than one data source in the Catalogs.

### Steps to reproduce:

Pre-condition: Have an existing website connected to an existing Pinterest account.

1. Setup a new website with new URL.
2. Go through setup onboarding, connect to existing Pinterest account, use the same advertiser and tracking tag.
3. Go to Catalog page: /wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fcatalog, wait for the sync to be done, and look at the Overview section. There should be a number of warnings. 
4. Go to the [Pinterest Catalog page](https://www.pinterest.com/product-catalogs/data-source/), find the data source for the new site, click the expand button and click on View issues for the most recent date. The number of issues should match the number you see in Step 3. 

#### Expected behavior

There should be an Issues section below the Overview section. 

#### Actual behavior

The Issues section is missing.

**Comment by findingsimple** [comment]
> I suspect this is because I am connecting a new site to an existing Pinterest account. My Pinterest account has more than one data source in the Catalogs.

Possibly related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/183

**Comment by nima-karimi** [comment]
I can confirm that this issue is now fixed by https://github.com/woocommerce/pinterest-for-woocommerce/pull/222. Closing.
