### ISSUE TITLE
Make PHP 7.4+ compatibility requirements clear on plugin landing page

### ISSUE THREAD

**Issue by wjia88** [woocommerce/pinterest-for-woocommerce#203]
### Is your feature request related to a problem? 

- One of the most frequent challenges encountered during the study was the inability to connect to our integration due to the users’ PHP version being incompatible with the integration. This prevented many participants from being able to install the plugin and participate in our study. Out of the 10 participants that did participate, 3/10 were initially unable to install the plugin for this reason. Once they upgraded to PHP 7.4 through their hosting provider, they were able to successfully install the integration.
- In order to resolve this problem participants had to upgrade their version of PHP to 7.4. For some users, this was an easy fix but others were unable to resolve this issue as it would interfere with other plugins and potentially crash their website entirely. This should be a known limitation of our integration and it should be understood that this will be a barrier for certain users and potentially affect their ability to adopt our integration.
- Additionally, users using the Wordpress desktop app received a completely different error message when encountering this issue, which offered little to no information about the error.

### Describe the solution you'd like 
On the plugin landing page, clearly communicate to users that PHP 7.4 is a requirement to access this integration and provide a link to instructions or a link to a resource on how to upgrade.

**Comment by findingsimple** [comment]
Closing in favor of https://github.com/woocommerce/pinterest-for-woocommerce/issues/215

Reducing to 7.3 should cover the majority of users based on our stats - we can stick with the php version notifications that are part of WP, WC and the marketplaces already.
