### ISSUE TITLE
Do not sync hidden/out of stock products

### ISSUE THREAD

**Issue by wjia88** [woocommerce/pinterest-for-woocommerce#206]
### Describe the bug:
During catalog ingestion, all products, including products that were marked as hidden/out of stock by the user were synced.

One user noticed that some products that were Out of Stock (and hidden from customers) in her store had been synced to Pinterest after ingestion was complete. Because of this, the user had to manually delete the undesired products from WooCommerce and wait for the integration to sync again, at which point the products were removed from Pinterest.

#### Expected behavior
By default if any products are marked as Out of Stock or Unavailable, do not include these in feed ingestion.

### Additional details:

Recommend updating the logic to check to make sure that
* Products are published (and not draft or private/password-protected) - For variations, we recommend checking the status of the parent variable product and not the child.
* Is a supported product type if relevant (e.g. simple products or variations etc..)
* Is visible in the store’s catalog (it’s not manually hidden from the store)

Out-of-stock products are by default visible and they become hidden only if the `woocommerce_hide_out_of_stock_items
` WooCommerce option is set to ‘yes’; therefore, we recommend only sync those out-of-stock products that are not hidden from the store catalog.

WooCommerce’s `\WC_Product::is_visible` method can be used to check if a product is visible or not. This internal method checks multiple options and applies filters to check whether a product should be visible in store’s catalog.

In Google listings & Ads if the product is a variation, we apply an internal WooCommerce filter called `woocommerce_hide_invisible_variations` to make sure that the variation is actually visible before syncing it. This is to mimic the conditions set by the `\WC_Product_Variable::get_available_variations` method to retrieve available variations. It confirms that disabled variations and variations with empty prices are not synced to Merchant Center.

**Comment by findingsimple** [comment]
> product that were marked as hidden / out of stock by the user were synced

Looking at the code, the extension does support the availability field and maps it to Woo stock status https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L219

My understanding is it should be fine to sync "out of stock" items based on this.

However...

I suspect we should better support the `woocommerce_hide_out_of_stock_items` options

<img width="610" alt="Screen Shot 2021-10-12 at 9 41 42 pm" src="https://user-images.githubusercontent.com/355014/136945622-fe30d0a3-9dab-4edb-99f6-96c5f702e68f.png">

I suspect we should better support the Catalog Visibility option and not sync a product if it is set to "Hidden"
<img width="319" alt="Screen Shot 2021-10-12 at 9 31 14 pm" src="https://user-images.githubusercontent.com/355014/136944065-f00f9f9e-60af-4869-b400-ce37b1ce1a0e.png">

And also password protected products etc.

**Comment by findingsimple** [comment]
Has been included within the feed generation refactor work https://github.com/woocommerce/pinterest-for-woocommerce/pull/284
