### ISSUE TITLE
Multiple product pins created for variants of a single product

### ISSUE THREAD

**Issue by wjia88** [woocommerce/pinterest-for-woocommerce#207]
### Describe the bug:
One user who had several size/flavor variations for some products noticed that a product Pin was created only for a single variation of the product. For example, if a product had several flavor and size options to choose from, the product Pin that was created by the integration only showed the information (image, price, title) for one variation of the product. 

### Steps to reproduce:

1.
2.
3.

#### Expected behavior
If a product has more than one variation (flavor, size, color, etc.) create a single product Pin but include information regarding all the available options.

### Additional details:

![Screen Shot 2021-09-17 at 1 33 54 PM](https://user-images.githubusercontent.com/89154337/133850294-9d4b75a3-db88-4200-98ce-b966df0c796e.png)

**Comment by findingsimple** [comment]
Marked as on-hold, waiting for some additional information

**Comment by findingsimple** [comment]
Closing in favor of

https://github.com/woocommerce/pinterest-for-woocommerce/issues/241
https://github.com/woocommerce/pinterest-for-woocommerce/issues/242
https://github.com/woocommerce/pinterest-for-woocommerce/issues/243
