### ISSUE TITLE
Simplify register_feed()

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#223]
This is a follow up from https://github.com/woocommerce/pinterest-for-woocommerce/issues/211

See https://github.com/woocommerce/pinterest-for-woocommerce/issues/211#issuecomment-932209153

> in register_feed we are trying to find feed profiles created by Woo plugin. register_feed code can be simplified by using `/v3/catalogs/<merchant>/feed_profiles/` api which returns all feed profiles for a merchant and includes which feed profiles were created by Woo.

We can include this as part of multi feed effort (will cross-link when we have some issue/s).

**Comment by budzanowski** [comment]
Fixed with https://github.com/woocommerce/pinterest-for-woocommerce/pull/305
