### ISSUE TITLE
feed xml: Remove parent item node when child items (variants are present)

### ISSUE THREAD

**Issue by ghost** [woocommerce/pinterest-for-woocommerce#242]
Feed xml includes both parent item and child items (variants). Pinterest feed ingestion creates pins for parent item as well as child items. 

For e.g. in attached sample xml [sample.txt](https://github.com/woocommerce/pinterest-for-woocommerce/files/7481057/sample.txt)

Parent item 12 V-Neck T-Shirt has 3 child items and on pinterest 4 pins are created.

![Screen Shot 2021-10-22 at 9 25 37 AM](https://user-images.githubusercontent.com/81649037/140469935-9edef56e-0514-450f-9ce5-40a02d326e7a.png)

Parent item needs to be removed from feed xml

**Comment by findingsimple** [comment]
Just noting that that refactor branch includes the fix for this https://github.com/woocommerce/pinterest-for-woocommerce/pull/271
