### ISSUE TITLE
PHP Fatal Error on accessing REST API endpoint

### ISSUE THREAD

**Issue by AchalJ** [woocommerce/pinterest-for-woocommerce#244]
### Describe the bug:
On accessing "wp-json/wc/v1" when non-logged in, it throws the below error.

PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /apps/wordpress/htdocs/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php:191

### Steps to reproduce:
1. Setup a WooCommerce Store
2. Install Pinterest for WooCommerce plugin
3. Now try accessing the endpoint without login. For example, yoursite.com/wp-json/wc/v1 

### Additional details:
```
Stack trace:
#0 /apps/wordpress/htdocs/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php(340): Automattic\WooCommerce\Pinterest\Tracking::get_hashed_customer_email()
#1 /apps/wordpress/htdocs/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php(79): Automattic\WooCommerce\Pinterest\Tracking::base_tag()
#2 /apps/wordpress/htdocs/wp-includes/class-wp-hook.php(303): Automattic\WooCommerce\Pinterest\Tracking::maybe_init()

**Comment by apmwebdev** [comment]
A customer encountered this issue in 4434890-zen

**Comment by Amaury-T** [comment]
Same issue here with judgeme endpoint (wp-json/judgeme/v1/domain_check)
When non logged in, error is thrown. It totally break the judgeme functionnality as I can't no more have reviews pushed on my shop.

If I disable Enhanced Match support setting, it resolve the problem.

Thanks for the help

`2021-11-06T01:17:41+00:00 CRITICAL Uncaught Error: Call to a member function get() on null in /www/example_664/public/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php:191
Stack trace:
#0 /www/example_664/public/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php(340): Automattic\WooCommerce\Pinterest\Tracking::get_hashed_customer_email()
#1 /www/example_664/public/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php(79): Automattic\WooCommerce\Pinterest\Tracking::base_tag()
#2 /www/example_664/public/wp-includes/class-wp-hook.php(303): Automattic\WooCommerce\Pinterest\Tracking::maybe_init('')
#3 /www/example_664/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#4 /www/example_664/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /www/example_664/public/wp-settings.php(578): do_action('init')
#6 /www/example_664/public/wp-config.php(110): require_once('/www/example...')
#7 /www/example_664/public/wp-load.php(50): require_once('/www/example dans /www/example_664/public/wp-content/plugins/pinterest-for-woocommerce/src/Tracking.php à la ligne 191`

**Comment by findingsimple** [comment]
> If I disable Enhanced Match support setting, it resolve the problem.

Thanks @Amaury-T that is a missing piece of the puzzle for how to replicate - need to have Enhanced Match enabled

**Comment by ecgan** [comment]
The fix for this issue has been released in https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.1.
