### ISSUE TITLE
XML file takes thumbnails instead of the normal size images

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#248]
Issue reported in the forums for investigation https://wordpress.org/support/topic/xml-file-takes-thumbnails-instead-of-the-normal-size-images/

`wp_get_attachment_image_src()` is being used to populate `additional_image_link`.

https://github.com/woocommerce/pinterest-for-woocommerce/blob/eb98cfed04cf5d2bba72c98f500e59ee0ae46899/src/ProductsXmlFeed.php#L300-L324

 It defaults to `thumbnail` size](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/)

Full or large size images should be used instead of low res thumbnails.

**Comment by ChristianAF** [comment]
@jconroy seems to be an issue, when product images gallery has some images attached, the XML feed is getting the thumbnails, here is an example: check the tag <g:additional_image_link>

```
<item>
<g:id>38</g:id>
<title>
<![CDATA[ Polo ]]>
</title>
<description>
<![CDATA[ Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. ]]>
</description>
<g:product_type>Tshirts</g:product_type>
<link>
<![CDATA[ https://corporate-damselfly.jurassic.ninja/product/polo/ ]]>
</link>
<g:image_link>
<![CDATA[ https://corporate-damselfly.jurassic.ninja/wp-content/uploads/2021/11/polo.jpg ]]>
</g:image_link>
<g:availability>in stock</g:availability>
<g:price>20USD</g:price>
<g:mpn/>
<g:additional_image_link>
<![CDATA[ https://corporate-damselfly.jurassic.ninja/wp-content/uploads/2021/11/tshirts-150x150.jpg,https://corporate-damselfly.jurassic.ninja/wp-content/uploads/2021/11/accessories-150x150.jpg,https://corporate-damselfly.jurassic.ninja/wp-content/uploads/2021/11/hoodies-150x150.jpg ]]>
</g:additional_image_link>
</item>

**Comment by findingsimple** [comment]
Thanks @ChristianAF , I've updated with some quick findings.
