### ISSUE TITLE
Multiple catalog created on pinterest with no possibility to delete them

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#249]
Placeholder for forum issue to come back to investigate https://wordpress.org/support/topic/multiple-catalog-created-on-pinterest-with-no-possibility-to-delete-them/

Will update with more information when I have a moment

**Comment by ChristianAF** [comment]
It's related to #166 , When user deactivate "Product Sync" option, and then activate it again is going to create another feed on Pinterest side. Also the API not allow removal of feeds. @ksere can confirm

**Comment by budzanowski** [comment]
This should be closed by #305
