### ISSUE TITLE
Pinterest Ads Manager CTA

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#252]
**Problem:** Currently when merchants complete setup there is no prompt/next step/indication that they can run paid ads.

**Goal:** After merchants have completed setup, they should understand they can run paid campaigns on Pinterest and have an active ads credit if eligible.

**Initial Requirements:**
* Display a link/button/cta encouraging merchants to continue to set up ads

**Technical Detail**
* The button/link/cta will deep link the merchant into their Pinterest account to continue ads setup.
* The link is a simple static link (not dynamically generated per user etc.)
* Link url to be confirmed with Pinterest

**Expected UI Implications: **

New UI elements required:
* Update catalog overview with banner/link through to Pinterest Ads Manager

![Catalog](https://user-images.githubusercontent.com/355014/141228185-e874f571-6b42-497c-8095-e1946013539d.png)

**Comment by findingsimple** [comment]
`https://ads.pinterest.com/` can be used as a placeholder URL for now.

**Comment by ianlin** [comment]
@jconroy 

The screenshot of the catalog overview you've attached is different from what I saw on my local development environment.

This is what I saw (please ignore all the red warnings 😅):

<img width="1554" alt="Screenshot 2021-11-18 at 11 20 01" src="https://user-images.githubusercontent.com/914406/142345881-6cdefbaf-c699-4e63-abe8-1a080e9528cd.png">

Is this because we're using different version of the plugin? If not, can you please guide me where can I find the page as in your screenshot?

Thanks!

**Comment by findingsimple** [comment]
Hi @ianlin its the same page, you're just missing the Issue to resolve section because the feed isn't connected.

@shivanarrthine should the ads CTA display at the bottom of the overview section all the time or just once everything is green?

**Comment by findingsimple** [comment]
Just trying to figure out if it will be better to work off https://github.com/woocommerce/pinterest-for-woocommerce/pull/240 as your base initially

**Comment by findingsimple** [comment]
@ianlin - use #240 for now

**Comment by ianlin** [comment]
@jconroy Got it, thanks for checking it!

**Comment by shivanarrthine** [comment]
> should the ads CTA display at the bottom of the overview section all the time or just once everything is green?

I think we can display it all the time - no harm in letting users browse possible features while waiting for the catalog to sync. Unless there's anything preventing them from accessing the Ads manager site until they've set up successfully.

**Comment by findingsimple** [comment]
Thanks @shivanarrthine !
