### ISSUE TITLE
Deprecated function log: Onboarding:should_show_task.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#259]
### Describe the bug:

In WC5.9 Onboarding:should_show_task() was deprecated. TaskList API should be used instead.

### Steps to reproduce:

1. Install and activate the plugin.
2. Go to Marketing -> Pinterest
3. Error should be in logs or directly on screen depending on logging settings.

![image](https://user-images.githubusercontent.com/17271089/141759600-f125dfbb-c912-411e-b1b7-990afc72020b.png)

#### Expected behavior

Menu opens without issues.

#### Actual behavior

Deprecation information.

**Comment by findingsimple** [comment]
Related https://github.com/woocommerce/pinterest-for-woocommerce/issues/259
