### ISSUE TITLE
An invalid external link on step three of onboarding setup

### ISSUE THREAD

**Issue by eason9487** [woocommerce/pinterest-for-woocommerce#262]
### Describe the bug:

Found this issue from https://github.com/woocommerce/pinterest-for-woocommerce/pull/261#discussion_r750068297.

The property `SetupTracking` doesn't exist in the `wcSettings.pinterest_for_woocommerce.pinterestLinks`.

### Steps to reproduce:

1. Head to step three of onboarding setup - `/wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fonboarding&step=setup-tracking`
2. Click on the "**Read more**" link in the main section description.

#### Expected behavior

❓  I couldn't find the relevant documents about the missing URL or expected behavior. Probably it should open an external page on a new tab, or a tooltip?

#### Actual behavior

Nothing happened.

![Kapture 2021-11-16 at 18 03 27](https://user-images.githubusercontent.com/17420811/141964693-e27e5465-f44f-43fd-bddc-2ac4cb7580e4.gif)

### Additional details:

When fixing this issue, the related naming and tracking might need to be adjusted as well.
- https://github.com/woocommerce/pinterest-for-woocommerce/blob/47bc121d82e979dcf97f19b0f2a8148a4014afee/assets/source/setup-guide/app/steps/SetupTracking.js#L43
- https://github.com/woocommerce/pinterest-for-woocommerce/blob/47bc121d82e979dcf97f19b0f2a8148a4014afee/assets/source/setup-guide/app/steps/SetupTracking.js#L376-L388

**Comment by findingsimple** [comment]
@shivanarrthine 👋 do you happen to know what should be happening with this link?

**Comment by shivanarrthine** [comment]
> do you happen to know what should be happening with this link?

@jconroy Not too sure where it's meant to link to but we can link it to the Pinterest documentation regarding the Pinterest tag: https://help.pinterest.com/en/business/article/install-the-pinterest-tag

**Comment by findingsimple** [comment]
Thanks @shivanarrthine !
