### ISSUE TITLE
Request to omit zero cost products from Pinterest feed

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#265]
### Is your feature request related to a problem? 
(https://wordpress.org/support/topic/request-to-omit-zero-cost-products-from-pinterest-feed/)

 > I have about 100 products in my shop that are free downloads, so the product price is $0.00. This is a lead magnet to get my customers to my online shop to buy digital products. On Pinterest side, it always shows an Error 113 for the 101 free products, as Pinterest does not accept 0 values for price.
> 
> Error 113: “Some items have price value formatting errors in product metadata, so those items will not be published”

#### How to reproduce the problem
Add products to WooCommerce with price = 0.00

### Describe the solution you'd like 

> If possible, would you make a change to exclude any products with zero cost from the feed in a future release? Many in my industry follow these same practices of offering zero cost items. So, this is more of an enhancement request. Perhaps an option to exclude products in the future using the settings?

**Comment by ghost** [comment]
@jconroy Pinterest does not support ingesting $0.00 price products. We need to filter out these on feed creation.

**Comment by findingsimple** [comment]
thanks for confirming @niketpins

**Comment by findingsimple** [comment]
Making a note that this should be [checked against the refactor branch](https://github.com/woocommerce/pinterest-for-woocommerce/pull/271) - if still an issue the PR can probably target that branch too
