### ISSUE TITLE
Consider still providing users with the external link about the enhanced match

### ISSUE THREAD

**Issue by eason9487** [woocommerce/pinterest-for-woocommerce#267]
It's a follow-up mentioned in #253 by @ianlin:

> One suggestion regarding the current flow: as a customer I would like to know more information about each setting on the Pinterest site as I might not be able to understand it from a simple description on the tooltip. A better approach could be adding a `See more` link on the tooltip and it will open a new tab to the Pinterest site for more information about that setting when I click on it.

### Additional context 

We removed the external link https://help.pinterest.com/en/business/article/enhanced-match from #253. And Ian provides a suggestion that we could still provide the link to customers.

// cc @shivanarrthine

**Comment by budzanowski** [comment]
@j111q or @shivanarrthine could you please confirm if https://github.com/woocommerce/pinterest-for-woocommerce/pull/253#pullrequestreview-805741454  approach is the valid one? Or should we use something else.

@alexiglesias31 after confirmation please implement.

**Comment by shivanarrthine** [comment]
@budzanowski Just to clarify, are we talking about a new implementation with a link within the tooltip or has it already been implemented? I'm good with including the link. In other designs we implemented the tooltip with a white background so the link (in blue) is visible, or perhaps we could keep the link in white text but underlined if we go with the dark background.

**Comment by budzanowski** [comment]
@shivanarrthine new implementation.

> I'm good with including the link.

Great. Thanks for confirming.

> In other designs we implemented the tooltip with a white background so the link (in blue) is visible, or perhaps we could keep the link in white text but underlined if we go with the dark background.

@alexiglesias31 ^ whichever is easier to implement 😄

**Comment by alexiglesias31** [comment]
Hey @budzanowski @shivanarrthine 
Just to be clear, we are adding an external link for the AEM support.

![image](https://user-images.githubusercontent.com/40774170/217529041-8fdeed9d-62d3-47b2-ad76-0afcd623fe0c.png)

Are we following the same approach for the link on enhanced match or a different one?

**Comment by shivanarrthine** [comment]
@alexiglesias31 This would be a different approach - more just adding links to the tooltips / help content. For AEM, we kept a separate link because it's additional settings they can configure.
