### ISSUE TITLE
Onboarding page is blank, for merchants with pluign "Advanced Coupons for WooCommerce Free" activated

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#270]
### Describe the bug:
https://wordpress.org/support/topic/plugin-landing-page-is-blank/

--------

When the plugin "Advanced Coupons for WooCommerce Free" is active, users can't do the onboarding because they see a blank page.
![image](https://user-images.githubusercontent.com/43881685/142854328-cafd074e-3bd9-4383-ba95-daba06ad6052.png)

### Steps to reproduce:
1. On a clean WP/WC site, install "Advanced Coupons for WooCommerce Free" plugin and activate it.
2. Install "Pinterest for WooCommerce" and activate it.
3. Go to Marketing > Pinterest

#### Expected behavior
Merchant can do the onboarding without problem

#### Actual behavior
blank page is shown to Merchant.

**Comment by ChristianAF** [comment]
Maybe we also should contact the developers of "Advanced Coupons for WooCommerce Free"

**Comment by findingsimple** [comment]
Thanks @ChristianAF !

Similar issue reported here https://github.com/woocommerce/google-listings-and-ads/issues/1059

Hi @jkohlbach 👋 We've got another report in a different extension - just an FYI for your fixes
