### ISSUE TITLE
WordPress 5.9 Compatibility Testing

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#289]
[WordPress 5.9](https://href.li/?https://make.wordpress.org/core/5-9/) is scheduled for release on ~December 14th~ 25th January

Perform smoke and compatibility testing to make sure the extension maintains compatibility with the upcoming release.

Fix any issues identified.

Updated tested up to tags as necessary.

> WordPress 5.9 will be the third major release of 2021 and will focus on blocks and intrinsic web design, navigation menus, interface for theme.json, refining editing flows for block themes, additional design tools, and a new default theme. Additionally its possible that the release will also include pattern insertion and creation, unzip/rollback failsafes, PHPUnit tests, and improved compatibility with PHP 8.0 and 8.1.

**Comment by ChristianAF** [comment]
Hey @jconroy for future releases, with which version you prefer to test the plugin? Beta, Release Candidate or released ?

**Comment by findingsimple** [comment]
@ChristianAF RC is usually best and typically when I'll look to create these issues

Marked as done by @ksere
