### ISSUE TITLE
Rename documentation-link-props to tracked-link-props

### ISSUE THREAD

**Issue by puntope** [woocommerce/pinterest-for-woocommerce#298]
### Is your feature request related to a problem? 
Related to #297, #261  and #232 

The `documentation-link-props` was created to avoid code duplication for documentation-link-click events. 
Since the params are exactly the same as `get_started_notice_link_click`  and potentially `modal_link_click` I suggest to rename and relocate the file and function name.

### Describe the solution you'd like 

`documentationLinkProps` function name will be -> `trackedLinkProps` 
`documentation-link-props` file name will be -> `tracked-link-props`
Location of helper functions in `/setup-guide/helpers` -> will move to `/helpers`

**Comment by tomalec** [comment]
I like the intention to avoid duplicated code, and cleaner naming.

But I have a few doubts about the proposal above:
1. I would expect the "tracked link props" to be usable for any trackable link also for the internal. But the main purpose of the current implementation is to provide defaults for an external link.
   > The `documentation-link-props` was created to avoid code duplication for documentation-link-click events.

   Precisely: The `documentation-link-props` was created to avoid code duplication for creating external documentation link properties, including firing tracking events.
2. The links provided in getting started, look to me as documentation links as well. So I'd consider `documentationLinkProps` still a valid name to be used here. There are just a bit more specific subset/subclass of those links.
3. As proposed in https://github.com/woocommerce/pinterest-for-woocommerce/pull/299/files#r771725484 we don't even need to change the `documentationLinkProps` implementation, to let the Notice components use a more specific name
