### ISSUE TITLE
Refactor - Move tracking.test.js tests to specific component tests. 

### ISSUE THREAD

**Issue by puntope** [woocommerce/pinterest-for-woocommerce#306]
### Is your feature request related to a problem? 

This issue depends on #299 and #300 

After discussion we decided to move the test in their own component file tests instead of having them inside a generic `tracking.test.js` function. 

### Describe the solution you'd like 
- Create generic mocks for `@woocommerce/tracks` and `@woocommerce/settings`
- Create `ClaimWebsite.test.js` to perform the testing for that component
- Create `UnsupportedCountryNotice.test.js`  to perform the testing for that component
- Create `PrelaunchNotice.test.js`  to perform the testing for that component
- Remove `tracking.test.js`

### Additional context 

`tracking.test.js` was in order to avoid duplication in the testing. However, with a minimum of work with the mocks, we can reduce duplication and have independent test files per component in order to make it easier to localise the testing files. 

see https://github.com/woocommerce/pinterest-for-woocommerce/pull/300#discussion_r771510864

**Comment by tomalec** [comment]
I think having those separate could help avoiding conflicts like this one :) 
![image of 80% of the file being a merge conflic](https://user-images.githubusercontent.com/17435/147006285-b23cfbd1-b7e3-4a21-a7b5-06eed4f24500.png)

**Comment by tomalec** [comment]
Also, I missed that in https://github.com/woocommerce/pinterest-for-woocommerce/pull/299#pullrequestreview-837920276, but `assets/source/tests/dependencies/woocommerce/settings.js` should return a named export. Maybe that could be fixed with one of the following PRs
