### ISSUE TITLE
Peculiar ( probably a bug ) logic around variable products price in the feed xml.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#319]
### Describe the bug:
While working on UT for feed generation I have observed two interesting code sections:

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L274-L276
 
and

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L297-L301

in my understanding the:
```PHP
! $product->get_parent_id()
```
is false for variation products so we will never fetch their values using their specific functions.
What should be the actually desired behavior? Always use non-variation functions ( this means that we can remove the `if` completely ) or should we fix the logic and use variation functions.?

#### Expected behavior
Don't really know.

**Comment by ksere** [comment]
> in my understanding the:
> 
> ```
> ! $product->get_parent_id()
> ```
> 
> is false for variation products so we will never fetch their values using their specific functions.

The full conditions:

```! $product->get_parent_id() && method_exists( $product, 'get_variation_price' )```
& 
``` ! $product->get_parent_id() && method_exists( $product, 'get_variation_sale_price' )```

Are true for variable products (parent) but not their variations (children), so that the correct ["min"](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-product-variable.php#L97) price is shown.

**Comment by budzanowski** [comment]
Absolutely. I misread variation for variable and confused myself with the logic. Thank you for clearing this for me.
