### ISSUE TITLE
ProductsXmlFeed::description does not strip the HTML tags.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#323]
### Describe the bug:
According to the documentation, the description filed does not support the HTML tags and sets no limit on characters and the length of the description.

![image](https://user-images.githubusercontent.com/17271089/148959475-09a2b984-ea4e-459c-9cc2-3bab0422a4a8.png)
from https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs

The function that is creating the feed file XML should be aware of these limitations. Right now it is not doing any formatting/stripping. 

#### Expected behavior
`ProductsXmlFeed::description` should create XML that conforms the requirements in the documentation.

Requirements to finish this item:

- [ ] Modify the method in such a way that it produces output according to the requirements in the documentation.
- [ ] Add unit tests that test the new functionality.

**Comment by findingsimple** [comment]
As outlined in https://github.com/woocommerce/pinterest-for-woocommerce/issues/247 - a merchant outline[ from forum topic](https://wordpress.org/support/topic/i-know-its-new-and-its-probably-on-the-roadmap-already/#post-15052643) here identified that HTML and shortcodes were not being stripped

There is an original PR that indicates both HTML and shortcodes were being stripped https://github.com/woocommerce/pinterest-for-woocommerce/pull/85 but perhaps a regression was introduced at some point
