### ISSUE TITLE
Constantly generation transients on wp-options

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#336]
### Describe the bug:
When tracking conversion is activated, transients are constantly being generated on wp_options. it's a problem for site with high traffic.

### Steps to reproduce:
1. Install Pinterest for WooCommerce
2. Navigate on the site 
3. go to the table wp_options

### Expected behavior:
no transients created

### Actual behavior:
transients are created on wp_options

### Additional details:
https://saucal.zendesk.com/agent/tickets/8792

**Comment by findingsimple** [comment]
Looks like there is a save event hooked into shutdown which would be firing a lot.

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Tracking.php#L105

This tracking implementation looks like it could do with a review.
