### ISSUE TITLE
Few api endpoint /v3/catalog/partner/connect/ requests are failing

### ISSUE THREAD

**Issue by niketuec** [woocommerce/pinterest-for-woocommerce#354]
### Describe the bug:
Reason: Pinterest allow users to claim domain with paths (e.g. https://xxz.com/en-US/ might be claimed by one user and  https://xxz.com/en-en_GB/ claimed by another user)
When merchant domains are passed with path one verification step is failing 

### Steps to reproduce:

1. invoke /v3/catalog/partner/connect/ with merchant domain as domain + path

### Expected behavior:
merchant_domain parameter in request should only contain domain from Woo not with path

### Actual behavior:
merchant_domain parameter in request contain domain with path

Currently during domain verification plugin invokes following APIs 
1. https://developers.pinterest.com/docs/redoc/#operation/v3_verification_code_GET to get verification code
2. https://developers.pinterest.com/docs/redoc/#operation/v3_verify_domain_POST to verify domain

This restricts verification to only domain level not with domain+path.

Please switch to following APIs
1. https://developers.pinterest.com/docs/redoc/#operation/v3_verification_code_for_website_GET to get verification code
2. https://developers.pinterest.com/docs/redoc/#operation/v3_verify_website_POST to verify website

Differences in domain and website API: 
- Instead of hostname you need to pass get_home_url() which is passed in merchant connect. 
- pass website in query parameter instead of path as per documentation
- can_claim_multiple param is not needed. can_claim_multiple is True for requests coming for website apis.

**Comment by findingsimple** [comment]
Additional details provided via slack e.g.

> For website verification (domain + path) there is another api https://developers.pinterest.com/docs/redoc/#operation/v3_verify_website_POST It is similar to domain

@niketuec @niketpins will update the issue
