### ISSUE TITLE
[p1] Uninstalling/deactivating the plugin fails when I had WooCommerce plugin installed but not activated

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#360]
### Describe the bug:
Uninstalling/deactivating the plugin fails when I had WooCommerce plugin installed but not activated
### Steps to reproduce:

1. Create a new jurassic.ninja instance
2. Install WooCommerce plugin but DONT activate it
3. Install WooCommerce for pinterest plugin (1.0.3 used for the bug) and activate it
3. Uninstalling/deactivating the WooCommerce for pinterest plugin 

### Expected behavior:
No errors during the process.

### Actual behavior:
Saw this stacktrace error
"
Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Pinterest\as_unschedule_all_actions() in /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-content/plugins/pinterest-for-woocommerce/src/ProductSync.php:661 Stack trace: #0 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-content/plugins/pinterest-for-woocommerce/pinterest-for-woocommerce.php(119): Automattic\WooCommerce\Pinterest\ProductSync::cancel_jobs() #1 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-includes/class-wp-hook.php(307): {closure}(false) #2 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #3 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #4 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-admin/includes/plugin.php(812): do_action('deactivate_pint...', false) #5 /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-admin/plugins.php(209): deactivate_plugins('pinterest-for-w...', false, false) in /srv/users/usera278ef7d/apps/usera278ef7d/public/wp-content/plugins/pinterest-for-woocommerce/src/ProductSync.php on line 661"

### Additional details:

![Screen Shot 2022-02-08 at 1 44 54 PM](https://user-images.githubusercontent.com/1510328/153258403-1ddeeb4f-b12b-4957-b207-00c091a7a035.png)

**Comment by liveme** [comment]
The problem occurs again! 
Wordpress v6.7.2
Pinterest for WooCommerce v1.4.16
WooCommerce v9.6.1 

`[13-Feb-2025 07:09:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Pinterest\as_unschedule_all_actions() in /www/wwwroot/wordpress/wp-content/plugins/pinterest-for-woocommerce/src/CommerceIntegration.php:50
Stack trace:
#0 /www/wwwroot/wordpress/wp-content/plugins/pinterest-for-woocommerce/class-pinterest-for-woocommerce.php(807): Automattic\WooCommerce\Pinterest\CommerceIntegration::maybe_unregister_retries()
#1 /www/wwwroot/wordpress/wp-content/plugins/pinterest-for-woocommerce/uninstall.php(17): Pinterest_For_Woocommerce::disconnect()
#2 /www/wwwroot/wordpress/wp-admin/includes/plugin.php(1314): include_once('...')
#3 /www/wwwroot/wordpress/wp-admin/includes/plugin.php(970): uninstall_plugin()
#4 /www/wwwroot/wordpress/wp-admin/includes/ajax-actions.php(4771): delete_plugins()
#5 /www/wwwroot/wordpress/wp-includes/class-wp-hook.php(324): wp_ajax_delete_plugin()
#6 /www/wwwroot/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /www/wwwroot/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /www/wwwroot/wordpress/wp-admin/admin-ajax.php(192): do_action()
#9 {main}
  thrown in /www/wwwroot/wordpress/wp-content/plugins/pinterest-for-woocommerce/src/CommerceIntegration.php on line 50
`
