### ISSUE TITLE
[p3] Unable to reconnect from different account after selecting personal account

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#361]
### Steps to reproduce:

1. Initialize registration process after creating a personal account on pinterest
2. Try disconnecting and reconnecting from some other user. 
3. When you click on get started after disconnection same user is connected

### Expected behavior:
We should be able to connect a different account

### Actual behavior:
When you click on get started after disconnection same user is connected

**Comment by niketuec** [comment]
Screen recording
https://user-images.githubusercontent.com/3583093/153300772-b03c7943-bed7-4ce2-a509-c56378183227.mov
