### ISSUE TITLE
Double pin button show when pinterest plugin is installed

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#362]
### Steps to reproduce:
1. Install pinterest Chrome extension https://chrome.google.com/webstore/detail/pinterest-save-button/gpdjojdkbbmdfjfahjcgigfpmkopogic?hl=en
2. Ensure "Save to Pinterest" enabled in Woocommerce for Pinterest settings
3. Observe products end up with two Pinterest save buttons

### Expected behavior:
Only one pin button to be present

### Actual behavior:
Multiple pin buttons are present

### Additional details:
![Screen Shot 2022-02-08 at 2 09 09 PM](https://user-images.githubusercontent.com/1510328/153259271-6bf3222e-f209-4885-bddc-4895b4546286.png)

**Comment by findingsimple** [comment]
> Only one pin button to be present

@adarshakb Does Pinterest have a recommendation on how this should be handled?

* Is there a way to detect product pins from the extension?
* Which product pins should be used by default? etc.

**Comment by adarshakb** [comment]
I am sorry, just saw your msg. I dont know what the ask is here. 

The pinterest plugin adds the save button to all images on the page. So I think detecting the browser plugin and disabling this feature is one way to handle it. 

We can wait for product input on it too and bring it up on a call

**Comment by findingsimple** [comment]
> I dont know what the ask is here.......The pinterest plugin adds the save button to all images on the page. So I think detecting the browser plugin and disabling this feature is one way to handle it.

@adarshakb I was curious if your team has a recommendation for how to detect if the browser plugin exists or if there is an API to detect the the existence of the browser plugin etc.

**Comment by budzanowski** [comment]
There is no API, but we can use some hacker magic to detect the plugin (testable directly in console):

```javascript
fetch(`chrome-extension://gpdjojdkbbmdfjfahjcgigfpmkopogic/html/save.html`)
      .then(() => ( console.log('Found')))
      .catch(() => ( console.log('Not Found')))
```

I am moving this ToDo In SAU/CAL - please investigate how this snippet can be used for blocking the additional button and implement blocking if possible.

**Comment by adarshakb** [comment]
https://chrome.google.com/webstore/detail/pinterest-save-button/**gpdjojdkbbmdfjfahjcgigfpmkopogic**?hl=en this is the extension and the ID I think remains constant. We can check for either /html/save.html or /manifest.json .

**Comment by budzanowski** [comment]
@adarshakb that is what basically my snippet achieves. This will work on chrome only though. That is OK in the scope of this issue, I think, bc we are only talking about chrome plugin here. Correct?

**Comment by alexiglesias31** [comment]
There is also a Firefox extension [here](https://addons.mozilla.org/en-US/firefox/addon/pinterest/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).

**Comment by budzanowski** [comment]
For Firedfox we can't really do anything. The plugins IDs are unique for each browser instances.
The method proposed above should also work for MS Edge if the plugin is installed from the Chrome store.

**Comment by alexiglesias31** [comment]
@budzanowski, another approach (slightly trickier) is to get the save pin button by the style attribute:

```javascript
jQuery( 'span[style*="data:image/svg+xml;base64,PHN2ZyBpZD0ic291cmNlIiB3aWR0aD0iMTIiIGhlaWdodD0iMTIiIHZpZXdCb3g9IjAgMCAxMiAxMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iNiIgY3k9IjYiIHI9IjYiIGZpbGw9IiNFNjAwMjMiPjwvY2lyY2xlPgo8cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTAgNkMwIDguNTYxNSAxLjYwNTUgMTAuNzQ4NSAzLjg2NSAxMS42MDlDMy44MSAxMS4xNDA1IDMuNzUxNSAxMC4zNjggMy44Nzc1IDkuODI2QzMuOTg2IDkuMzYgNC41NzggNi44NTcgNC41NzggNi44NTdDNC41NzggNi44NTcgNC4zOTk1IDYuNDk5NSA0LjM5OTUgNS45N0M0LjM5OTUgNS4xNCA0Ljg4MDUgNC41MiA1LjQ4IDQuNTJDNS45OSA0LjUyIDYuMjM2IDQuOTAyNSA2LjIzNiA1LjM2MUM2LjIzNiA1Ljg3MzUgNS45MDk1IDYuNjM5NSA1Ljc0MSA3LjM1QzUuNjAwNSA3Ljk0NDUgNi4wMzk1IDguNDI5NSA2LjYyNTUgOC40Mjk1QzcuNjg3IDguNDI5NSA4LjUwMzUgNy4zMSA4LjUwMzUgNS42OTRDOC41MDM1IDQuMjYzNSA3LjQ3NTUgMy4yNjQgNi4wMDggMy4yNjRDNC4zMDkgMy4yNjQgMy4zMTE1IDQuNTM4NSAzLjMxMTUgNS44NTZDMy4zMTE1IDYuMzY5NSAzLjUwOSA2LjkxOTUgMy43NTYgNy4yMTlDMy44MDQ1IDcuMjc4NSAzLjgxMiA3LjMzIDMuNzk3NSA3LjM5MDVDMy43NTIgNy41Nzk1IDMuNjUxIDcuOTg1IDMuNjMxNSA4LjA2OEMzLjYwNSA4LjE3NyAzLjU0NSA4LjIwMDUgMy40MzE1IDguMTQ3NUMyLjY4NTUgNy44MDA1IDIuMjE5NSA2LjcxIDIuMjE5NSA1LjgzNEMyLjIxOTUgMy45NDk1IDMuNTg4IDIuMjE5NSA2LjE2NTUgMi4yMTk1QzguMjM3NSAyLjIxOTUgOS44NDggMy42OTYgOS44NDggNS42NjlDOS44NDggNy43Mjc1IDguNTUwNSA5LjM4NDUgNi43NDg1IDkuMzg0NUM2LjE0MyA5LjM4NDUgNS41NzQ1IDkuMDY5NSA1LjM3OTUgOC42OThDNS4zNzk1IDguNjk4IDUuMDggOS44MzkgNS4wMDc1IDEwLjExOEM0Ljg2NjUgMTAuNjYgNC40NzU1IDExLjM0NiA0LjIzMyAxMS43MzU1QzQuNzkyIDExLjkwNzUgNS4zODUgMTIgNiAxMkM5LjMxMzUgMTIgMTIgOS4zMTM1IDEyIDZDMTIgMi42ODY1IDkuMzEzNSAwIDYgMEMyLjY4NjUgMCAwIDIuNjg2NSAwIDZaIiBmaWxsPSJ3aGl0ZSI+PC9wYXRoPgo8L3N2Zz4=' )
```

This approach detects both Chrome and Firefox extensions, but has the drawback that it will be useless if there are any changes to the SVG encoding.

**Comment by budzanowski** [comment]
I would just go with the fingerprints approach that I and @adarshakb have provided.
