### ISSUE TITLE
Store stays connected to Pinterest account after disconnecting. Prevents connecting with a different Pinterest account

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#363]
### Steps to reproduce:

1. Create a new store
2. Disconnect the store
3. connect it to another store

### Expected behavior:
Should allow users to connect to different pinterest account

### Actual behavior:
Prevents connecting with a different Pinterest account

### Additional details:

![1Cl8CMFtdVB_DXBkQBHyzFzyTlvYObS5438wgF0CA](https://user-images.githubusercontent.com/1510328/153259671-f3196ade-cb11-4eeb-9b1b-e25bdbd81c65.png)

**Comment by adarshakb** [comment]
Reduced the priority of the bug because it looks like this is the best path for now.

Its beecause domain/website can be sensitive ownership even inside the same company. The merchant always has the option to unclaim the domain/website from [pinterest.com](http://pinterest.com/) manually which make the action and goal explicit,

In future we can add the following updates

1. Show a popup to disconnect during deactivation... however lets wait for user feedback
2. we can auto un/reclaim the domain/website, if is LBA accounts under the same user

**Comment by findingsimple** [comment]
Thanks @adarshakb - moving to low priority and will remove from the SAU/CAL queue cc @alexiglesias31

**Comment by jacoswan** [comment]
Also observed in 5202662-zen.
