### ISSUE TITLE
When special characters are used on the SKU field of products, the feed is created with errors.

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#365]
### Steps to reproduce:

1. Edit a product and add a special character on the SKU field as "&"
2. Install "Pinterest for WooCommerce" and do the ondobarding 
3. Cehck the feed created

### Expected behavior:
Feed should be created with out problems

### Actual behavior:
Feed is created with errors.

**Comment by findingsimple** [comment]
> Feed is created with errors.

What are the errors @ChristianAF ?

**Comment by budzanowski** [comment]
I was thinking about this some time ago. The SKU field allows characters that are considered special for XML. We should just escape that. I have a PR #371 for that.
