### ISSUE TITLE
Fix shipping column format

### ISSUE THREAD

**Issue by niketuec** [woocommerce/pinterest-for-woocommerce#369]
### Describe the bug:
In xml format shipping information should come as 
```
<g:shipping>
    <g:country>UK</g:country>
    <g:service>Flat Rate</g:service>
    <g:price>0 GBP</g:price>
</g:shipping>
```

It was incorrectly communicated to add as `country:region:service:price`

### Expected behavior:
Add shipping information as 
```
<g:shipping>
    <g:country>UK</g:country>
    <g:service>Flat Rate</g:service>
    <g:price>0 GBP</g:price>
</g:sshipping>
```

**Comment by findingsimple** [comment]
Asked in slack, but will also add here

@niketuec can you confirm how do you structure it for multiple countries/destinations?
(related previous conversations last year - changes were needed to the shipping column to support multiple shipping destinations

**Comment by niketuec** [comment]
Multiple <g:shipping/> nodes are supported in an item. I just want to confirm from person who was working on this. He is in different timezone. will update here as soon as i hear back on this.

**Comment by budzanowski** [comment]
@niketuec The examples do not show the region as a valid option but I assume that we can use it `<g:region>`. Correct?

**Comment by niketuec** [comment]
Confirming multiple <g:shipping/> nodes are supported and also <g:region>

```
<g:shipping>
    <g:country>UK</g:country>
    <g:region>xyz</g:region>
    <g:service>Flat Rate</g:service>
    <g:price>10 GBP</g:price>
</g:shipping>
```
