### ISSUE TITLE
Product attributes Condition and Google Category fields can only be added to Simple/variable products

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#372]
### Describe the bug:
Condition and Google Category fields can only be added to Simple/variable products. For other products like Subscriptions after editing and saving, Condition and Google Category fields are still not saved.

### Steps to reproduce:

1. Install Pinterest plugin (1.0.2 or higher)
2. Edit a Subscription product
3. go to "Pinterest" Tab to edit the Attributes Condition and Google Category
4. Save
5. Go to "Pinterest" Tab again

### Expected behavior:
the Attributes Condition and Google Category are saved

### Actual behavior:
the Attributes Condition and Google Category are not saved

### Additional details:
For Simple/Variable products is working ok

**Comment by findingsimple** [comment]
@mikkamp was there a technical/support reason behind this? I'm guessing we copied the same approach as GLA.

**Comment by mikkamp** [comment]
> was there a technical/support reason behind this? I'm guessing we copied the same approach as GLA

Yes the same logic was copied as GLA where we support only specific product types. Although Subscriptions in particular shows/hides data fields for Simple/Variable products (depending on subscription type). So we added an additional [compatibility class](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Integration/WooCommerceSubscriptions.php) if the Subscriptions plugin was activated (that class didn't get added here).

Based on the description in this PR it sounds like Subscription products should be synced in the feed? Is that the intention, and if so is it correctly populating the feed with the subscription data?

Looks like the only product type we are excluding by default is "grouped". If we are going to include all other product types and expect their attribute data to be set for pinterest then we will need some changes to get it working for all other product types.

**Comment by findingsimple** [comment]
Marking as on-hold while waiting for confirmation about subscriptions support from @niketpins

**Comment by findingsimple** [comment]
Subscriptions aren't supported (but the "products" are) - however the price field doesn't really allow for all the different factors that go into a subscription product pricing model e.g.

![free-trial-sign-up-fee@2x](https://user-images.githubusercontent.com/355014/158925981-7338ddbb-8188-4ffe-9939-a65808f485f6.jpg)

Safest option at the moment is to exclude subscriptions products (like GLA) and we can circle back to this at a later point

**Comment by alexiglesias31** [comment]
@jconroy

> Safest option at the moment is to exclude subscriptions products (like GLA) and we can circle back to this at a later point

Just to clarify, does this mean that we are excluding the subscription products from the feed?

Also, we should hide the `Pinterest` product tab for Subscriptions too.
![Screenshot_20220523_090658](https://user-images.githubusercontent.com/40774170/169826278-9d8d0a82-b32b-4bb3-be2a-15cac02754b1.png)

**Comment by findingsimple** [comment]
Yes correct on both accounts.

**Comment by alexiglesias31** [comment]
@jconroy.
I wanna your confirmation if we should close this or not. As discussed here, the Subscriptions products were removed on #468.

**Comment by findingsimple** [comment]
@alexiglesias31 I was waiting to see what eventuated with the [discussion here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/468#issuecomment-1150752357)

**Comment by findingsimple** [comment]
> For other products like Subscriptions after editing and saving, Condition and Google Category fields are still not saved

@alexiglesias31 can you please confirm that even though we have dropped support for Subscriptions the core issue here "Product attributes Condition and Google Category fields can only be added to Simple/variable products" will still be present for other product types?

If that's the case then we need to look at [discussion here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/468#issuecomment-1150752357) and consider adjusting logic further

**Comment by alexiglesias31** [comment]
@jconroy

We are hiding the Condition and Google Category Tab on [Subscriptions products](https://github.com/woocommerce/pinterest-for-woocommerce/blob/942f7e0d6590c8b7dbeb67be85a9689a28f87648/src/Admin/Product/Attributes/AttributesTab.php#L196).

> can you please confirm that even though we have dropped support for Subscriptions the core issue here "Product attributes Condition and Google Category fields can only be added to Simple/variable products" will still be present for other product types?

The Condition and Google Category field will be present on the  [supported types](https://github.com/woocommerce/pinterest-for-woocommerce/blob/942f7e0d6590c8b7dbeb67be85a9689a28f87648/src/Admin/Product/Attributes/AttributesTab.php#L185).


I think we can hide the Condition and Google Category tab for every product type that is not included in the [supported types](https://github.com/woocommerce/pinterest-for-woocommerce/blob/942f7e0d6590c8b7dbeb67be85a9689a28f87648/src/Admin/Product/Attributes/AttributesTab.php#L185). That way we can have like a more "boolean" way of supporting Google Category.

**Comment by findingsimple** [comment]
I think that makes sense, @JPry do you concur? I believe this is how we handle it in other extensions.

**Comment by JPry** [comment]
> I think we can hide the Condition and Google Category tab for every product type that is not included in the [supported types](https://github.com/woocommerce/pinterest-for-woocommerce/blob/942f7e0d6590c8b7dbeb67be85a9689a28f87648/src/Admin/Product/Attributes/AttributesTab.php#L185). That way we can have like a more "boolean" way of supporting Google Category.

> @JPry do you concur?

This makes sense to me as well.
