### ISSUE TITLE
Low resolution pictures 

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#374]
### Describe the bug:
some merchants are complaining on the resolution of the images that gets the plugin.

complete thread: https://wordpress.org/support/topic/low-resolution-pictures/

### Expected behavior:
feed is created with the correct resolution of the image

### Additional details:
could be related to #248

**Comment by JPry** [comment]
@ChristianAF I did some looking into this issue, and what I found is that there could be some variation in image size depending on the theme in use. This extension is set to use `woocommerce_single` as the image size, as you can see here:

https://github.com/woocommerce/pinterest-for-woocommerce/blob/4aab3d8f992d5406f13fc635cb1cf697744eaa77/src/ProductsXmlFeed.php#L307

The `woocommerce_single` size can be determined by the theme that is in use. For example, the Storefront theme defaults this image size to `416`, as you can see here:

https://github.com/woocommerce/storefront/blob/7a90ed992dab4d46d30202204700ee4635ac3981/inc/woocommerce/class-storefront-woocommerce.php#L59

Other themes may set this differently. If the theme does not set this size at all, then the default width is `600`.

I can see how `600` might still not be ideal for sizing, but it would also help to have more information about what theme is in use and what (if any) size it sets for `woocommerce_single`.

It might make sense to add a filter to the size we use, and that would be a fairly simple feature request.

**Comment by findingsimple** [comment]
Thanks for the digging @JPry 

> 'woocommerce_single'

I feel like we should just be linking to the original file / full size if Pinterest can support it - not sure what the original history is behind the decision here.

@niketuec @adarshakb are there any restrictions on the upper limit of image sizes supported? The docs mention a lower (75x75) https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs

**Comment by alexiglesias31** [comment]
Great thread @jconroy @JPry.
This issue was treated on [PR #268](https://github.com/woocommerce/pinterest-for-woocommerce/pull/268).
`'woocommerce_single'` was used in order to prevent some kind of issues if an image is too big.
Probably we can setup a size limit and get the full size image or the `'woocommerce_single'` if the full size is too big.

**Comment by findingsimple** [comment]
Thanks @alexiglesias31 

> was used in order to prevent some kind of issues if an image is too big.

I can't see any discussion about the size being too big, do you know where that is?

Chatting with @niketuec @adarshakb I believe we should be ok to use the full size URL as Pinterest will process things on their end (unless you have an update after our call @niketuec  @adarshakb)

**Comment by alexiglesias31** [comment]
[This was the thread](https://github.com/saucal/pinterest-for-woocommerce/pull/1) where we mentioned the issue.
If using full size (unrestricted size) unlikely will cause any issue, then we will update the code in order to get the full size image.

**Comment by adarshakb** [comment]
width * height <= 89478485 of the image.Limit is only based on pixels not image size (in bytes). In general it would be good practice to limit it to 4k (3840 x 2160) max image size I think so may be limit it to around 5000x5000
