### ISSUE TITLE
Value for additional_image_link to big - Pinterest only supports 10 additional images

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#382]
### Describe the bug:
details: https://wordpress.org/support/topic/value-for-additional_image_link-to-big

### Steps to reproduce:

1. Add more than 10 aditional images to a product
2. install and setup Pinterest plugin
3. XML is ingested to Pinterest and shows the error.

**Comment by findingsimple** [comment]
Confirmed with Pinterest - Pinterest only supports up to 5 additional images

**Comment by findingsimple** [comment]
Placing on hold - some discrepancy on the Pinterest end - it might actually support more than that listed in the docs.

**Comment by findingsimple** [comment]
Update - the limit is actually exactly 10 additional image
