### ISSUE TITLE
Support Automatic enhanced match feature apart from email specific enhanced match

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#385]
## User story
Enhanced match in the plugin uses only email field https://help.pinterest.com/en/business/article/enhanced-match

We can upgrade this to use [Automatic enhanced match](https://help.pinterest.com/en/business/article/automatic-enhanced-match)

In setup: For automatic enhanced match, in setting we must provide users with higher level setting for disabling/enabling the feature. But also more granular setting like the ability to opt-in/out of name fields, other field types.

Legal: The language in the terms and conditions while connecting need to be updated.

Initial state: We can automatically opt-in the user when they connect for first time similar to enhanced match as long as Legal is clear on this. 

### Is your feature request related to a problem? 
Helps merchants better attribute Pinterest conversions

**Comment by adarshakb** [comment]
Here is the legal copy :
Enable automatic enhanced match
Enabling automatic enhanced match may improve the performance of your campaigns (return on ad spend and cost per action) and can help increase the size of your Pinterest tag audiences. Automatic enhanced match uses hashed information that your customers have already provided to your business to help match more of your website visitors and conversions to people on Pinterest. 
Learn more (---> Link goes to https://www.pinterest.com/_/_/help/business/article/automatic-enhanced-match)

**Comment by findingsimple** [comment]
@adarshakb 

> Legal: The language in the terms and conditions while connecting need to be updated.

Just confirming, that is an update on the Pinterest side right?

Within https://business.pinterest.com/business-terms-of-service/ or https://business.pinterest.com/en/pinterest-advertising-services-agreement ?

**Comment by findingsimple** [comment]
@adarshakb another question - would we replace standard Enhanced Match with AEM? Or have multiple options?

**Comment by adarshakb** [comment]
@jconroy - Since they are different features it would be 2 different options

**Comment by adarshakb** [comment]
link needs to be added/updated onboarding flo
<img width="123" alt="Screen Shot 2022-04-13 at 7 20 40 PM" src="https://user-images.githubusercontent.com/1510328/163301415-a3aa188c-19be-41df-a502-2f1dc39c4d7d.png">
w

**Comment by findingsimple** [comment]
I will update with links to designs and text in the next day. They are complete - just waiting for final confirmation of no feedback.

Would recommend developing using a feature branch with smaller PRs for review.

**Comment by findingsimple** [comment]
Figma: https://href.li/?https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3052%3A35818

Prototype: https://href.li/?https://www.figma.com/proto/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?page-id=2929%3A32327&node-id=3052%3A35818&viewport=155%2C503%2C0.04&scaling=scale-down&starting-point-node-id=3052%3A35705

**Comment by alexiglesias31** [comment]
@jconroy @adarshakb, just want to jump in to clarify a couple of details.

- Will AEM be enabled by default as displayed on [designs](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3052%3A35818)?
- Email, name, phone number, etc. are options under AEM. Are we getting this info from the checkout customer data?
- Is the AEM setting on the plugin readonly or should we sync to Pinterest when the user changes it?

**Comment by adarshakb** [comment]
>Will AEM be enabled by default

For new customers it can be enabled by default. Please ensure legal terms and conditions are linked correctly. Johnny Yu from pinterest should be able to help with that

>should we sync to Pinterest 

It should ideally be read only for v1 as there are many edgecases and the customer can be linked to their pinterest account to disable/enable it.

**Comment by alexiglesias31** [comment]
Thanks @adarshakb,

So, wrapping up. The idea is that enhanced match be enabled via API when a customer does the onboarding, right?
I suggest to enable setting when an user connects the plugin, since it may become difficult to determine if it's a brand new customer or an user re-connecting the site.

I will ask to Johnny Yu via Slack, or if you have his GH user you can ping him here.
