### ISSUE TITLE
For some stores on woocommerce duplicate events (pageVisit) are sent when page is cached

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#398]
### Steps to reproduce:

1. Install pinterest tag helper to help debug
2. goto https://lacrialeather.com/ you will see page visit event and everything successful for tags
3. refresh page, you will see duplicate tag warning.
4. now reload by clearing cache, you will see the warning go away
5. refresh again normally you will the duplicate error again

### Expected behavior:
only single page visit event should be sent
### Actual behavior:

https://user-images.githubusercontent.com/1510328/158911249-bbdcb69f-a947-4714-bcad-69c06a25e5fc.mp4

duplicate pagevisit events sent

**Comment by findingsimple** [comment]
Thanks @adarshakb 

I was able to replicate it.

When the error happens, viewing the page source I can see

```
<script> pintrk( 'track', 'pagevisit' );
pintrk( 'track', 'pagevisit' );</script>
```

**Comment by adarshakb** [comment]
<img width="1636" alt="Screen Shot 2022-03-21 at 9 57 26 AM" src="https://user-images.githubusercontent.com/1510328/159321145-85855669-f962-4164-aea9-78c381849737.png">
Here is another example... In this site https://www.kreidehelden.de/chalkboard-kategorie/briefe-fuer-kinder/

**Comment by findingsimple** [comment]
This actually looks to be similar / the same as 

https://github.com/woocommerce/pinterest-for-woocommerce/issues/359
https://github.com/woocommerce/pinterest-for-woocommerce/pull/357
