### ISSUE TITLE
AddToCart event for tags is missing some properties when access from different pages

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#400]
### Describe the bug:
Value and currency fields are missing when added to cart from some pages
### Steps to reproduce:

1. Visit https://navahair.us/shop/
2. Use add to cart directly on shop page
3. Use add to cart on the product detail page

### Expected behavior:
Both tags should have the values same (currency and value)

### Actual behavior:
Only some surfaces add these values

### Additional details:
![Screen Shot 2022-03-18 at 9 48 24 AM](https://user-images.githubusercontent.com/1510328/159050158-9c830208-5c91-4b56-8e1f-213752df0cef.png)
![Screen Shot 2022-03-18 at 9 48 04 AM](https://user-images.githubusercontent.com/1510328/159050173-b7a7e5b3-f436-4d9c-813f-041c55eaf06e.png)

**Comment by findingsimple** [comment]
Just adding some clarifying information.

When clicking add to cart on the shop page for a product - the events look like:

<img width="476" alt="Screen Shot 2022-03-23 at 1 07 58 pm" src="https://user-images.githubusercontent.com/355014/159613287-dc74403e-413c-4883-ad79-bb857644ac24.png">

But when adding from the product page it has additional `currency` and `value` properties

<img width="436" alt="Screen Shot 2022-03-23 at 1 08 40 pm" src="https://user-images.githubusercontent.com/355014/159613318-fb208548-b601-4640-96c9-76dc7032a297.png">

On the test site the shop page uses the AJAX add to cart while the product page is non ajax

The non-ajax event is located here (includes all values)

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Tracking.php#L213

While the ajax event is located here and misses similar properties

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Tracking.php#L298
