### ISSUE TITLE
Error with the generated catalog XML

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#401]
### Describe the bug:
May be due to encoding issues there are errors in the generated catalog XML for some merchants
### Steps to reproduce:

1. example XML https://www.greenhousebeautyct.com/wp-content/uploads/pinterest-for-woocommerce-Opc11Y.xml

### Expected behavior:
XML is properly generated

### Actual behavior:
XML has errors in the generation

### Additional details:
The above website is an approved woocomerce merchant with username mezzo87 on pinterest

**Comment by adarshakb** [comment]
More example of feedprofile parsing errors

- https://thextremeshopper.com/wp-content/uploads/pinterest-for-woocommerce-EohDwn.xml
- https://www.modelsandparts.co.uk/wp-content/uploads/pinterest-for-woocommerce-yhJ9s8.xml
- https://www.recuerding.com/wp-content/uploads/pinterest-for-woocommerce-Tm6D3K.xml
- https://la-maison-aria.com/wp-content/uploads/pinterest-for-woocommerce-j14s8L.xml
- https://bandsawblades.co.uk/wp-content/uploads/pinterest-for-woocommerce-kK7dLQ.xml
- https://kalpa.vn/wp-content/uploads/pinterest-for-woocommerce-o70apY.xml
- https://myfrenchcountryhomebox.com/wp-content/uploads/pinterest-for-woocommerce-9ryuOv.xml
- https://alturasiete.com/wp-content/uploads/pinterest-for-woocommerce-eAh1lu.xml
- https://puffandpencil.com/wp-content/uploads/pinterest-for-woocommerce-qjE1sY.xml
- https://www.royaldesign.nl/wp-content/uploads/pinterest-for-woocommerce-fIeM38.xml
- https://naturatopia.com/wp-content/uploads/pinterest-for-woocommerce-zh87m4.xml
- https://www.greenhousebeautyct.com/wp-content/uploads/pinterest-for-woocommerce-Opc11Y.xml
- https://amaroliaandcompany.com/wp-content/uploads/pinterest-for-woocommerce-ARaqj2.xml
- https://islaibizabonita.com/wp-content/uploads/pinterest-for-woocommerce-WJL3f3.xml

**Comment by adarshakb** [comment]
Internal query shows roughly 130+ feed profiles have errors in XML parsing

**Comment by budzanowski** [comment]
@adarshakb the #409 will close this one. I will open separate issues and PRs for distinct problems I have found in the broken feeds.
