### ISSUE TITLE
product price mismatch for some websites

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#402]
### Steps to reproduce:

1. Visit https://dagelijksebroodkruimels.nl/webshop/christelijke-boeken/bijbelse-dagboeken/dagboek-dagelijksebroodkruimels/
2. Add to cart
3. look at add to cart events

### Expected behavior:
The price should be same as shown in website

### Actual behavior:
The price is different in the event sent

### Additional details:
<img width="1393" alt="Screen Shot 2022-03-18 at 3 41 12 PM" src="https://user-images.githubusercontent.com/1510328/159094131-7b886d31-4600-434a-ab22-fd832ee39379.png">

**Comment by JPry** [comment]
@adarshakb What are the WooCommerce tax settings for the store? Are prices shown with tax included, or with tax excluded?

**Comment by adarshakb** [comment]
@JPry The above bug is from a production woocommerce account. Can you test which of the settings you mentioned causes the problem? When I searched in Woo commerce settings on wordpress, I couldn't find any such settings you are referring to.

**Comment by findingsimple** [comment]
@adarshakb tax settings are here https://woocommerce.com/document/setting-up-taxes-in-woocommerce/#configuring-tax-options - "prices entered with tax"

Looks like the feed is simply getting the regular price set https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L533 and not making any adjustments

**Comment by findingsimple** [comment]
Looking at other meta price fields embedded in the page source - they are also reporting the price as `22.9266055`

I looked up dutch sales tax rates - 0, 9% or 21% - doing a quick calculator I think the tax angle holds e.g.

<img width="773" alt="Screen Shot 2022-03-23 at 10 22 48 pm" src="https://user-images.githubusercontent.com/355014/159693408-2349faa2-22a5-4ae4-b617-4caa1d9074e0.png">

So if I understand Pinterest requirements correctly the price sent needs to match the price on the product page displayed to the merchant - which means we need to update things to account for the "display prices in the shop: Including/Excluding tax"

**Comment by findingsimple** [comment]
This is how we handle in GLA

https://github.com/woocommerce/google-listings-and-ads/blob/590c7ea6ae0b8ce41b6728415043f91fcd8ba0ed/src/Product/WCProductAdapter.php#L597-L627

**Comment by budzanowski** [comment]
> Looks like the feed is simply getting the regular price set https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L533 and not making any adjustments

So we have two issues. One is for the feed and another one is for the tag which is what @adarshakb is pointing to.

**Comment by findingsimple** [comment]
> One is for the feed and another one is for the tag

Good call out

**Comment by alexiglesias31** [comment]
We can have an edge case here imho.

If the tax settings are configured as follows:
- Display prices in shop and product pages excluding taxes
- Display prices in cart and checkout including taxes

How would we read the price (on events and feed) in this specific case?

![image](https://user-images.githubusercontent.com/40774170/161330689-9b1da46f-5ce8-4c69-9d88-719d2807481b.png)

**Comment by alexiglesias31** [comment]
cc @jconroy @budzanowski
