### ISSUE TITLE
Order id and value was not correctly in AddToCart tag event

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#405]
### Describe the bug:
AddToCart event isnt being fired correctly for this store https://rainforestbaskets.com/product/smiling-tiger/

### Steps to reproduce:

1. Goto https://rainforestbaskets.com/product/smiling-tiger/
2. Add the item to cart

### Expected behavior:
Add to cart should include correct values

### Actual behavior:
The values should be real values with right data

### Additional details:
![Screen Shot 2022-03-21 at 4 09 12 PM](https://user-images.githubusercontent.com/1510328/159377722-a1316a41-134e-4646-a65c-d5460b9b708e.png)
![Screen Shot 2022-03-21 at 4 01 43 PM](https://user-images.githubusercontent.com/1510328/159377726-7352a7df-c53c-49e5-b4ac-1923233d11e3.png)

**Comment by findingsimple** [comment]
Investigating this a little.

Seems to be when simply viewing the cart page (AFTER adding a product to cart at some point previously) there is an extra Add to cart event being triggered when I haven't actually added anything extra to the cart - again I just viewed the cart page. I tested on a different site (https://navahair.us) and it doesn't have the same problem

When adding a product to the cart it redirects to the cart page so what is happening is the same extra event and incorrect values are present.

Viewing the checkout page also gives an addtocart error (also not reproducable on https://navahair.us ) which seems odd.

https://rainforestbaskets.com/product/smiling-tiger/ is using a "new checkout" so its possible some extra events are being triggered at unexpected points resulting values not being available

---

One other thing to note is the product i limited to 1 per order

**Comment by findingsimple** [comment]
I'm not sure this site is even using our integration.

I can't find the plugin files e.g. https://rainforestbaskets.com/wp2020/wp-content/plugins/pinterest-for-woocommerce/README.txt 404's but woocommerce is visible https://rainforestbaskets.com/wp2020/wp-content/plugins/woocommerce/readme.txt

And there are none of the plugin pinterest rest API routes 

But it is still somehow firing pinterest events.

I also noticed the site is using the litespeed caching plugin. I installed it on my test site and settings like minify and combine JS didn't give me any issues (I thought they might be the cause)

@adarshakb I think this can be closed.

**Comment by findingsimple** [comment]
Site is using Google Tag Manager and I can't see any of our API routes. I suspect they are no longer using our extension and issue and pinterest events are possible being fired by GTM.

Related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/417
