### ISSUE TITLE
Checkout event was wrongly trigged (with wrong values) before I actually checked out

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#406]
### Describe the bug:
I just added to cart an item and checkout event was triggered

### Steps to reproduce:

1. Goto this website's product item page https://organicalbotanicals.com/product/lotus-seeds-nelumbo-nucifera/?v=7516fd43adaa
2. click add to cart

### Expected behavior:
No checkout event to be triggered before making the purchanse

### Actual behavior:
checkout event was triggered with wrong value in text

### Additional details:
![Screen Shot 2022-03-21 at 4 16 12 PM](https://user-images.githubusercontent.com/1510328/159378485-5384a111-a269-4a28-b0ae-a627e73cb3a3.png)

**Comment by adarshakb** [comment]
also notice if you see above screenshot you can see "value" has "Order_Total" string which isnt right value

**Comment by findingsimple** [comment]
Looks to me like a whole lot of things are broken on this site - which is having flow-on effects
* Multiple page view events when viewing shop page 
* Add to cart event fired when viewing shop page
* Checkout event fired on viewing shop page (I haven't even added a product to cart)

<img width="932" alt="Screen Shot 2022-03-23 at 9 38 59 pm" src="https://user-images.githubusercontent.com/355014/159686513-5d12f168-291f-4e4c-9509-074f57fecc12.png">

Probably some stray loops or something happening in the theme when building each page.

Not sure we should be using this site as an example of bugs - but perhaps the extension needs to be more protective/defensive to more gracefully handle sites of this nature.

**Comment by findingsimple** [comment]
Dug in some more

---

There are 2 pinit.js scripts being loaded - indicating there is more than one pinterest related extension being loaded (I can't can't figure out which extension

 I can see both of the following

```
<script async defer src="//assets.pinterest.com/js/pinit.js"></script>
<script src="https://assets.pinterest.com/js/pinit.js?siteground-async=1&#038;ver=1.0.8" defer="defer"></script>
```

---

The second is ours - The site does some sort of weird async loading which appears to be related to their hosting (siteground?)

---

Uses Themify Ultra theme with a side/slide cart.

---

I can't find where the checkout event is being fired in the source on the checkout page

**Comment by adarshakb** [comment]
Another example can you check https://useparadigma.com.br/
<img width="3035" alt="Screen Shot 2022-03-24 at 6 16 49 PM" src="https://user-images.githubusercontent.com/1510328/160035986-f8162274-f656-4c0f-aa13-7923d7851c95.png">

As soon as I visit all events get triggered.

**Comment by findingsimple** [comment]
@adarshakb 

* I can't see our pinit.js script being loaded in the source
* I can only see 1 of our page visit events in the source
* They do use google tag manager

**Comment by findingsimple** [comment]
From what I can tell more sites with extra tagging - so I think it will be related to whatever solution we choose to implement for https://github.com/woocommerce/pinterest-for-woocommerce/issues/417
