### ISSUE TITLE
Unparsable currency value in checkout event

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#407]
### Describe the bug:
This bug might be related in some way to this https://github.com/woocommerce/pinterest-for-woocommerce/issues/406

### Steps to reproduce:
1. Add this item to your cart https://patyrommanel.com/produto/anel-solitario-coracao-folheado-a-ouro-com-zirconias-e-cristal/
2. Goto checkout

### Expected behavior:
Firstly as described  in  #406 this event shouldnt event be shown

But secondly the value in this has unparsable value
### Actual behavior:

1. dont trigger checkout
2. always send parsabled values in the right keys (in this case should be currency)

### Additional details:
![Screen Shot 2022-03-21 at 4 32 11 PM](https://user-images.githubusercontent.com/1510328/159380868-a6f93f46-5371-4638-aff5-2269b2dbacfa.png)

![image](https://user-images.githubusercontent.com/1510328/159379886-023b504e-2b39-4d94-ac48-c3323c543b61.png)

**Comment by findingsimple** [comment]
Looks like the site in question is using Elementor and Cartflows

**Comment by findingsimple** [comment]
Another site with 2 pinterest tags, indicating another plugin

```
<!-- Pinterest Tag -->
<script>
!function(e){if(!window.pintrk){window.pintrk = function () {
window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var
  n=window.pintrk;n.queue=[],n.version="3.0";var
  t=document.createElement("script");t.async=!0,t.src=e;var
  r=document.getElementsByTagName("script")[0];
  r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
pintrk('load', '2613660662144', {em: '<user_email_address>'});
pintrk('page');
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt=""
  src="https://ct.pinterest.com/v3/?event=init&tid=2613660662144&pd[em]=<hashed_email_address>&noscript=1" />
</noscript>
<!-- end Pinterest Tag -->
```

and

```
<script type="[text/javascript]()">
  !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var n=window.pintrk;n.queue=[],n.version="3.0";var t=document.createElement("script");t.async=!0,t.src=e;var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");

  pintrk('load', '2613660662144');
  pintrk('page');
</script>
```

I can't find where the checkout event is being fired in the source on the checkout page

**Comment by adarshakb** [comment]
How about this site @jconroy ?

https://store.cloverleafdistribution.com/product/goldwhip-580g-tank/
<img width="3066" alt="Screen Shot 2022-03-24 at 6 02 29 PM" src="https://user-images.githubusercontent.com/1510328/160034551-954fcb42-2f1a-48a6-860e-3236530949b0.png">

**Comment by findingsimple** [comment]
@adarshakb that's a different event - add to cart. 

The theme looks to be using its own ajax style add to cart functionality that is likely interfering

**Comment by findingsimple** [comment]
First site is related to having duplicated tagging implementation and therefore related  to https://github.com/woocommerce/pinterest-for-woocommerce/issues/417

Second site is a different event and looks like they have GTM installed and aren't using our extension (anymore?)

Closing this issue
