### ISSUE TITLE
Investigate why the following websites have zero conversion value in checkout process

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#411]
- https://www.socialpreset.com/prodotto/preset-gratuito/
  - (stripe + bitcoin - normal checkout) - 1.0.8
  - rocketlazyloadscript
- https://jgfoster.com/shop/
  - (woo payments - normal checkout - 1.0.7
- https://theplrhustler.com/shop/
  - ( woo payments - fusion / avada 2 step checkout) - 1.0.8
- https://www.crochetcafe.pl/
  - (couldn't get checkout payment method) - 1.0.7
- https://stitchingmesoftly.co.uk/wholesale/
  - (square cc or clear pay - regular checkout) - 1.0.7
  - can't see pinit.js - but can see our pintrk

**Comment by adarshakb** [comment]
Please check all the websites linked individually. Some of them may no longer exhibit the behaviour if there is a change in their setup as data is couple of day old

**Comment by findingsimple** [comment]
Thanks @adarshakb 

Making a note - discussed on call that its possible fixing other tagging/event issues may resolve this - but its been difficult to replicate by the pinterest team.

**Comment by findingsimple** [comment]
> zero conversation value

Realized today talking with @adarshakb that Woo support free / $0 products as well coupons that could make cart total $0

Some of the sites above do have $0 products

**Comment by findingsimple** [comment]
Screenshot of a free order and the Pinterest tag manager error

<img width="1303" alt="Screen Shot 2022-03-25 at 2 41 54 pm" src="https://user-images.githubusercontent.com/355014/160052826-20cdf57c-80f9-412f-a73e-ad83d5292f0a.png">

cc @adarshakb

**Comment by findingsimple** [comment]
On hold - discussing with Pinterest team the best course of action here

**Comment by adarshakb** [comment]
@jconroy - The previous discussion here was as long as its a real $0 order it is fine, but not for other ways. Lets update this bug based on that assumption

**Comment by ecgan** [comment]
This issue was investigated by @ibndawood, and discussed with @jconroy in pb0Spc-3i8-p2. It seems like this is a non-issue. Closing this.
