### ISSUE TITLE
Deprecated warning for API permissions

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/pinterest-for-woocommerce#416]
### Describe the bug:
I'm getting a lot of the following deprecation warnings in my log file. It shows up whenever a WC REST API request is sent (also any request sent from WC).

```
PHP Deprecated:  woocommerce_rest_api_option_permissions is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in wp-includes/functions.php on line 5701
```

It seems to be coming from the code added in this [commit](https://github.com/woocommerce/pinterest-for-woocommerce/commit/f2a4cec9d02b91fb1c3805cc1c625c95e97395ea) and mentions it's been deprecated since WooCommerce Admin version 3.1 (included since WooCommerce 6.2).

There doesn't seem to be an alternative filter available. But in other extensions we've created a separate route/class to handle options/settings instead of trying to extend the WC Admin endpoint. Which could be something like `wp-json/pinterest/v1/settings`, that way you can have full control over who is allowed to access that endpoint.

### Steps to reproduce:
1. Enable debug logging with WP_DEBUG_LOG
2. View the page Marketing > Pinterest or any WC Admin page in the dashboard
3. See multiple deprecated warnings show up in the log

**Comment by findingsimple** [comment]
Thanks @mikkamp

**Comment by alexiglesias31** [comment]
@mikkamp
The plugin options are passed to the frontend using `AssetDataRegistry` of the package `woocommerce-blocks`, afaik this already checks the user capabilities to `manage_woocommerce`.
In that case, imho, we don't need [this](https://github.com/woocommerce/pinterest-for-woocommerce/commit/f2a4cec9d02b91fb1c3805cc1c625c95e97395ea#diff-42350bdf24f87fb7f188b4ab2c01c26d7aadd3d1d4f0fde4c6bbd1bbd956d2a4R200) anymore. Not sure if it worth to implement the new endpoint.

**Comment by mikkamp** [comment]
I haven't really looked into the changes there in detail, but when I disable that filter, I get a 403 error for the endpoint:
`/wp-json/wc-admin/options?options=pinterest_for_woocommerce&_locale=user`

This only happens when I login with a user with the role `Shop Manager`, for a regular `Administrator` the endpoint works.

If we have another way around that I'd say that should be fine, but for the long term it's probably worthwhile switching to another endpoint.
