### ISSUE TITLE
Detect if there are other tags installed on website

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#417]
## User story
Customers might already have other tag integrations installed before installing our plugin

We see at the creation of this ticket around atleast 8% of installed users have multiple tag plugins installed.

We need to detect these tags and warn the users to uninstall/remove pinterest tag so duplicate events arent sent

1. google tag manager
2. pixelyoursite
3. premmerce

Detecting the above 3 tags would help us in reducing a majority of cases

**Comment by findingsimple** [comment]
@shivanarrthine can we chat about design implications for this one?

**Comment by shivanarrthine** [comment]
@jconroy sure. From the looks of it, we likely need a warning during the onboarding flow (when they set up tracking) and the Catalog page (if an existing user sets up a conflicting extension/tag). 

Do we want to prevent them from completing the setup if there's a conflict? Or should we just leave it as a warning that some things may not work properly? I'm thinking if it's just a warning, they can complete the setup first and then fix the conflict later. But I'm not too sure if it may cause other issues.

**Comment by findingsimple** [comment]
> (if an existing user sets up a conflicting extension/tag)

We can't actually say with 100% certainty there will be a conflict - so I don't think we should block it - I think we should ask them to review/deactivate those extensions to avoid potential conflicts. Maybe display a link to the admin plugin page. Or Give them the options to disable our tracking (if they want to rely on a different/custom implementation)

Problems are mainly around the events that are fired
* https://github.com/woocommerce/pinterest-for-woocommerce/issues/407
* https://github.com/woocommerce/pinterest-for-woocommerce/issues/398

@adarshakb thoughts?

**Comment by adarshakb** [comment]
Yeah a warning is good with me @jconroy

**Comment by shivanarrthine** [comment]
## Designs
I've added warnings to the UI to warn users during and after the onboarding flow if they have a duplicate/conflicting tag.

### During onboarding

![Warnings_Onboarding](https://user-images.githubusercontent.com/1027482/174908089-c0c7fe01-2b83-495e-8fa0-48ca7f555554.png)
Added a warning during Step 3 of onboarding where users set up tracking with the Pinterest tag. Clicking on Review plugins would lead users to the wp-admin plugins page. 
Users are still allowed to continue with the setup flow as they can always review the plugins after setup and we might not be 100% certain that there would be a conflict.

### After onboarding
If the user proceeds with the setup without fixing/reviewing the conflict or if they installed another plugin that’s causing conflicts after onboarding, a warning would be shown on the Catalog tab.

![Warnings_Catalog_new](https://user-images.githubusercontent.com/1027482/174908124-b76d9ead-ef14-4aa8-9fbe-f03fa5cfd01d.png)
Added the warning to the catalog screen as an additional status. Unlike the other statuses, this would only appear if there is a conflict detected. 

Review plugins would lead users to the wp-admin plugins page. Manage settings would lead users to the Settings tab where they can choose to disable tracking within our extension if they want to rely on a different/custom implementation.

#### Alternate version
![Warnings_Catalog](https://user-images.githubusercontent.com/1027482/174960063-8ecdcc62-de5d-4c44-800c-86ab81fae168.png)
I made an alternate version without the option for users to disable tracking (manage settings) in our plugin. I am a little unsure if we should make the option that prominent as it reduces the value of our extension. It feels easier to just turn the tracking off then find and fix other extensions. Do let me know if there's a preference here.


_Full designs in Figma file (page: Warnings for duplicate tags)_

**Comment by alexiglesias31** [comment]
@adarshakb,
The Premmerce Pinterest plugin was closed.
https://wordpress.org/plugins/premmerce-woocommerce-pinterest/
https://premmerce.com/woocommerce-pinterest/

Were you referring to the standard Premmerce plugin or to another extension?

**Comment by alexiglesias31** [comment]
@shivanarrthine

This is the ongoing progress on the task.
![pinterest-warning](https://user-images.githubusercontent.com/40774170/175068322-d86ad747-eb89-48a7-b842-30afd03960a4.png)

Just wanna confirm that we don't need to inform to user which are the plugins that can potentially cause issues.

cc @jconroy

**Comment by findingsimple** [comment]
@alexiglesias31  I haven't aligned with @shivanarrthine internally yet on the designs so there may still be some changes needed e.g. we can't actually tell for certain that multiple tags have been detected - just that they the may potentially have a plugin that is conflicting - so saying "multiple tags detected" may be incorrect.

**Comment by adarshakb** [comment]
@alexiglesias31 yep! We can ignore that plugin and recognize the other 2 if its not in use anymore, but we see data that people use it still. My be they are using older versions. Not sure.

**Comment by alexiglesias31** [comment]
@jconroy 

> I haven't aligned with @shivanarrthine internally yet on the designs so there may still be some changes needed e.g. we can't actually tell for certain that multiple tags have been detected - just that they the may potentially have a plugin that is conflicting - so saying "multiple tags detected" may be incorrect.

Perfect. Please ping me if there is any update.

@adarshakb 

> We can ignore that plugin and recognize the other 2 if its not in use anymore, but we see data that people use it still. My be they are using older versions. Not sure.

Probably they are referring to [this extension](https://woocommerce.com/products/softblues-pinterest-for-woocommerce/), seems there was a change in the brand name. In that case, we would need a copy of the extension to be able to detect it.

**Comment by findingsimple** [comment]
> Probably they are referring to [this extension](https://woocommerce.com/products/softblues-pinterest-for-woocommerce/),

Interesting, I was aware. That does look to be it

**Comment by findingsimple** [comment]
@alexiglesias31 we have some updated designs - [in the project figma](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3239%3A41991). 

![new_catalog-1](https://user-images.githubusercontent.com/355014/177151925-27d554e7-79f9-4d29-8a6a-23c2b39faee2.png)

![new_onboarding-2](https://user-images.githubusercontent.com/355014/177151943-69bb2c44-8de3-4470-a5f0-1d143c366af1.png)

**Comment by findingsimple** [comment]
Depending on how big the dev gets on this feature please consider creating a feature branch and splitting up work into smaller PRS for review

**Comment by dieherbar** [comment]
hi @jconroy hope you're doing fine.
I've got 2 comments about this task.
1- To properly verify this fix we need you to provide us a valid plugin licence for pixelyoursite - pinterest addon
2- Premmerce plugin will be part of a future PR

If you have any comments please let us know, thank you!
