### ISSUE TITLE
Harmonize `Google Product Category` meta key with the official `Facebook for WooCommerce` plugin

### ISSUE THREAD

**Issue by strarsis** [woocommerce/pinterest-for-woocommerce#419]
## User story
The official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) plugin adds a Google Product Category selection to WooCommerce Product Categories and Products. Product Categories also inherit the Google Product Category from their higher Product Categories, which is very handy.

This official `Pinterest for WooCommerce` plugin uses a different meta key for the Google Product Category than the official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) plugin does:
https://github.com/woocommerce/facebook-for-woocommerce/blob/master/includes/Products.php#L51
https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Product/Attributes/GoogleCategory.php#L27
Also the Google Product Category can be assigned to WooCommerce Categories and can be inherited down, which is very useful for a larger collection of nested categories.

### Is your feature request related to a problem? 
The requirement to set the Google Product Category multiple times and in different ways due to a often used attribute that isn't standardized (Google Product Category).

#### How to reproduce the problem
- On a stock WooCommerce setup, ensure that both plugins, this official `Pinterest for WooCommerce` and the official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) are installed.
- Using the added (UI) fields from the official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) plugin, assign Google Product Categories to the WooCommerce Product Categories.
- Set up and initiate sync of both plugins.
Note that this official `Pinterest for WooCommerce` plugin warns about the missing Google Product Category field for all products.

### Describe the solution you'd like 
- Use the same Google Product Category meta key between both plugins, ideally, due to their importance and popularity, setting a precedence for a semi-official attribute key for the Google Product Category for other plugins in the process. Also the inheritance of the Google Product Category should be supported, as it can become very cumbersome to set it for each individual category.
- Also checking for other potential attribute keys (as the one used by the other, official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) plugin) and falling back to them.

### Describe alternatives you've considered 
- Redundantly setting the Google Product Category again to a new field using some plugin or other way.
- Using a product attribute filter, but this may not work or stop working, depending on how low-level the plugins access the product attribute data.

## Technical
When both plugins use the same attribute key, the old attribute key used by previous plugin versions has to be either migrated or fallen back to, to ensure backward compatibility.

## Acceptance criteria
- Proper migration/backward compatibility with the Google Product Category attribute key.
- Equal/compatible Google Product Category attribute values (this should be the case as IDs are used that are provided [by Google as a single source of truth](https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt)).

## Unknowns
- Does the other plugin `Pinterest for WooCommerce` plugin use an attribute key/value/inheritance logic/data structure that can be easily supported in this plugin?
- Is migration to new Google Product Category attribute key hard to achieve?

## Out of bounds/rabbit holes
When multiple plugins support the Google Product Category attribute, which plugin should be responsible for displaying the UI for setting the Google Product Category? Currently the official [`Facebook for WooCommerce`](https://github.com/woocommerce/facebook-for-woocommerce) plugin adds an UI. Should this be moved into a separate plugin? Or even into the WooCommerce core?

**Comment by findingsimple** [comment]
Thanks @strarsis for the detailed enhancement description.

Could you please head over to https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=412041 and add the idea there and link back to this issue so we can track popularity

For what its worth I agree all "feed" extensions should be able to use the same attributes instead of re-inventing the wheel every time. It's something we are looking into.

**Comment by strarsis** [comment]
@jconroy: Created a new idea: https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/44970310-use-same-google-product-category-data-as-the-offic
