### ISSUE TITLE
Pull supported countries for Ads list from API instead of hardcoded value

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#426]
Original implementation https://github.com/woocommerce/pinterest-for-woocommerce/issues/251

Advertiser enabled countries can be pulled from the following endpoint

https://developers.pinterest.com/docs/redoc/adtech_ads_v4/#operation/get_advertiser_countries_handler

/ads/v4/advertisers/countries

 “supported country” refers to the “selling location”. Currently the extension is based on “store location” based on WP Admin > WooCommerce > Settings > General location information.

If Multi feed support is added - this will be based on the WooCommerce “selling location” setting so would need to support checking against multiple locations once multi feed is added.

**Comment by findingsimple** [comment]
Complete prior to 06/27

**Comment by alexiglesias31** [comment]
Hi @adarshakb.

I was making some tests with the endpoint and I'm getting this error all the time. Do you know what can be the cause:
`{"status":"failure","code":3,"data":null,"message":"Authorization failed.","endpoint_name":"get_advertiser_countries_handler","error":{"message":"None"}}`

This is the endpoint that i'm hitting: `https://api.pinterest.com/ads/v4/advertisers/countries`

cc @jconroy

**Comment by alexiglesias31** [comment]
As mentioned @adarshakb in Slack:

> Looks like we need to add your client type to the authorization. I have an internal ticket for this issue. It might take sometime to add it.

We are adding manually Argentina, Colombia and Chile in the meantime.

cc @jconroy

**Comment by findingsimple** [comment]
Perfect thanks @alexiglesias31

**Comment by findingsimple** [comment]
Set to on-hold while we [wait for changes on the Pinterest side](https://github.com/woocommerce/pinterest-for-woocommerce/issues/426#issuecomment-1161885670)

**Comment by ivanrios** [comment]
@alexiglesias31  Just to confirm, the endpoint currently allows partners to obtain the list of countries.

![Screen Shot 2022-09-12 at 10 52 29](https://user-images.githubusercontent.com/1007705/189700153-4401022e-15a1-4c3a-bed4-b754a786b9f4.png)

**Comment by alexiglesias31** [comment]
@jconroy, can we remove the on-hold for this task?

**Comment by alexiglesias31** [comment]
@ivanrios I tested again and got the same error:

`{"status":"failure","code":3,"data":null,"message":"Authorization failed.","endpoint_name":"get_advertiser_countries_handler","error":{"message":"None"}}`
