### ISSUE TITLE
Enhanced match value isn't synced with pinterest

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#430]
### Describe the bug:

This is a continuation of https://github.com/woocommerce/pinterest-for-woocommerce/issues/429 so please refer there for more details

In settings page if enhanced match is disabled and customer enables it, then we need to update the enhanced match value via API PATCH call

API - https://developers.pinterest.com/docs/redoc/adtech_ads_v4/#operation/create_conversion_tag_handler

### Steps to reproduce:

1. Have a pinterest account connect with woo commerce plugin
2. Goto pinterest Ads -> conversion and disable enhanced match
3. In plugin disable enhanced match
4. Now re-enable enchanged match in the plugin.

### Expected behavior:
 It should be enabled automatically in Pinterest when user enables it in the woocommerce site.

### Actual behavior:
No change on pinterest side

### Additional details:

NOTE: Lets hold off on the otherway round of update. i.e when we disable enhanced match on the plugin DONOT disable the enhanced match at pinterest side (only stop sending EM signals from plugin) because the user might have the same tag installed in other places

**Comment by alexiglesias31** [comment]
@adarshakb

> NOTE: Lets hold off on the otherway round of update. i.e when we disable enhanced match on the plugin DONOT disable the enhanced match at pinterest side (only stop sending EM signals from plugin) because the user might have the same tag installed in other places

To clarify here, are we only syncing the setting on Pinterest side when the user enables the setting? Something like:
- Setting disabled -> setting enabled -> sync with Pinterest
- Setting enabled -> setting disabled -> don't sync with Pinterest, only stop sending the EM signals

**Comment by adarshakb** [comment]
thats correct for now!. 

the disabled option still need to be discussed

**Comment by adarshakb** [comment]
@alexiglesias31 - We just had an internal sync and it looks like its better to do a complete sync

i.e 

Setting enabled -> setting disabled -> sync with Pinterest and stop sending the EM signals

Is it possible to make the change in this ticket or should I create a new one.?


Also can you please update the help text modal to inform the user of these behaviour

**Comment by alexiglesias31** [comment]
@adarshakb.
Yes, it is possible. There is an ongoing PR related to that, we will add the changes there.
