### ISSUE TITLE
Changes on enhanced match value on Pinterest aren't synced with the plugin

### ISSUE THREAD

**Issue by alexiglesias31** [woocommerce/pinterest-for-woocommerce#440]
### Describe the bug:
In edge cases where the user disables/enables the enhanced match (EM) setting in Pinterest UI, when they come to the plugin's settings page the change is not synched.

### Steps to reproduce:
1. Install the plugin and do the onboarding.
2. Go to Pinterest UI -> Ads -> Conversions -> Change the tag's enhanced match setting.
3. Go to the plugin's settings page: The change is not synched with the plugin.

### Expected behavior:
We should find a way to sync the change on Pinterest side with the plugin.

### Actual behavior:
The change on Pinterest side is not synched with the plugin.

**Comment by adarshakb** [comment]
The goal is to show the correct information to user when they open the settings page.

How about we sync in the following scenarios

1. Every 24 hours in feed generation stage
2. Every-time the user opens the settings page this row could be greyed out while we async fetch the value.

I dont anticipate the user to open the settings page much after initial setup phase.

**Comment by alexiglesias31** [comment]
@adarshakb, sounds good to me.

**Comment by findingsimple** [comment]
@jill @shivanarrthine do you have any thoughts on how we should approach this?

> The goal is to show the correct information to user when they open the settings page.

Currently the settings page can get out of sync with changes made in Pinterest Frontend

**Comment by shivanarrthine** [comment]
> Every time the user opens the settings page this row could be greyed out while we async fetch the value.

@jconroy  Doing this makes sense to me and I'm assuming it shouldn't take too long to load the new settings after the page loads. We can probably also add a small indication somewhere on the page/card saying we are fetching the latest settings.

**Comment by findingsimple** [comment]
> We can probably also add a small indication somewhere on the page/card saying we are fetching the latest settings.

Great. Did you want to add this to your pile to explore sometime?

**Comment by shivanarrthine** [comment]
@jconroy I explored adding a top status bar on the Settings page that shows when it's last updated. The settings get automatically synced on page load (form disabled until it's done) and users can also manually sync if needed.

**Designs:**
![Pinterest_fetch latest settings](https://user-images.githubusercontent.com/1027482/172994077-45c993d5-9e20-410b-b0f5-854262322de8.png)

Full designs in Figma (page: Fetch latest settings)

**Comment by adarshakb** [comment]
My only comment is that this is yet another button the user should click. Does this page has heavy traffic? If not we could add it as a call before loading the page/setting?

**Comment by shivanarrthine** [comment]
@adarshakb The settings would update automatically on page load without them having to click on the button. I added the button there in case there's an error or if the user wants to manually sync without having to reload the page.

**Comment by adarshakb** [comment]
Thank you for the clarification @shivanarrthine . Had mistaken your comment. I am ok then :)

**Comment by findingsimple** [comment]
Depending on how big the dev gets on this feature please consider creating a feature branch and splitting up work into smaller PRS for review

**Comment by alexiglesias31** [comment]
Hey @jconroy, just a small question here.

Since we will sync only the `Enhanced match support` setting. Would it be worth to include the sync button in the Tracking section?

![image](https://user-images.githubusercontent.com/40774170/180289418-286ad484-7623-45ad-9b63-042b06e142da.png)

**Comment by findingsimple** [comment]
@shivanarrthine do you have any thoughts on @alexiglesias31 's question?

**Comment by shivanarrthine** [comment]
@jconroy @alexiglesias31 I think it might be worth keeping at the top since it happens on page load and it could scale better if we decide to fetch settings for other options in the future. 

But maybe instead of disabling all the fields while waiting for it to fetch & load the latest setting, we could just disable the Enhanced match one?
