### ISSUE TITLE
Investigate No relevant meta tag was found exception

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#446]
Partner connect failed with exception "No relevant meta tag was found when creating merchant"

Over the last week a majority of errors came from
Domain ['https://scarfbank.com/gallery'] verification failed for user scarfbank
Domain ['https://www.bathroombutler.com/us'] verification failed for user bathroombutler

Below domains also had errors but number of errors were lower
Domain ['https://bathroombutdev.wpengine.com/us'] verification failed for user bathroombutler
Domain ['https://jorgephyttasraposo.com'] verification failed for user jaffrayhunter3426

**Comment by adarshakb** [comment]
Also investigate why this endpoint is called repeatedly when there is this error. This endpoint was called 1.3k times in 2 weeks
<img width="747" alt="Screen Shot 2022-04-18 at 6 04 20 PM" src="https://user-images.githubusercontent.com/1510328/163899948-052e5258-d5ab-44df-971c-ca961742a927.png">

**Comment by JPry** [comment]
> Partner connect failed with exception "No relevant meta tag was found when creating merchant"

I did some digging into the codebase, and I don't see this message (or even one close to it) anywhere. My assumption is that this specific message is actually returned from the Pinterest API. Is there more information about what triggers that error to be returned from the API? Do we know exactly which endpoint is being hit here? It looks like the domain verification, but I want to be sure.

Assuming it *is* domain verification, there is no payload data being sent with the request, so I'm not sure how our calls can do anything differently. But understanding which endpoint is being hit can help us track down where the issue is originating. 

> Also investigate why this endpoint is called repeatedly when there is this error. This endpoint was called 1.3k times in 2 weeks

Assuming it is indeed domain verification, the endpoint will be retried in short succession in the case of a failure. This might explain why there is a higher call rate for that endpoint.

**Comment by alexiglesias31** [comment]
@jconroy @JPry

- I think this is the endpoint that returns that response: `catalogs/partner/connect/`
- The endpoint is used to create a merchant or update an existing one, including the update call to register the feed.
- In fact, the endpoint is called repeatedly on errors, especially for new users without an associated merchant, as it will try to create a merchant on each `health_check()` call.
- In addition to the back-off functionality that we're investigating, there's probably a more efficient way of doing this using a different endpoint or flow.


> Partner connect failed with exception "No relevant meta tag was found when creating merchant"

The message comes from the Pinterest API in the error message field. We couldn't find anything related in the documentation about that message.

cc @adarshakb

**Comment by alexiglesias31** [comment]
The back-off functionality could be approached as follows:
- If the `update_or_create_merchant()` call is successful, proceed as expected.
- Cache the error responses using an exponential expiry time.

**Comment by findingsimple** [comment]
Thanks for the extra info @alexiglesias31 I'll discuss with @JPry

**Comment by findingsimple** [comment]
@JPry where are you at with this one? 

([Just capturing another recent "no tag" issue](https://github.com/woocommerce/pinterest-for-woocommerce/issues/477) as possibly related)

**Comment by adarshakb** [comment]
Adding info from Slack thread by @niketpins 

a) some websites are behind login e.g. [the-falcon.net/ladiva_staging](http://the-falcon.net/ladiva_staging) because of which we may not be able to verify from metatag or filename
b) Rest of the domains which are failing, both metatag and html file are missing for those. My guess is init_plugin is invoked before verification_data is set https://saucal.slack.com/archives/C01D4U4JS3C/p1656656456455469?thread_ts=1655826809.021029&cid=C01D4U4JS3C

Is there anyway to reach out to 1-2 merchants to find debug logs and more info. We can join the session as well if it helps.

**Comment by JPry** [comment]
@adarshakb 

> Rest of the domains which are failing, both metatag and html file are missing for those. My guess is init_plugin is invoked before verification_data is set [saucal.slack.com/archives/C01D4U4JS3C/p1656656456455469?thread_ts=1655826809.021029&cid=C01D4U4JS3C](https://saucal.slack.com/archives/C01D4U4JS3C/p1656656456455469?thread_ts=1655826809.021029&cid=C01D4U4JS3C)

Can you provide more details from that conversation? I don't have access to that Slack instance.

**Comment by adarshakb** [comment]
Currently domain verification code is injected on init_pluginhttps://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/class-pinterest-for-woocommerce.php#L246 and maybe_inject_verification_code method requires verification_data to inject otherwise skips.
When does init_plugin  invoked?
Is there a possibility that init_plugin  is invoked and verification_data is not set and hence code is not injected (assuming init happens only once)?

**Comment by adarshakb** [comment]
Separate question do we remove injected code after domain verification is complete or it stays there

**Comment by alexiglesias31** [comment]
`init_plugin` is hooked on `plugins_loaded` and the verification data stays there after domain verification is complete.
