### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to undefined method Exception::get_pinterest_code()

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#453]
### Describe the bug:
from this review: https://wordpress.org/support/topic/many-error-records/ and here: https://wordpress.org/support/topic/pinterest-version-1-0-11

### Expected behavior:
No fatal errors

### Actual behavior:
[Mon Apr 25 22:58:39.392xxx 2022] [php7:error] [pid 3117] [client 172.70.xx.xxx:10956] PHP Fatal error: Uncaught Error: Call to undefined method Exception::get_pinterest_code() in xxxxxpinterest-for-xxxxxxxxxxxxxxx

**Comment by ChristianAF** [comment]
Also this WooCommerce request: WooCommerce.com Request Number 253528

**Comment by alexiglesias31** [comment]
Closing this issue, since it was solved on this PR https://github.com/woocommerce/pinterest-for-woocommerce/pull/451
