### ISSUE TITLE
Include free_shipping_label in XML

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#457]
## User story
Include the free shipping label on the XML. It was required by some Merchants.

### Is your feature request related to a problem? 
When Merchant has free shipping is not present on the XML

### Describe the solution you'd like 
Include Free shipping label on XML
![image](https://user-images.githubusercontent.com/43881685/167126331-d1ee3c8b-9a58-48ee-a083-e8a16dd3685d.png)
[Related documentation](https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs)

**Comment by ChristianAF** [comment]
https://wordpress.org/support/topic/free_shipping_label-not-in-xml/

**Comment by findingsimple** [comment]
@JPry I am going to label this one as needs investigation - I think we'll need to confirm how @budzanowski set up handling for this already (and tests etc.) before diving in. I feel like he would have considered "free_shipping_label"

**Comment by budzanowski** [comment]
@jconroy , @JPry 

Yes, the free shipping is included in the XML:

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/src/Shipping.php#L15-L31

The UT cases cover the scenarios quite extensively:

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/tests/Unit/FeedXMLGenerationShippingTest.php#L62

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/tests/Unit/FeedXMLGenerationShippingTest.php#L110

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/tests/Unit/FeedXMLGenerationShippingTest.php#L240

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/tests/Unit/FeedXMLGenerationShippingTest.php#L264

https://github.com/woocommerce/pinterest-for-woocommerce/blob/e0dbf45385b6091f5728cbeb34e0c9e1535497da/tests/Unit/FeedXMLGenerationShippingTest.php#L463

We need to understand which scenario does not work ( outside UT ), or if it is a missing scenario, or ( probably ) a wrong configuration in the merchant settings.

**Comment by findingsimple** [comment]
Thanks @budzanowski 🙇 

> We need to understand which scenario does not work ( outside UT ), or if it is a missing scenario, or ( probably ) a wrong configuration in the merchant settings.

@ChristianAF can you see if you can fill some of those gaps for us with the merchant please?

**Comment by findingsimple** [comment]
@alexiglesias31 @ChristianAF it was mentioned in slack this may be closed - could you please confirm then close when you get a moment?

**Comment by ChristianAF** [comment]
Yes, this could be close. The merchant didn't write back to us again.
