### ISSUE TITLE
Add plugin version to API headers when communicating with Pinterest

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#460]
## Is your feature request related to a problem? 
Currently, it is difficult for the Pinterest team to
* identify what version of the extension is (potentially) causing issues with their APIs
* track % of users using deprecated APIs broken down by plugin version etc.

## Describe the solution you'd like 
* We've discussed with the Pinterest team adding the plugin version as a header when making requests to the Pinterest API.

## Unknowns
* We have not confirmed parameter/header name - open to hearing input as part of solution

**Comment by alexiglesias31** [comment]
@jconroy is there any specification for the header that will include the Pinterest version?

**Comment by findingsimple** [comment]
Hi @alexiglesias31 

> open to hearing input as part of solution

^ This

@adarshakb would your eng have any requirements for the property?

**Comment by alexiglesias31** [comment]
@jconroy @adarshakb
I'd go with something similar to 'Pinterest-Woocommerce-Version'
