### ISSUE TITLE
Add Japan to list of available countries in WooCommerce

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#461]
Add Japan as a country where the app is available. Please make it available on 5/23 PST. It need not be exact but approximately thats the date we will need to launch it by releasing a plugin.

**Comment by findingsimple** [comment]
>  It need not be exact but approximately thats the date we will need to launch it by releasing a plugin.

Just confirming @adarshakb it will only be available to those who install new or update after we do the release

**Comment by adarshakb** [comment]
> Just confirming @adarshakb it will only be available to those who install new or update after we do the release

yep!
