### ISSUE TITLE
orphaned variation breaks XML feed

### ISSUE THREAD

**Issue by rrennick** [woocommerce/pinterest-for-woocommerce#462]
### Describe the bug:

In https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/ProductsXmlFeed.php#L172:L173, `wc_get_product()` returns `false` when a product/product_variation's parent does not exist. This logs a warning in the Pinterest -> Catalog screen:

```
XML feed:	 Could not get feed info.   •   Last activity: 11 mins ago - Automattic\WooCommerce\Pinterest\Product\Attributes\AttributeManager::get_all_values(): Argument #1 ($product) must be of type WC_Product, bool given, called in [/var/www/example.com/wp-content/plugins/pinterest-for-woocommerce/src/ProductsXmlFeed.php](http://example.com/wp-content/plugins/pinterest-for-woocommerce/src/ProductsXmlFeed.php) on line 166
```

### Steps to reproduce:

1.  Edit a test product in the database and give it a post_parent value that is greater than 0 and is not the ID of a product.
2.  Go to the Pinterest -> Catalog screen
3. 

Tested with the latest version of WC and this plugin.

**Comment by findingsimple** [comment]
Thanks @rrennick 👍
