### ISSUE TITLE
Change strings and Add the POT files into the build for i18n

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#470]
1. Remove html encoding in the strings from POT

```
line 473 msgid "Search for a category&hellip;" (replace &hellip; with ...)
line 12 msgid "Cheatin&#8217; huh?" (replace &8217; with ') 

```

2. Please checkin the POT files into the build so that it can be monitored for new strings to help with translation

**Comment by findingsimple** [comment]
> Please checkin the POT files into the build so that it can be monitored for new strings to help with translation

@JPry lets discuss a workflow internally for this and see what we can come up with

**Comment by findingsimple** [comment]
> Please checkin the POT files into the build so that it can be monitored for new strings to help with translation.

@adarshakb just confirming that my preference is for us to have a workflow that gets the translations themselves into WPORG rather than committing them all to the repo as well. I'm following up.

**Comment by adarshakb** [comment]
@jconroy 

Question:
What happens when there are translations
1. Available in both the places (PO file and WPORG)? 
2. if a string is missing in PO file but present in WPORG ? and Vice-versa ?

My goal is to package these localized PO files into the app.

The reason is
1. It is not going to add too much size as we have very less number of strings.
3. I dont see us updating the strings often since the plugin isnt changing much.
4. The overhead is a 48hour turnaround time for translators to push the translation back into the develop branch (which in reality is more like 12hours)
5. In case of emergency fixes, we can always release plugin without translation and then later do a release with translations.

let me know your thoughts.

**Comment by adarshakb** [comment]
Another question if you know the answer to @jconroy 
Is there a way to upload translated PO file WPORG rather than using their UI?

**Comment by adarshakb** [comment]
Question 3:

Is there an API you know about for WPORG
