### ISSUE TITLE
Domain verification page/save settings error during the onboarding

### ISSUE THREAD

**Issue by ghost** [woocommerce/pinterest-for-woocommerce#477]
Discription:
Users report a problem with site verification and saving settings during onboarding. It's impossible to go through and finish.

Steps:
Claim your website" the website is prefilled and when I press start verification it brings up the error message "There was an error saving the settings"
logs:
“2022-06-08T15:10:15+00:00 ERROR Sorry! We couldn't find that merchant. Please ensure you have access and a valid merchant id.”

Massage from Piterest:
I am seeing a pattern from 05/15. The errors have spiked from that date. Was there any change on that day? One main problem I see is _Partner connect failed with exception No relevant meta tag was found._

I speicifically couldnt find the above websites in the log, but there is a clear pattern from that day

![image](https://user-images.githubusercontent.com/97885354/173859746-5d4be5e8-273e-42ae-a045-df5ca1e58e65.png)

you can see that 99.1% of the errors are:
_Domain_Verifification_Error_Realtime_Nonretryable failed for website [bathroombutler.com/us](http://bathroombutler.com/us) and user 686376936867416861 with result no_tag_
and the domain does not have the meta tag
_<meta name="p:domain_verify" content="..."/>_

I checked these above domains and they too dont have the meta tag
https://angelblessings.ca/
raymond-weil.com/en/

Something to check on plugin's end ?
user is bathroombutler on pinterest.

**Comment by findingsimple** [comment]
Hi @Braksoft - there were no releases on 05/15 https://github.com/woocommerce/pinterest-for-woocommerce/releases
