### ISSUE TITLE
Feed register error if the merchant has another feed registered

### ISSUE THREAD

**Issue by alexiglesias31** [woocommerce/pinterest-for-woocommerce#494]
### Describe the bug:
The feed registration is not working properly when a merchant has another feed already registered on the Business account.

### Steps to reproduce:
1. Install the plugin and do the onboarding on one site (site A).
2. Install the plugin and do the onboarding on another site (site B).
3. There is only one feed registered in the Pinterest business account (site A).
4. The feed sync overview details on site B belongs to the site A.

Site A:
![site-a](https://user-images.githubusercontent.com/40774170/178539732-cf7c8b97-ad54-4b2c-a95d-1b4375220f14.png)

Site B:
![site-b](https://user-images.githubusercontent.com/40774170/178539743-fa01d1ad-95b0-4631-bf5b-f0de298c9727.png)

Business Account Catalogs:
![pinterest-business](https://user-images.githubusercontent.com/40774170/178539786-4df75d36-ba1c-49ab-a256-18429b49f172.png)

### Expected behavior:
Both feeds should be registered on the Business account.

### Actual behavior:
Only one feed is registered on the Business account.

### Updated Expected behavior:
A warning should be displayed informing the user that the Merchant has already registered a different feed.

**Comment by findingsimple** [comment]
@adarshakb can you refresh my memory, I seem to recall we only support connecting 1 site?

**Comment by adarshakb** [comment]
Yes you are correct @jconroy

**Comment by alexiglesias31** [comment]
Perfect. I think the solution here should be to display a warning message to the user informing that the merchant has already registered a different feed. What do you think @jconroy @adarshakb?
Just updated the issue description to reflect that.

**Comment by adarshakb** [comment]
@alexiglesias31 correct. We will update the API to return a new error code in that scenario and update

**Comment by adarshakb** [comment]
@alexiglesias31 we should block the user from connecting account in the Site B when they are already connected to Site A. So this should happen in Step 1 of the setup process

**Comment by alexiglesias31** [comment]
Got it @adarshakb. Perhaps the API can return the error when the user connects the plugin to the Pinterest account. That way we can add an error notice on the Step and block the onboarding process.
Looking forward to your feedback with the error code, will make progress in the mean time setting up the notice, etc.

**Comment by adarshakb** [comment]
Capturing slack conversation details. 

Currently create commerce partner endpoint will block if the user is trying to update feed URL with a different domain. This API fix will serve as a proxy to block the above bug's usecase. However the UI us going to make a GET call earlier to determine the failure and show better error message to customer.

**Comment by alexiglesias31** [comment]
@adarshakb @jconroy 

The new API error message blocks the feed registration when a merchant connects a second site.
![image](https://user-images.githubusercontent.com/40774170/197765831-d80356c6-7d7d-49f4-865b-cb1721b69e6f.png)

> we should block the user from connecting account in the Site B when they are already connected to Site A. So this should happen in Step 1 of the setup process

The merchant_id is only available either on the Step 3 (select advertiser) or after the setup is complete.
@adarshakb, Is there any endpoint to get the list of feeds on an early step to prevent that the user follows all the setup? Or can we close this and rely on the above API error?

**Comment by budzanowski** [comment]
@adarshakb ^ ?

**Comment by adarshakb** [comment]
>Is there any endpoint to get the list of feeds on an early step to prevent that the user follows all the setup?

To have a better UX. But  I will leave it upto designers to determine that. This works for now

**Comment by message-dimke** [comment]
I connected my site to Pinterest, then disconnected it and connected again. What I noticed is that my feed url at Pinterest was the one from the previous connection and my new url at WordPress side was not the same. 

I created a new site and connected it to Pinterest. Feed url at Pinterest side did not change, it remained the one from the first time connecting. Now I have two sites, both connected to the same Pinterest account and three different feed URLs. 

I am not receiving any error message as on the screens above, Pinterest does allow me to connect as many websites as I want, but does not change the feed URL. It keeps the one from the first time I connected my first website. Also Pinterest keeps sending me email messages that it was not able to fetch my feed by that first url which is not actual any more.

**Comment by alexiglesias31** [comment]
I did another round of test and I'm not receiving the API error. I think I got the error at some point, but perhaps I'm confused with a different issue.
The image below displays the logs while connecting a second site to the same merchant. As you can notice the API returns OK status in this case.

![image](https://user-images.githubusercontent.com/40774170/211835318-e7b87adc-39e4-4e76-921b-009eb816837f.png)

@adarshakb is this the expected behavior? If that's the case, then we should detect if there is another connected feed via a GET call instead of relying on the error of the `partner/connect` method.

**Comment by message-dimke** [comment]
There is an ongoing discussion about having multiple registered feeds with same/different locales. Nothing is decided yet.

**Comment by budzanowski** [comment]
I am closing this issue.

The current behavior of the plugin allows for multiple connections from different integrations at the same time. The plugin is not restricted this way. It is up to the API to decide what to do with this case. As it was tested the behavior has changed: https://github.com/woocommerce/pinterest-for-woocommerce/issues/494#issuecomment-1378862907 and a second connection is available.

The only thing that the plugin does is a maintenance cycle where it checks if another feed configuration is active ( but it needs to be from the same host as the current integration ), if it finds one it disables it. This other feed config comes from a wrong/old setup and is no longer necessary.
