### ISSUE TITLE
Product catalog: suggest next action when "Product feed is declined by Pinterest"

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#51]
In the product catalog page, Overview > Remote feed setup, I'm seeing a red error message "Product feed is declined by Pinterest". 

![image](https://user-images.githubusercontent.com/417342/123468121-ea6acf80-d623-11eb-812b-3b908a090286.png)

It would be good to suggest to users what they can do to fix the problem; otherwise, users might be left in the dark and don't know how to proceed. Some examples:

- Advise users to check their email and follow the instructions there.
- Provide a link to Pinterest official documentation on how to solve the problem.
- If there are specific reasons for the declination, provide those reasons so the users can act on them.

@j111q , tagging you here for your input.

**Comment by ksere** [comment]
Assuming that the only valid next step for a declined feed is to submit an appeal, I think its safe to say that this has been addressed in #227 

![image](https://user-images.githubusercontent.com/4016167/138293975-9b2d5408-9e6c-4d24-b132-e165849f5a51.png)
