### ISSUE TITLE
Ads Credit Flow: Feature Flag

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#514]
_Work In Progress Issue_

### User story

As a product manager
I want to be able to disable/enable Ads credit flow/functionality within Pinterest for WooCommerce
So that Ads Credits are only offered when they are available

As a merchant
I want to be offered Ads Credit only when it s available
So that I am not confused or falsely incentivized

### Description

WooCommerce.com will provide XXXXXX API to indicate promotions functionality should be enabled/disabled.

Make use of the API to provide a "feature flag" that can used within the extension to enable/disable the ads credit flow functionality,

## Technical

The API available is at

XXXXXXX

Assuming we'll want to cache the response in a transient.

Then expose the flag in a helper method/function

We will need a filter be able to for enable / disable the feature flag for testing

Please use the [feature/ads-credit-flow](https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/ads-credit-flow) branch for targeting prs against.

## Figma link

N/A

## Acceptance criteria

* [ ] Log request/response to debug log

## Unknowns

* Last update we have is the Campaign API is not yet available - dummy value can be used to kick start development

## Event tracking

N/A

**Comment by findingsimple** [comment]
The API requires authentication so can't be used like a  true feature flag as intended

**Comment by budzanowski** [comment]
I am closing this one. The Plugin part is done. And the PR for woocommerce.com part is ready https://github.com/Automattic/woocommerce.com/pull/14549
