### ISSUE TITLE
Ads Credit Flow: Onboarding Eligibility Notice

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#515]
_Work In Progress Issue_

## User story

As a product manager
I want to incentivize Merchants to continue setting up Pinterest for WooCommerce
So that they have the motivation to finish onboarding

As a merchant
I want to be incentivized to complete set up of Pinterest for WooCommerce
So that I am willing to continue to spend my valuable time/money finishing onboarding

### Description

We would like to display a clear notice during the onboarding flow notifying merchants of their eligibility for Ads Credit e.g. "Get $100 Credit...."

<img width="1098" alt="Screen Shot 2022-08-23 at 8 45 36 pm" src="https://user-images.githubusercontent.com/355014/186144639-e29343dc-3121-4276-be86-71fcac7ac7f5.png">

## Technical

* Use tracks event functionality already within the extension
* Where possible utilize existing WordPress/WooCommerce components (icons etc.)

Please use the [feature/ads-credit-flow](https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/ads-credit-flow) branch for targeting prs against.

## Figma link

[https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3417%3A56425](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3417%3A56425)

## Acceptance criteria

* [ ] Component visually matches design
* [ ] Component scales responsively in an appropriate manner (@shivanarrthine to confirm)
* [ ] Tracks event fired when clicking "View terms" link

## Unknowns

* Terms and conditions link to provided - can use placeholder link to get development started
* Copy to be confirmed

## Out of bounds/rabbit holes

* Ideally we can pull Campaign values e.g. $100 programmatically from API - for version 1 of this feature we'll just hard code to meet deadlines.

## Dependency

* TBC

## Event tracking

* `event_name` - Clicking view terms link should trigger tracks event

**Comment by budzanowski** [comment]
Latest design.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/17271089/191719826-f5cdabc0-d34d-4048-b212-d9db219c12e9.png">

**Comment by alexiglesias31** [comment]
@budzanowski, please confirm if we can close this issue as a result of the PR #526.

**Comment by budzanowski** [comment]
Yep.
