### ISSUE TITLE
Ads Credit Flow: Inbox Notification/s

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#517]
_Work In Progress Issue_

## User story

As a product manager
I want to incentivize Merchants to continue setting up Pinterest for WooCommerce
So that they have the motivation to finish onboarding

As a merchant
I want to be reminded and incentivized to complete setup of Pinterest for WooCommerce
So that I benefit from the addition reach for my products

## Description

Create the following inbox notifications

* Logic and content still TBC

## Technical

* [Scaffolding for inbox notifications is already available within the extension](https://github.com/woocommerce/pinterest-for-woocommerce/tree/develop/src/Notes)

Please use the [feature/ads-credit-flow](https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/ads-credit-flow) branch for targeting prs against.

## Figma link
* N/A

## Acceptance criteria

* [ ] Note content matches requirements
* [ ] Note triggers as detailed by logic in description

## Unknowns

* Content and logic to be confirmed  - can use placeholders to get development started

## Event tracking

* N/A Inbox notifications already have tracking built in.

**Comment by alexiglesias31** [comment]
@jconroy just added the needs design flag, since most of the description is TBC. Please let me know if I'm missing something here.

**Comment by findingsimple** [comment]
Hey @alexiglesias31 yep thanks all good, I'm waiting on confirmation from product and design

**Comment by findingsimple** [comment]
Closing - inbox notifications haven't been aligned on for marketing
