### ISSUE TITLE
Duplicate meta tags when RankMath Meta also used

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#521]
### Describe the bug:
For example when mercahnts also use the plugin "RankMath SEO" most of the meta tags that Pinterest plugins creates are:

meta property=”og:url” - Also created by RankMath
meta property=”og:site_name” - Also created by RankMath
meta property=”og:title” - Also created by RankMath
meta property=”og:type” - Also created by RankMath
meta property=”og:image” - Also created by RankMath
meta property=”product:price:currency” - Also created by RankMath
meta property=”product:price:amount” - Also created by RankMath
meta property=”og:price:standard_amount”
meta property=”og:description” - Also created by RankMath
meta property=”og:availability” - Also created by RankMath

Is there a way we can avoid this? other than deactivating the settings "Add Rich Pins for Products” and “Add Rich Pins for Posts” 

### Steps to reproduce:

1. Install and activate "RankMath SEO" and Pinterest plugin
2. do the onboarding on Pinterest plugin
3. Go to a product page and check the meta created

### Expected behavior:
no meta tags duplicated

### Actual behavior:
most of the meta created by Pinterest are duplicated.

### Additional details:
https://wordpress.org/support/topic/plugin-conflict-with-rankmath/

**Comment by ChristianAF** [comment]
I think this issue is duplicated #417

**Comment by findingsimple** [comment]
Agree, I've moved this to a compatibility issue to look at adding RankMath as an extension to look for

**Comment by alexiglesias31** [comment]
The issue #417 was to avoid conflict with the tracking events and the suggested actions are to review the conflicting plugins or deactivate Tracking in the settings.
The compatibility issue with RankMath affects the RichPins support. @jconroy should we add a second warning, similar to the warning that we added for the Tracking events, but the actions pointing to RichPins?

**Comment by budzanowski** [comment]
@alexiglesias31 Yes, we should extend the code from https://github.com/woocommerce/pinterest-for-woocommerce/pull/495 to also detect RichPins and warn about that.
