### ISSUE TITLE
Improve logic around feed state messages

### ISSUE THREAD

**Issue by alexiglesias31** [woocommerce/pinterest-for-woocommerce#522]
## User story
As mentioned in PR #495, we can improve the logic around feed state messages in order to avoid rendering HTML elements in PHP.
This issue can be considered a follow up of [this comment](https://github.com/woocommerce/pinterest-for-woocommerce/pull/495#pullrequestreview-1086862386).

### Describe the solution you'd like 
We need to rewrite the logic around the feed state messages in order to render all HTML elements in the frontend (react) and to avoid do that in PHP.

**Comment by message-dimke** [comment]
It's a pretty old ticket. Closing it as no issues were reported in regard.
