### ISSUE TITLE
Ads Credit Flow: Background Check

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/pinterest-for-woocommerce#531]
### Describe the solution you'd like 

In cases where a merchant has not setup billing or is in the process of setting up billing and closed the modal we should check on a regular basis to see if the billing is setup and redeem any available credit

![Catalog](https://user-images.githubusercontent.com/355014/187677079-18fac3ad-8780-49d1-af55-69b91f9eb115.png)

## Technical

* Check for billing setup once every 24 hours
* ~~If billing is setup, check eligibility and redeem credit~~
* ~~Catalog overview page will update to reflect whether credit is redeem as per figma designs and https://github.com/woocommerce/pinterest-for-woocommerce/issues/516~~

## Figma link

[https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3446%3A59130](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3446%3A59130)

## Dependencies

* https://github.com/woocommerce/pinterest-for-woocommerce/issues/516

## Out of bounds/rabbit holes

n/a

## Event tracking

n/a

**Comment by budzanowski** [comment]
- If billing is setup, check eligibility and redeem credit 
is now handled in:
https://github.com/woocommerce/pinterest-for-woocommerce/issues/553

**Comment by budzanowski** [comment]
- Catalog overview page will update to reflect whether credit is redeem as per figma designs and https://github.com/woocommerce/pinterest-for-woocommerce/issues/516
is now handled in:
https://github.com/woocommerce/pinterest-for-woocommerce/issues/554
