### ISSUE TITLE
Rich Pins Feature not stripping HTML

### ISSUE THREAD

**Issue by trinadin** [woocommerce/pinterest-for-woocommerce#539]
### Describe the bug:

The “Add Rich Pins for Products” setting in Pinterest for WooCommerce does not appear to be stripping HTML from og:description on line 174 of /pinterest-for-woocommerce/src/RichPins.php.

When Jetpack implements a similar feature, they use jetpack_og_get_description  which basically does a trim, strip_shortcodes, wp_strip_all_tags, etc. That’s on line 479 of /jetpack/functions.opengraph.php.

### Steps to reproduce:

1. Enable Rich Pins
2. Look at the generated og:description
3. $$$

### Expected behavior:

No HTML in og:description.

### Actual behavior:

HTML in og:description.

### Additional details:

I can haz rich pins?

**Comment by findingsimple** [comment]
Thanks @trinadin
