### ISSUE TITLE
Exclude Composite products from feed.

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#543]
### Describe the bug:
Merchant selling composite product:

>  I sell Composite products using the WooCommerce Composite Products Plugin. I would like to exclude them from the Pinterest feed because the single components don't make sense on Pinterest. I guess I just need to exclude the entire category "configurator" from my xml file (and also our gift vouchers which is another product category). How can I do that? Do I just edit the xml file through FTP or will it be overwritten by the plugin on a regular basis? I'd very much appreciate your support with this, thank you!

### Steps to reproduce:

1. install the plugin WooCommerce Composite Products
2. create a composite product with single components
3. Regenerate feed

### Expected behavior:
Composite product to be excluded from feed

### Actual behavior:
Composite products are not exculed

**Comment by alexiglesias31** [comment]
@jconroy 
Based on the decision on the last comment [here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/496), if we decide to only support some product types by default and make that condition extensible by the user then we  will can close this issue too.

**Comment by budzanowski** [comment]
The #496 is the ultimate solution that we will implement. Until that will be done the user can use the following snippet to block the Composite products from the feed file generation:

```PHP
function remove_composite_products_from_pinterest_feed( $excluded_products ) {
	array_push( $excluded_products, 'composite' );
	return $excluded_products;
}

add_filter( 'pinterest_for_woocommerce_excluded_product_types', 'remove_composite_products_from_pinterest_feed' );
```
The following information can be added to the response:


>Add this code to your child theme’s functions.php file or via a plugin that allows custom functions to be added, such as the [Code snippets](https://wordpress.org/plugins/code-snippets/) plugin. Please don’t add custom code directly to your parent theme’s functions.php file as this will be wiped entirely when you update the theme.

You can also inform the customer that we are working on more holistic solution that would not require a snippet - but it is unclear when it will be available.

I am closing this as we have a solution for what the merchant needs.
