### ISSUE TITLE
The sale price in the feed is wrong when the price exclude taxes

### ISSUE THREAD

**Issue by alexiglesias31** [woocommerce/pinterest-for-woocommerce#544]
### Describe the bug:

The sale price property on the feed has a wrong value if the WooCommerce option of displaying prices excludes taxes.

While working on the task we spotted another issue, the regular price on the feed was the same than sale price (for products on sale), already solved in this PR.

### Steps to reproduce:
1. Install the plugin and do the onboarding,
2. Set the WooCommerce option to display prices to exclude taxes.
3. Setup a product with a sale price.
4. The `<sale_price>` and the `<g:price>` properties on the feed should not include the taxes.

### Expected behavior:
The sale price on the feed should also exclude the taxes.

### Actual behavior:
The sale price doesn't exclude the taxes on the feed.

**Comment by alexiglesias31** [comment]
@jconroy this issue was spotted following up a CS ticket.

**Comment by findingsimple** [comment]
Thanks added to the list of to-dos
