### ISSUE TITLE
Tweak add to cart tracking event on AJAX

### ISSUE THREAD

**Issue by alexiglesias31** [woocommerce/pinterest-for-woocommerce#548]
### Describe the bug:

There are some customers complaining about the add to cart tracked event on single product pages using AJAX. The plugin is not reading properly the product properties (id, value, quantity).
There is margin for an enhancement on the logic around add to cart AJAX hook.

### Steps to reproduce:
1. Install the plugin.
2. Add a product to the cart from the single product page with AJAX.
3. The tracked event only contains the currency but no other product info.

### Expected behavior:
The tracked add to cart event should contain all the correct information.

### Actual behavior:
The tracked add to cart event only contains the store's currency.

**Comment by findingsimple** [comment]
> There are some customers complaining about the add to cart tracked event on single product pages using AJAX. The plugin is not reading properly the product properties (id, value, quantity). There is margin for an enhancement on the logic around add to cart AJAX hook.

@alexiglesias31 can you include some more details about this when you get a chance?

We have other issues/prs like https://github.com/woocommerce/pinterest-for-woocommerce/issues/27  https://github.com/woocommerce/pinterest-for-woocommerce/pull/428 and I'd be interested to clarify how they inter-relate

**Comment by alexiglesias31** [comment]
@jconroy the customers were using third party plugins like [this](https://wordpress.org/plugins/woo-ajax-add-to-cart/), which allows to add products to the cart from the single product page using AJAX.

**Comment by ColdRealms** [comment]
As one of the affected users, I would be happy to add any details that you might need. For example. I have tested on a variety of AJAX add to cart plugins including the one listed above, YITH's AJAX Cart, and the CART All In One Cart plugin from villatheme along with a few I cannot remember (didn't like the styling anyway).
Simply switching off the ajax function allows the tag to fire correctly. Using the Pinterest tag tester the value it sends on add to cart is "null". 
Note - Other tags fire correctly on these events, it is only the Pinterest one that does not.
