### ISSUE TITLE
Ads Credit Flow, onboarding modals rules.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#559]
### Information
While working on Issue #550 in PR #557 we have discovered that we don't fully understand and have not decided on the rules that will govern when the onboarding modals will be show.
For reference: https://github.com/woocommerce/pinterest-for-woocommerce/issues/550#issuecomment-1254003920

>If the original window/tab "gets focus" again check if billing is setup and poll every X seconds (open to discussion) to check again
Once billing is setup, check eligibility and redeem
Automatically close modal and display success message on catalog page

In this issue we will concretise and decide on the rules.

**Comment by findingsimple** [comment]
[Figma link](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3417%3A56425) just for reference

Note - designs are based on "auto redemption" - so if billing setup is detected - the extension is to auto try to redeem/claim available credit. Modals are displayed based on billing + redemption states.

So there are 4 general situations

* If the feature is disabled or there is no relevant campaign
* If Billing IS NOT setup
* If Billing IS setup and redemption has worked
* If there are any errors checking billing state or redeeming

I will try to cover below....

---


**If there is no active credit/coupon or "feature flag" is disabled show the "Without campaign / campaign turned off" state**

We basically say congrats on finishing setup

![Catalog](https://user-images.githubusercontent.com/355014/192443886-61b02205-48f1-4906-83a5-5e3e075a0c0a.png)

---

**If Billing IS NOT setup prompt the user to set up billing (call to action is clicking the "add billing details" button)**

![Catalog](https://user-images.githubusercontent.com/355014/192444187-40fa230c-201c-419d-b259-31552f0d1d38.png)

After clicking "add billing details" direct user to Pinterest in new tab - **close the modal** show the catalog page with the "Credits not claimed (Billing not set up)"

If "do it later" is clicked or the modal is closed before billing is detected as being setup also show the "Credits not claimed (Billing not set up)" state

The billing background check will be used to check when billing is set up and redeem coupons/offers.

--

**If Billing IS setup, redeem and show the redeem state (call to action is clicking the "got it" button)**

![Catalog](https://user-images.githubusercontent.com/355014/192444111-1156fad5-f43a-4296-b935-2f147c42c7d8.png)

After clicking "got it" show catalog page with "Credits not claimed (User hasn’t spent $15)" state
 
---

**If there are errors with checking billing or redeeming show error state / edge cases**

![Catalog(1)](https://user-images.githubusercontent.com/355014/192444296-a68209f2-cacd-4bc3-b733-576b314f7e9a.png)

We have 3 specific edge cases to catch as well as a generic error message which is used above.
