### ISSUE TITLE
When merchant's feed take more than 24hs to generate, the feed is never updated or created.

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#563]
### Describe the bug:
This happens when merchants have more than 800k products and variants. After 24h the previous execution didn't finish and start the new one, so this creates an endless loop.

### Steps to reproduce:
1. Site with 800k products
2. install and do the onboarding with the Pinterest plugin

### Expected behavior:
New execution of feed generation should not be executed until the last one was finished.

### Actual behavior:
the feed never is updated or created.

### Additional details:
SauCal ticket: https://saucal.zendesk.com/agent/tickets/10637
WooCommerce ticket: #5206946

**Comment by findingsimple** [comment]
Thanks @ChristianAF we'll discuss and update how we want to handle

> After 24h the previous execution didn't finish and start the new one, so this creates an endless loop.

To confirm is this based more on the length of time (24 hour) it takes or number of products e.g. if we add 800k products and it takes less than 24 hours is it still a problem?

**Comment by ChristianAF** [comment]
@jconroy Is a matter of time IMO. if Merchants have 800k products or more but take less than 24h to create the feed, this will not be a problem.

**Comment by budzanowski** [comment]
Speeding up generation is not in the scope of this issue. We only want to check how to generate the feed if it needs longer than 24h.

**Comment by alexiglesias31** [comment]
Here are some findings after the exploration:
- The new generation doesn't start if the previous generation is still running.
- The feed generation for that specific customer takes around 22h, 2h later the generation starts again, that may lead to an "always generating" perception.
- The problem in that customer site is the following, at some point one of the batch actions fails (throws a timeout error) and the generation breaks.

I think that the real issue would be how to prevent that a failed batch breaks the whole generation, I mean to implement a kind of retry mechanism.
cc @budzanowski

**Comment by budzanowski** [comment]
> The new generation doesn't start if the previous generation is still running.
That is great.

> The problem in that customer site is the following, at some point one of the batch actions fails (throws a timeout error) and the generation breaks.

OK, Please investigate potential solutions. I agree that this is the real problem. Do you think that we should have a UI element that would tell the merchant the generation takes a lot of time because there are a lot of elements?

**Comment by alexiglesias31** [comment]
I was thinking in something like a retry mechanism. Limiting the retries per batch to 3 or 4 to avoid endless generation.
I'm not sure about the UI, the generation time is already displayed in the Catalogs tab and it doesn't seem to be the root of the problem. However, an extra thought from a designer here would be nice.
Instead of the warning for the long generation time I'd display a warning or error notice if the generation breaks after the retry mechanism (in case we move forward with the retry mechanism of course).

@budzanowski

**Comment by budzanowski** [comment]
I missed the ping. Sorry! If the batch fails then yes we should restart it. We should have proper logging around the whole process.
