### ISSUE TITLE
Ads Credit: connect gating functionality to Ads Credit UI elements.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#577]
When a merchant uses Pinterest plugin with Ads feature they should not see the ads nudges and banners if the gating functionality detects that the ads campaign is not possible for current merchant. For example the start screen should not show the ads message for merchants form outside ads allowed countries:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/17271089/193353023-d8bc327e-43de-48b8-8ae8-492c207b44e5.png">

The aim of this issue is identification of all ads credits UI elements and not showing them in case Ads credits are not available.

**Comment by alexiglesias31** [comment]
@budzanowski, just double checking

> the gating functionality detects that the ads campaign is not possible for current merchant

Are you referring to the info that is returned in the variable `adsCampaignIsActive` or anything else?

**Comment by budzanowski** [comment]
Yep. Basically:

```js
useSettingsSelect()?.ads_campaign_is_active
```

**Comment by budzanowski** [comment]
@alexiglesias31 I have added a related Issue [Ads credits, check for available credits even if campaign is not active. #588](https://github.com/woocommerce/pinterest-for-woocommerce/issues/588) The display of available credits - if they exist -should not be disabled when `ads_campaign_is_active`.
