### ISSUE TITLE
The links should open in a new window for T&S 

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#595]
### Describe the bug:
![Screen Shot 2022-10-12 at 12 15 19 PM](https://user-images.githubusercontent.com/1510328/195429259-326ce7ed-c880-4d71-8063-d2da00ac4de8.png)

### Steps to reproduce:

1. Goto onboarding step and click on Terms and conditions
2. The model opens. 

### Expected behavior:
The links in model should open in a new window

### Actual behavior:
The links in model opens in same window taking user out of onboarding flow

**Comment by budzanowski** [comment]
@adarshakb that was a design decision, hmm.

**Comment by budzanowski** [comment]
I have asked @shivanarrthine for input.

**Comment by shivanarrthine** [comment]
> The links in model should open in a new window

Yes, clicking on a link within the modal should open the link in a new tab/window. Similar to the current behavior with other links on the onboarding wizard flow.

**Comment by budzanowski** [comment]
Sorry!
I have misread the issue. For a second I thought that the modal should be opened in a new window - which made no sense.
yes, the links inside the modal should open a new tab.
