### ISSUE TITLE
The campaign promo was only show in the first step of onboarding flow

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#596]
### Describe the bug:
![Screen Shot 2022-10-12 at 12 21 57 PM](https://user-images.githubusercontent.com/1510328/195430249-1c8ec05a-a7e4-40c7-91d9-109a7fed64ae.png)
![Screen Shot 2022-10-12 at 12 21 40 PM](https://user-images.githubusercontent.com/1510328/195430251-998953c7-dbe8-49d8-a70e-648f30584651.png)

### Steps to reproduce:

1. Open the onboarding flow with campaign turned on
2. Connect an account 

### Expected behavior:
The campaign upsell should continue to come in step 2 and 3 of onboarding flow
### Actual behavior:
Only the first step has campaign upsell flow

**Comment by budzanowski** [comment]
Oh, how could I have missed that!
