### ISSUE TITLE
The user is shown Ads credit is added but actually it is not added

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#597]
### Describe the bug:
![Screen Shot 2022-10-12 at 1 18 37 PM](https://user-images.githubusercontent.com/1510328/195439873-45d33dfc-4a4b-4e27-b1be-6731b2083e7b.png)
![Screen Shot 2022-10-12 at 1 17 46 PM](https://user-images.githubusercontent.com/1510328/195439881-57befcc3-ad52-4ac6-b08f-0133925175e7.png)
![Screen Shot 2022-10-12 at 1 17 36 PM](https://user-images.githubusercontent.com/1510328/195439886-6bd366e5-4da6-41ae-a5c9-693aef
![Screen Shot 2022-10-12 at 1 20 04 PM](https://user-images.githubusercontent.com/1510328/195439993-65dc577c-b3df-459a-bae3-df2b2a9d4295.png)
667592.png)

### Steps to reproduce:

1. Follow normal process and connect the user with LBA - (DM for login info for this particular user) 

### Expected behavior:
Only show redeemed if we actually redeemed

### Actual behavior:
Shows Ads credit as redeemed but its not applied

**Comment by adarshakb** [comment]
![Screen Shot 2022-10-12 at 12 26 00 PM](https://user-images.githubusercontent.com/1510328/195441943-45c41fee-d060-4c72-a0cf-6ee60f50c2aa.png)

**Comment by adarshakb** [comment]
https://clinical-willet.jurassic.ninja/wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fcatalog

**Comment by budzanowski** [comment]
Closed in favour of #611
