### ISSUE TITLE
Gack when activating the plugin

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#598]
### Describe the bug:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/1510328/195440683-1e8cdd92-3e75-4378-819a-862125a9d58d.png">

https://user-images.githubusercontent.com/1510328/195441389-e6f69d6a-6883-4322-915a-56e58ba8328e.mp4

### Steps to reproduce:

1. install and activate the plugin https://github.com/woocommerce/pinterest-for-woocommerce/files/9764563/pinterest-for-woocommerce.zip

### Expected behavior:
No gack

### Actual behavior:
`Notice: Undefined index: is_partner in /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/class-pinterest-for-woocommerce.php on line 1020
Fatal error: Uncaught Exception: Reconnect to your Pinterest account in /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/src/API/Base.php:243 Stack trace: #0 /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/src/API/Base.php(114): Automattic\WooCommerce\Pinterest\API\Base::handle_request(Array) #1 /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/src/API/Base.php(356): Automattic\WooCommerce\Pinterest\API\Base::make_request(‘users/me/busine...’, ‘GET’) #2 /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/class-pinterest-for-woocommerce.php(1020): Automattic\WooCommerce\Pinterest\API\Base::get_linked_businesses() #3 /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/class-pinterest-for-woocommerce.php(996): Pinterest_For_Woocommerce::update_linked_businesses() #4 /srv/users/userf721c88f/apps/userf721c88f/pu in /srv/users/userf721c88f/apps/userf721c88f/public/wp-content/plugins/pinterest-for-woocommerce/src/API/Base.php on line 243`

**Comment by budzanowski** [comment]
The error suggest that there was some corruption in the account_data option.

Was this a completely fresh install or there was Pinterest plugin installed before on this site?

**Comment by ivanrios** [comment]
For the original report, the plugin failed the first time, then I tried to uninstall and install again but it was not possible.

Just to test, I deleted the plugin (on a different site) and installed it again and I get the same error.

**Comment by budzanowski** [comment]
I think that I have found what is going on. The fix should be simple.
