### ISSUE TITLE
The plugin does not detect the billing configuration and does not trigger ad credits claim

### ISSUE THREAD

**Issue by ivanrios** [woocommerce/pinterest-for-woocommerce#599]
The plugin does not detect (even refreshing the page) that the user completes the billing setup on Pinterest and the offer code cannot be claimed.

It only works if I disconnect and connect and set up again.

### Steps to reproduce:
1. Connect and set up a Pinterest account (with no billing profile)
2. On the catalog tab, the banner "To claim the credits, add your billing information" appears.
3.  Set up your billing information on Pinterest adding a Credit Card
4.  Go back to the plugin page and refresh the page.
5. The "Set up billing" banner remains.

https://user-images.githubusercontent.com/1007705/195489403-ec697116-5149-45f7-a204-2c710003b4da.mp4

### Expected behavior:
After setting up the billing profile, the plugin should detect and claim the offer

**Comment by findingsimple** [comment]
Hi @ivanrios  - are you running this in a Jurassic ninja site? Can you share the details in slack? I'd like to make sure the Cron job  and events are setup correctly.

At the moment there is a daily events being setup
* [handle_billing_setup_check](https://github.com/woocommerce/pinterest-for-woocommerce/pull/551/files#diff-15c52da0801c164ddb71084ae436cdc5509676e0e192c3c57263d7136cc9cd40R28)
* [handle_redeem_credit](https://github.com/woocommerce/pinterest-for-woocommerce/pull/551/files#diff-add392e9b830327f712c032c6e0bb4a444f2f89041351aa18c331f452fb17f28R37)

**Comment by findingsimple** [comment]
@budzanowski did we look at

> If the original window/tab "gets focus" again check if billing is setup and poll every X seconds (open to discussion) to check again

[mentioned in this issue](https://github.com/woocommerce/pinterest-for-woocommerce/issues/516)

**Comment by budzanowski** [comment]
@jconroy We need a more aggressive way to check billing status change after user clicks the add your billing details button. Setup checking every refresh for the first hour after user has clicked button ( until it has been found that the billing has been set up ), later check every hour.

If the user ads billing using different route ( not through our button ) we have no way to detect this.

This should be rather easy fix.

**Comment by ivanrios** [comment]
I agree with @budzanowski, I think we should check Ads Credit validations for an hour after login on Pinterest (for new users), also for billing button or "Add billing details" link in the banner.

**Comment by ivanrios** [comment]
I have not claimed the credits yet, I discarded the modal last night and nothing has changed.

It is confusing from a user point of view and will cause problems at a functionality level because you Pinterest will not be able to track all campaigns spent as the user has no "future credits" claimed.



Banner with billing confirmation (I had to reconnect the account to see it)
![banner](https://user-images.githubusercontent.com/1007705/195691263-f672f7b0-5ed8-44ee-ba45-595ffd5865a5.png)

Current banner
![Catalogs](https://user-images.githubusercontent.com/1007705/195691282-55d4bccc-9e90-4d0d-b9ee-12c14f0c9ae5.png)

Billing section (no credits)

![Billing](https://user-images.githubusercontent.com/1007705/195691301-3f31c380-b42c-4cc9-846e-c808a6335168.png)

**Comment by budzanowski** [comment]
I think that at this stage you should have something in the Promotions. Assuming that your account is set-up correctly the coupon should be there. For some reason it was not redeemed.

Please enable debug logging and reconnect. It should catch the redeem API call.

**Comment by ivanrios** [comment]
No claim request, this is the log for reconnection.

[log.txt](https://github.com/woocommerce/pinterest-for-woocommerce/files/9780909/log.txt)

**Comment by ivanrios** [comment]
At this point I think the account is in the same situation as 

https://github.com/woocommerce/pinterest-for-woocommerce/issues/597

But I had to reconnect manually in order to view Ads modal and banner changes

**Comment by findingsimple** [comment]
> Setup checking every refresh for the first hour after user has clicked button ( until it has been found that the billing has been set up ), later check every hour.

So change is adding a check on page refresh correct? Then a check every hour.

@ivanrios can you confirm those timings are ok. Adarsha has flagged previously we don't want to check too often as it can create a lot of noise in your logging etc.

**Comment by adarshakb** [comment]
@jconroy - We can check on every refresh. That should be ok. Unless the user is spamming, I dont anticipate too many calls. That makes the logic simpler.

> Adarsha has flagged previously we don't want to check too often

This is true for background tasks which check every 10mins. We should exponentially backoff for background tasks which run automatically
