### ISSUE TITLE
WooCommerce 7.1 Compatibility Testing.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#604]
- WooCommerce 7.1 is scheduled for release on November 8th, 2022
- Beta Release on October 18th, 2022
- Release Candidate (Planned) November 1st, 2022

Perform smoke and compatibility testing to make sure the extension maintains compatibility with the upcoming release.

Fix any issues identified.

Confirm with Woo team that we can update tested up to tags

**Comment by dieherbar** [comment]
hi @budzanowski no issues were found between WooCommerce v7.1.0-rc.2, Woocommerce v7.1.0 and Pinterest for WooCommerce v1.2.5
This task can be closed.
cc. @jconroy
