### ISSUE TITLE
The feed profile is duplicated after changing the Wordpress language.

### ISSUE THREAD

**Issue by ivanrios** [woocommerce/pinterest-for-woocommerce#643]
### Describe the bug:

Every time a different language is set in the Wordpress settings, a new feed profile is created on Pinterest leaving the original one active.

![Screen Shot 2022-11-28 at 12 19 12](https://user-images.githubusercontent.com/1007705/204341885-a48d7668-2f6e-49d1-a26d-2419f4bc519d.png)

### Steps to reproduce:
1.  Log into your account
2.  Go to Settings -> General
3.  Change site Language
3.  Wait 2 hours
4.  Go to Pinterest Ads portal and go to Ads -> Catalogs.
5. You will see more than 1 catalog record

### Expected behavior:
Since there is no multifeed feature, each Pinterest connection should only have 1 active feed profile.

### Actual behavior:
A new feed profile is generated if the user changes the Wordpress language.

**Comment by ChristianAF** [comment]
Same issue for this merchant on one of our tickets, but maybe it's related to the plugin "Polylang"
