### ISSUE TITLE
Scheduled tasks are running with an unrecoverable API status (invalid token or unauthorized permission).

### ISSUE THREAD

**Issue by ivanrios** [woocommerce/pinterest-for-woocommerce#646]
### Describes the error:
Scheduled tasks are running with unrecoverable status.

If the API returns an **invalid token** response (status 401) or "**Permission denied to merchant XXX**", the synchronization process should terminate and the plugin should notify the user and **should stop running the scheduled tasks.**

**Examples**
API returns a 401 error code (invalid token).
[Screenshot 2022-12-01 at 1 58 41](https://user-images.githubusercontent.com/1007705/204987661-055d2e63-21d1-4df5-8b89-b4edc1330263.png)

API returns an error: Permission denied to merchant XXX in 
/v3/catalogs/datasource/feed_report/1490408914488/
/v3/commerce/product_pin_merchants/1506477470738/
[Screenshot 2022-12-01 at 1 35 17](https://user-images.githubusercontent.com/1007705/204987713-2d6dae38-cc16-4d8c-898c-87e467a47a3d.png)

### Expected behavior:
Notify the user about the error and pause all recurring tasks.

**Comment by alexiglesias31** [comment]
@ivanrios

> Notify the user about the error and pause all recurring tasks.

Is reconnecting the plugin a possible action to the user, or should the user do something with the merchant account? I mean, we will notify the users about the unauthorized operation and pause the scheduled actions. But we need to provide the user with an action to fulfill in order to get the plugin working again.

**Comment by ivanrios** [comment]
There is not option to reconnect the Pinterest account, if the token is no longer active (401 error), the solution is to ask the user to connect again.
