### ISSUE TITLE
When Merchant Account is disapproved you can not see all the reasons why.

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/pinterest-for-woocommerce#674]
### Describe the bug:

If you Pinterest account gets disapproved you can not see all the reasons why.

Pinterest extension UI

![Products_Catalog_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce](https://user-images.githubusercontent.com/9010963/214553659-ba5fccc9-c5e3-4080-8f4f-0c3a228ed73d.png)

Pinterest API response

![Cursor_and_wordpress-pinterest_–_Base_php](https://user-images.githubusercontent.com/9010963/214553575-d27d5fe3-5a1d-4879-aea9-093191306f49.png)

### Expected behavior:

You see all the reasons of account disapproval.

**Comment by ibndawood** [comment]
I did a quick check and I can see the code handling notices does not have `AUTHENTICITY_NO_SOCIALS_OR_ABOUT` and `AUTHENTICTY_NO_CONTACT_INFORMATION`: 

https://github.com/woocommerce/pinterest-for-woocommerce/blob/f7b60f089b43e00c255fa28a9be850d3372341fd/assets/source/setup-guide/app/components/HealthCheck/index.js#L19-L116

There is only a generic `AUTHENTICITY`. There are 2 ways to resolve this:
* Display the `AUTHENTICITY` message for all `AUTHENTICITY_*` related notices: `Merchant's information is incomplete or plagiarized`
* Or get all the available `AUTHENTICITY_*` `product_pint_approval_status_reasons` and add them to the `HealthCheck/index.js`.
