### ISSUE TITLE
Investigate all the possible Deprecated API v3 endpoints we may be using.

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/pinterest-for-woocommerce#677]
As of March 2022 Pinterest API v3 got deprecated. We may be using some of the deprecated endpoints. Prepare a list of those, if any.

**Comment by budzanowski** [comment]
@message-dimke, after it looks like also v4, is being deprecated I have created a project thread that will cover all of the things needed. I will close this for now, sorry for the confusion!
