### ISSUE TITLE
Create method(s) to report the product syncing status

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/pinterest-for-woocommerce#697]
This issue is part of #678 for integrating with the Multichannel Marketing Dashboard released with WooCommerce 7.4.

We need methods to obtain the product syncing status so that we return it through the `get_product_listings_status` method of `MarketingChannelInterface` and display it on the new multichannel marketing dashboard.

The method(s) must report the following statuses when queried:

- Is the product syncing in progress?
- Has the product syncing failed? (when, for example, there are errors when syncing the products or generating the feed)
- How many errors/issues is returned when syncing the products/feed?
- Is the product syncing finished?

The methods in the `FeedState` class already check and report the feed status (mainly through the `get_feed_state method`); however, since this is a controller class, these methods are tightly coupled with the front-end and not reusable. Moreover, this class heavily relies on filters to construct a multidimensional response array with the exact structure that the front-end is expecting. 

Ideally, we should extract some of these methods into a service class to make them reusable while keeping the structured response generation in the controller. This will prevent duplicate code and will improve the maintainability.

**Comment by ecgan** [comment]
Closing this issue since this has been addressed in merged PR https://github.com/woocommerce/pinterest-for-woocommerce/pull/705.
