### ISSUE TITLE
Console error related to the option "Save to Pinterest" 

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#706]
### Describe the bug:
When the option "Save to Pinterest" is enabled. the console error appears on the site.
![image](https://user-images.githubusercontent.com/43881685/224986942-797dbc6e-3558-4539-af24-05f2fa135833.png)

### Steps to reproduce:

1. Activate the option "Save to Pinterest"
2. NAvigate to a product page
3. open the console of the browser

### Expected behavior:
no error related to Pinterest plugin on the console of the browser

### Actual behavior:
there is a console error on related to the  "Save to Pinterest" option

**Comment by budzanowski** [comment]
This is not really fixable: https://stackoverflow.com/a/42986081 this is a permanent feature of the browser.

This is the only way to reliably check if the plugin is installed to prevent the second save to Pinterest button. To get rid of the console error we would need to disable this functionality

The only way to move forward would be to modify the Chrome plugin so it would have a method that would handle:
`chrome.runtime.connect` from the Pinterest For WooCommerce plugin.

**Comment by budzanowski** [comment]
This is not really fixable: https://stackoverflow.com/a/42986081 this is a permanent feature of the browser.

This is the only way to reliably check if the plugin is installed to prevent the second save to Pinterest button. To get rid of the console error we would need to disable this functionality

The only way to move forward would be to modify the Chrome plugin so it would have a method that would handle:
`chrome.runtime.connect` from the Pinterest For WooCommerce plugin.

**Comment by budzanowski** [comment]
Closing as won't fix.
