### ISSUE TITLE
Fatal error when trying to do the onboarding

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#712]
### Describe the bug:

> Hi,
> 
> I have already describe my problem in this topic but I’m still waiting for help : https://wordpress.org/support/topic/linking-problem-8/#topic-16228568-replies
> 
> At the end of the onboarding process I have a fatal error. I’ve try with different browser, computer, with all extensions deactivate except this one and woo commerce … And it’s still not working. I really need this extension to work so I can run my Pinterest ads campaign.
> 
> Here is the logs “fatal error” :
> 
> 2023-03-23T10:50:26+00:00 CRITICAL Uncaught Error: Undefined constant "AUTH_KEY" in /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/src/Crypto.php:37
> Stack trace:
> #0 /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/src/Crypto.php(75): Automattic\WooCommerce\Pinterest\Crypto->__construct()
> #1 /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/src/Crypto.php(113): Automattic\WooCommerce\Pinterest\Crypto::get_key()
> #2 /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/class-pinterest-for-woocommerce.php(635): Automattic\WooCommerce\Pinterest\Crypto::encrypt()
> #3 /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/src/API/Auth.php(105): Pinterest_For_Woocommerce::save_token()
> #4 /home/u968953634/domains/anartist.net/public_html/wp-includes/rest-api/class-wp-rest-server.php(1171): Automattic\WooCommerce\Pinterest\API\Auth->oauth_callback()
> #5 /home/u968953634/domains/anartist.net/public_html/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request()
> #6 /home/u968953634/domains/anartist.net/public_html/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch()
> #7 /home/u968953634/domains/anartist.net/public_html/wp-includes/rest-api.php(410): WP_REST_Server->serve_request()
> #8 /home/u968953634/domains/anartist.net/public_html/wp-includes/class-wp-hook.php(308): rest_api_loaded()
> #9 /home/u968953634/domains/anartist.net/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
> #10 /home/u968953634/domains/anartist.net/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
> #11 /home/u968953634/domains/anartist.net/public_html/wp-includes/class-wp.php(399): do_action_ref_array()
> #12 /home/u968953634/domains/anartist.net/public_html/wp-includes/class-wp.php(780): WP->parse_request()
> #13 /home/u968953634/domains/anartist.net/public_html/wp-includes/functions.php(1332): WP->main()
> #14 /home/u968953634/domains/anartist.net/public_html/wp-blog-header.php(16): wp()
> #15 /home/u968953634/domains/anartist.net/public_html/index.php(17): require('/home/u96895363...')
> #16 {main}
>   thrown dans /home/u968953634/domains/anartist.net/public_html/wp-content/plugins/pinterest-for-woocommerce/src/Crypto.php à la ligne 37
> [Contract](https://wordpress.org/support/topic/onboarding-fatal-error/#)
> And here is the logs “pinterest for woocommerce” (in French) :
> 
> 023-03-23T10:50:08+00:00 ERROR GET Demande : https://api.pinterest.com/ads/v4/advertisers/countries
> Code du statut : 401
> Réponse API : Reconnectez-vous à votre compte Pinterest
> I hope you’ll can help me, thank you
> 
WP forum thread: https://wordpress.org/support/topic/onboarding-fatal-error/

**Comment by rawdreeg** [comment]
Hi @ChristianAF,

This could mean that your AUTH_KEY has not been properly added to wp-config.php file. To fix this, you need to add it.

You can add it manually; this is a useful keys generator for WordPress: https://api.wordpress.org/secret-key/1.1/salt/

You can add the code returned by this API directly in your wp-config.php  file.

This should allow you to complete the installation. Let us know how it goes.

Thanks
