### ISSUE TITLE
Required PHP version is higher than the latest WooCommerce PHP requirement

### ISSUE THREAD

**Issue by moon0326** [woocommerce/pinterest-for-woocommerce#714]
### Describe the bug:
While investigating the `wcadmin_install_plugin_error` track data, I noticed an unusual # of `The PHP version on your server is 7.2.34, however the uploaded plugin requires 7.3.,Plugin installation failed.` errors. WoCommerce [records](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/PluginsHelper.php#L201) `wcadmin_install_plugin_error` error when a plugin installation fails during OBW.

WooCommerce requires PHP 7.2+, where as Pinterest for WooCommerce requires PHP 7.3+

Full error message:

```
Downloading installation package from https://downloads.wordpress.org/plugin/pinterest-for-woocommerce.1.2.15.zip&#8230;,Unpacking the package&#8230;,Installing the plugin&#8230;,The package could not be installed. The PHP version on your server is 7.2.34, however the uploaded plugin requires 7.3.,Plugin installation failed
```

### Steps to reproduce:

1. Setup a server with PHP 7.2 (PHP requirement for the latest WooCommerce)
2. Install and activate WooCommerce
3. Go to `Marketing -> Overview`
4. Click `Install plugin` button on `Pinterest for WooCommerce`

Screenshot 
![Screen Shot 2023-03-29 at 12 58 32 PM](https://user-images.githubusercontent.com/4723145/228653368-c00d7f4d-c160-409a-af20-15d9f3eed78b.jpg)

### Expected behavior:

Pinterest for WooCommerce should be installable on the latest WooCommerce

### Actual behavior:

Since Pinterest for WooCommerce has higher PHP requirement than the latest WooCommerce, it cannot be installed for some users.

**Comment by JPry** [comment]
Hi @moon0326!

> WooCommerce requires PHP 7.2+, where as Pinterest for WooCommerce requires PHP 7.3+

Within less than 2 months time, WooCommerce will be [bumping PHP to 7.3](https://developer.woocommerce.com/2023/01/10/new-requirement-for-woocommerce-7-7-php-7-3/). Additionally, WooCommerce will be moving to PHP 7.4 as the minimum version later this year. Since even PHP 7.4 is past the point of receiving security updates, it doesn't make sense to adjust the PHP version requirement *backwards*. 

> WoCommerce [records](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/PluginsHelper.php?rgh-link-date=2023-03-29T19%3A58%3A54Z#L201) wcadmin_install_plugin_error error when a plugin installation fails during OBW.

This really isn't an error with this extension. Rather, WordPress is correctly determining that the plugin cannot be installed given the current requirements, and prevents the installation. I believe the Onboarding Wizard should preemptively determine whether extensions can be installed before offering it as an option.

**Comment by moon0326** [comment]
Thanks @JPry 👍 

>Within less than 2 months time, WooCommerce will be [bumping PHP to 7.3](https://developer.woocommerce.com/2023/01/10/new-requirement-for-woocommerce-7-7-php-7-3/). Additionally, WooCommerce will be moving to PHP 7.4 as the minimum version later this year. Since even PHP 7.4 is past the point of receiving security updates, it doesn't make sense to adjust the PHP version requirement backwards.

Yup, that sounds very reasonable. Although...we'll still get these error messages until May. 

> This really isn't an error with this extension. Rather, WordPress is correctly determining that the plugin cannot be installed given the current requirements, and prevents the installation. I believe the Onboarding Wizard should preemptively determine whether extensions can be installed before offering it as an option.

I agree. However, I think the general expectation is that plugins such as Pinterest for WooCommerce should not require a PHP version higher than the latest WooCommerce as it is designed solely for WooCommerce. In the future, it would be nice if we check the latest WooCommerce version and match it.
