### ISSUE TITLE
Include Backordered items in feed file

### ISSUE THREAD

**Issue by darcie** [woocommerce/pinterest-for-woocommerce#717]
### Describe the bug:

When "Hide out of stock items from the catalog" is checked in WooCommerce Settings, only in stock items are synced to the Pinterest feed. This prevents back ordered items that would usually be visible in the catalog from being sent to Pinterest. 

This was changed in #284 

### Steps to reproduce:

1. Have products with out of stock and backorder status and check Hide out of stock items from the catalog
2. Only the in stock items are added to the generated feed
3. Uncheck Hide out of stock items from the catalog and force feed regeneration from scheduled actions
4. All products appear in the feed

### Expected behavior:

Since back ordered items appear in the WooCommerce catalog and are not hidden, I would expect them to be added to the Pinterest feed. 

### Actual behavior:

As the feed generator only looks for the `instock` status, the `preorder` status is skipped. https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/FeedGenerator.php#L289
We map backordered WooCommerce products to the Pinterest `preorder` status in status here: https://github.com/woocommerce/pinterest-for-woocommerce/blob/b5076f0fb399eb5ba156813b1a6ee71f469f9d79/src/ProductsXmlFeed.php#L354

### Additional details:

Reported in 6058102-zen

**Comment by message-dimke** [comment]
Hi, @darcie here is the PR for it https://github.com/woocommerce/pinterest-for-woocommerce/pull/720

**Comment by ibndawood** [comment]
Hello @darcie . We've released `v1.2.19`, which will fix this issue. Please ask the customers to update the plugin and let us know if there are any issues.
