### ISSUE TITLE
Full download url not taken into account when comparing local and remote feed config.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#724]
### Describe the bug:
When a new local configuration is generated it is not getting updated in the remote settings.

### Steps to reproduce:

1. Onboard a merchant to Pinterest
2. Disable product sync from Marketing > Pinterest > Settings
3. Reenable product sync. Pinterest for WooCommerce will generate a new feed XML file with a different URL. The old URL is deleted.
4. When Pinterest reads from the data source the next time, the URL of the file will be the old one instead of the new file.

### Expected behavior:
The remote feed config should be updated.

### Actual behavior:
The remote feed config still uses the old URL.

### Additional details:
The code that compares the local and remote feed configs uses `dirname` when in fact it should be using the full URL.

**Comment by sukafia** [comment]
6180703-zen, 6171973-zen - we tested the test file [here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/725) and it resolved the issue on our test site.

**Comment by sukafia** [comment]
6171973-zen

**Comment by sukafia** [comment]
6202509-zen

**Comment by budzanowski** [comment]
@sukafia the release is happening tomorrow 🤞🏻

**Comment by sukafia** [comment]
Thank you. I'll continue adding new reports until it's released. (helps me know the users to follow up with once the new version is out)

6199257-zen

**Comment by ibndawood** [comment]
Hello @sukafia. We've released `v1.2.19` which would fix this issue. Please ask the customers to update the plugin and let us know if there are any issues.

**Comment by sukafia** [comment]
Thank you, @ibndawood. I've followed up with affected users.

6212296-zen
