### ISSUE TITLE
V5 api token refresh procedure.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#748]
The access token is good for 30 days. Before it expires we need to update it using the refresh token.

From the documentation:

> As noted, the access token is good for 30 days. In order to avoid having to get permission again from the user,
> you can use the refresh token at day 29 for example to get a brand new access token. 
> That process is described in [Refreshing an access token](https://developers.pinterest.com/docs/getting-started/authentication/#operation/user_account/analytics/top_video_pins#Using%20the%20access%20token#Refreshing%20an%20access%20token) 
> and simply requires a server side API call to get a new access token that is good for another 30 days.

Starting from https://github.com/woocommerce/pinterest-for-woocommerce/pull/747 all the required information should be already available after the connection procedure redirects back to the site. ( the wizard portion after the redirect still does not work but the data is being saved ). Branching of that branch should allow adding the refresh token procedure.

**Comment by message-dimke** [comment]
@budzanowski  I think PR #756 closes this ticket
