### ISSUE TITLE
Complete the onboarding for the user.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#757]
From the documentation:

```Merchant connect/disconnect
The very first endpoints you will use are to connect the user to the commerce integration on the Pinterest side. You will need to reference the metadata retrieved from the pop UI step above.

[Create commerce integration](https://developers.pinterest.com/docs/api/v5/#operation/integrations_commerce/post) with connecting user

You will also be responsible for [disconnecting/deleting the user from the commerce integration](https://developers.pinterest.com/docs/api/v5/#operation/integrations_commerce/del)

You may also [retrieve and update](https://developers.pinterest.com/docs/api/v5/#tag/integrations) when appropriate.
Domain/Website verification
Below are the endpoints that you can use to complete the website verification steps

Useful to establish the method and get the code
[Get the verification method code](https://developers.pinterest.com/docs/api/v5/#operation/website_verification/get)

Useful to verify the website once method and code is established
[Verify the user’s website](https://developers.pinterest.com/docs/api/v5/#operation/verify_website/update) with method and code

See all the user’s websites
[Get the user’s website](https://developers.pinterest.com/docs/api/v5/#operation/user_websites/get) (verified and unverified)

Delete  a specific verified website
[Delete a verified website](https://developers.pinterest.com/docs/api/v5/#operation/unverify_website/delete)

Note: This can be [done manually by the user](https://help.pinterest.com/en/business/article/claim-your-website) and they may already have a verified website.```

**Comment by message-dimke** [comment]
## Complete setup

At final step of onboarding when clicking Complete Setup button

![Onboarding_Guide_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce](https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/b0d0d5e9-ea89-43a2-8fbd-8fd9bf4b04c3)

We do few things:
- update enhanced match settings for a selected tag
- connect advertiser account 

### Update enhanced match settings for a selected tag

**PATCH advertisers/{advertiser_id}/conversion_tags**

with params
- _id_: tag id to update enhances match settings for;
- _aem_enabled_
- _aem_fnln_enabled_
- _aem_ph_enabled_
- _aem_ge_enabled_
- _aem_db_enabled_
- _aem_loc_enabled_

With V5 API the only place where it is possible to set all these settings for a tag is when creating it. 

The onboarding process creates a tag if none of the tags exist and when creating a tag we will set all the enchanted match properties and have them for each tag created with Pinterest extension (besides it is said by Pinterest enhanced match is enabled by default). But if for any reason there are any tags created using Pinterest UI we do not have any possibilities to update enhanced match settings for those tags.

### Connect advertiser account

**POST advertisers/{advertiser_id}/connect**

The endpoint does not have any documentation. I suppose this is one of those endpoints which were created for us specifically. Not sure what the endpoint does and why do we need to use it and if there are any analogs within API V5. 



cc @budzanowski

**Comment by message-dimke** [comment]
## Disconnect

When disconnecting we do few things:
- disconnect merchant
- disconnect advertiser

### Disconnect merchant

**POST catalogs/partner/disconnect**

### Disconnect advertiser

**POST advertisers/{advertiser_id}/disconnect**

with params
- _id_: tag id

Both endpoints do not have documentation for v3 API and ads v4 API. I assume those were specifically created for Automattic some time ago.

cc @budzanowski

**Comment by budzanowski** [comment]
> Update enhanced match settings for a selected tag

We should have the `advertisers/{advertiser_id}/conversion_tags` ported to V5. For now, don't implement this.

> Connect advertiser account

My guess is that the `advertiser_id` you get from the connection modal is of a connected advertiser so this step is not required.

> Disconnect

It looks like we only need to do:
[`https://developers.pinterest.com/docs/api/v5/#operation/integrations_commerce/patch`
](https://developers.pinterest.com/docs/api/v5/#operation/integrations_commerce/del)
