### ISSUE TITLE
Critical Error on Uninstall

### ISSUE THREAD

**Issue by Everade** [woocommerce/pinterest-for-woocommerce#779]
### Describe the bug:
Unable to uninstall the plugin since v1.3.0.

### Steps to reproduce:
1. Deactivate plugin via plugin manager
2. Delete Plugin via plugin manager
3. E_ERROR

### Expected behavior:
Uninstall

### Actual behavior:
Critical Error

### Additional details:
@budzanowski 
Unable to uninstall the plugin since version 1.3.0. (version 1.3.3 still not possible)
https://github.com/woocommerce/pinterest-for-woocommerce/commit/d53b3926d97ba76ac13164131aa9e4666e2c2e93

```
An error of type E_ERROR was caused in line 25 of the file /wp-content/plugins/pinterest-for-woocommerce/uninstall.php.
Error message: Uncaught Error: Class "Automattic\WooCommerce\Pinterest\FeedRegistration" not found in /wp-content/plugins/pinterest-for-woocommerce/uninstall.php:25
Stack trace:
#0 /wp-admin/includes/plugin.php(1241): include_once()
#1 /wp-admin/includes/plugin.php(958): uninstall_plugin()
#2 /wp-admin/plugins.php(412): delete_plugins()
#3 {main}
  thrown
```

**Comment by ecgan** [comment]
Hi @Everade , I tested installing the plugin version 1.3.3, and then deactivated it and uninstalled it, it works as expected for me, see screenshot below:

![image](https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/5be9bf54-31e0-4262-a1af-442adaa4a5d0)

The best place to get more detailed support for your site is on our [WordPress.org Pinterest for WooCommerce forum](https://wordpress.org/support/plugin/pinterest-for-woocommerce/). Our support engineers are there to help out. If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

**Comment by rawdreeg** [comment]
Closing as a support request.
