### ISSUE TITLE
Add to Cart event is not tracked when using REST API requests.

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/pinterest-for-woocommerce#784]
### Describe the bug:

When using All Products Block to render product Add to Cart event is not tracked compared to AJAX requests which regular Add to Cart button uses. 

This is happening because REST API calls do not maintain session object which Tracker object uses to obtain customer id for delayed event tracking. 

### Steps to reproduce:

0. Use Chrome. Install Pinterest Tag Helper extension.

<img width="1309" alt="Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/764efc83-22f8-4480-999d-9fdd00a88f34">

1. Click `Edit site` to open editor.

<img width="1310" alt="WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/63ac117a-da03-42b6-9483-daf004a8b7bd">

2. Choose Templates section.

<img width="1310" alt="Home_‹_Template_‹_Editor_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/ab0ac317-874d-46ca-b806-791091a760db">

3. Choose Product Catalog page to edit.

<img width="1310" alt="Home_‹_Template_‹_Editor_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/33ddb733-6473-4b70-a533-296595bdb210">

4. Edit the page and add the block.

<img width="1310" alt="Product_Catalog_‹_Template_‹_Editor_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/b563902c-3af5-4d27-868a-90a62ceded08">

5. Save the page.

<img width="1310" alt="Product_Catalog_‹_Template_‹_Editor_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/aaf455a4-57ff-4b6b-bb47-dc913b3878b5">

6. Go to Shop page

<img width="1310" alt="Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/b8e6b299-c326-45ad-a3cf-a3851d8c5d80">

7. Click Add to Cart button.

<img width="1310" alt="Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/14d4be90-da75-4605-9e46-15eab5a9336b">

8. **Refresh the page.** Observe no Add to Cart event tracked.
_Page refresh is needed because when Add to Cart REST API call triggered the event is saved and added into delayed event storage to be triggered with the next website render ( since it is JavaScript tracker and we can not trigger JS with REST API calls )_.

<img width="1309" alt="Cursor_and_Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/706bd004-369b-4b19-a7d8-76755d350fd8">

### Expected behavior:

After Add to Cart button clicked and page is refreshed or user navigates to any other website page, Add to Cart event tracked when using All Products Block and Add to Cart button.

<img width="1310" alt="Cursor_and_Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/8fd884dd-89f6-4cf0-8228-68de57cad8f0">

### Actual behavior:

AddToCart event is not tracked.

<img width="1309" alt="Cursor_and_Shop_–_WordPress_Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/706bd004-369b-4b19-a7d8-76755d350fd8">

### Additional details:

We can not track JS events from the backend that is why with AJAX or REST API calls we have to record a delayed event at the backend, store it in the temp storage e.g. transient and render corresponding JS code to trigger those delayed events next time the website page renders. So to check if the AddToCart event was triggered after clicking Add to Cart button page refresh is required to see if event was actually recorded.

**Comment by Babylon1999** [comment]
zd-6481422

**Comment by message-dimke** [comment]
Solved with https://github.com/woocommerce/woocommerce-blocks/pull/11117
