### ISSUE TITLE
Add to cart events aren't tracked for Ajax add to cart

### ISSUE THREAD

**Issue by sukafia** [woocommerce/pinterest-for-woocommerce#793]
### Describe the bug:

Add to cart events aren't being tracked on themes or plugins using AJAX add to cart on the single product page.

### Steps to reproduce:

1. Install and activate the [Ajax add to cart for WooCommerce](https://wordpress.org/plugins/woo-ajax-add-to-cart/) plugin (or another plugin or theme offering similar functionality)
2. Add a product to the cart from the single product page via AJAX.
5. Check Pinterest tag helper and you'll find the add to cart event isn't fired.

(Note: for [Ajax add to cart for WooCommerce](https://wordpress.org/plugins/woo-ajax-add-to-cart/) plugin, you can get the add to cart event to fire by selecting "Enable AJAX add to cart buttons on archives" in WooCommerce > Settings > Product. See the [related bug report](https://github.com/woocommerce/pinterest-for-woocommerce/issues/789).)

### Expected behavior:

Add to cart event should be fired on Ajax add to cart on the single product page. 

### Actual behavior:

Add to cart events aren't fired on Ajax add to cart on the single product page.

**Comment by sukafia** [comment]
@message-dimke did you test that the PR also fixed this issue? I just tested on the staging site of the user who reported the issue and it persists.

**Comment by message-dimke** [comment]
Hey, @sukafia! I am confused how did you test it since it was not released yet. I believe it is going into release today.

**Comment by sukafia** [comment]
> Hey, @sukafia! I am confused how did you test it since it was not released yet. I believe it is going into release today.

Oh! I thought it was released as part of this:

<img width="1035" alt="Screenshot 2023-08-16 at 5 21 26 PM" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/60121732/371ae336-1c35-44a0-8e19-0251eba18941">

**Comment by message-dimke** [comment]
Hm, I thought…. Let me check myself then and I’ll write you back. Idk what is happening, have to investigate.On 16 Aug 2023, at 19:23, Sunday Ukafia ***@***.***> wrote:﻿

Hey, @sukafia! I am confused how did you test it since it was not released yet. I believe it is going into release today.

Oh! I thought it was released as part of this:
