### ISSUE TITLE
Improve the Ads credit message to avoid confustion

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#801]
## User story
Improve the copy to be more clear to merchants that these are the steps that will happen during ads credit

Step1: Merchant adds billing info & payment method
Step 2: Active WooCommerce Coupon appears on UI and it will specify the exact amount in their currency and dates in which they need to spend
Step 3: Merchant spends specified amount during those dates and waits up to 2 billing cycles
Step 4: Promo credits are given

Currently some merchants assume that they can spend the money anytime. But it needs to be spent only after the coupon is added and is appears in the billing UI

Improve messaging to specify the exact spend/credit 

Currency | spend req | credit given
-- | -- | --
USD | 15 | 125
EUR | 15 | 131
GBP | 13 | 117
BRL | 80 | 673
CAD | 20 | 172
AUD | 23 | 195
MXN | 305 | 2548
ARS | 2198 | 18320
CHF | 14 | 124
CZK | 385 | 3216
DKK | 116 | 970
HUF | 6366 | 53050
JPY | 2172 | 18102
NOK | 162 | 1353
NZD | 26 | 222
PLN | 74 | 624
RON | 77 | 646
SEK | 170 | 1424

![Screenshot 2023-07-27 at 10 16 37 AM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/2f278162-cf88-485c-938c-12034efe82cf)
![Screenshot 2023-07-27 at 10 15 23 AM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/f61156db-2d81-4f02-908c-b53768e63e4e)
![Screenshot 2023-07-27 at 10 15 05 AM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/67ca564e-b696-4d09-9395-ba1461b07722)

![Example of WooCommerce Coupon](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/4bae71c3-1d6e-4e4a-bd78-9aa9da43b495)

**Comment by budzanowski** [comment]
We shall split this issue into two parts:

1. Dynamically change the currency amount required for promo. @krutidugade 
2. Update text copy.

**Comment by adarshakb** [comment]
@budzanowski - NOTE: If there is already an active coupon, users should wait for that coupon to be exhausted before new offer can be applied

So for example if you already had $10 in credits that was unused, the new coupon cannot be applied. After the $10credit is used, the new coupon can be applied.

**Comment by budzanowski** [comment]
@adarshakb is this a new piece of logic that is required, or should we update the message?

We try to redeem the coupon cyclically. What will happen if we try the process when there already is a coupon active?

**Comment by adarshakb** [comment]
This is an existing logic that was missed while I tested.

The API returns an error when you try to redeem a second coupon from woocommerce. I saw this while debugging a customer bug and confirmed it with billing team.

After customers uses up the current coupon, woo's job can run and redeem this coupon.

**Comment by krutidugade** [comment]
>Dynamically change the currency amount required for promo. @krutidugade

I have [submitted a PR](https://github.com/woocommerce/pinterest-for-woocommerce/pull/812) for review that addresses this part.

**Comment by MatthiasReinholz** [comment]
@adarshakb can you confirm if the credits given per currency are static values? Or will these be adjusted based on exchange rates?

**Comment by message-dimke** [comment]
As per Slack discussion we had with @adarshakb here https://a8c.slack.com/archives/C04QQLX04MC/p1695917245399259 is was decided to leave the text as is for now at least.

cc @budzanowski | @MatthiasReinholz
