### ISSUE TITLE
The feed_location should always be absolute URL

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#838]
### Describe the bug:
v3_create_commerce_partner_merchant call made by the app. The Error is of type Api request failed. Cannot determine feed type from format [XML] and url [/wp-content/uploads/pinterest-for-woocommerce-t8OBKI.xml].
It looks like a small percentage of requests made are with relative URLs [during merchant creation](https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Merchants.php#L128) where as the API expects absolute URL.

### Steps to reproduce:
1.  I am not sure on how to reproduce but you can easily reproduce by sending a relative URL to the API for a new merchant

### Expected behavior:
Convert relative URLs to absolute URLs. If unable to convert show a error to user to change settings

### Actual behavior:
Is sent as relative URL

### Additional details:
Currently call is made using args
```
$args = array(
			'merchant_domains' => get_home_url(),
			'feed_location'    => $config['feed_url'],
			'feed_format'      => 'XML',
			'country'          => Pinterest_For_Woocommerce()::get_base_country() ?? 'US',
			'locale'           => LocaleMapper::get_locale_for_api(),
			'currency'         => get_woocommerce_currency(),
			'merchant_name'    => $merchant_name,
		);
```
The feed_location needs to be always absolute URL because merchant_domains is an array and there can be more than one value and no other field currently is able to give the correct schema and domain.

**Comment by message-dimke** [comment]
I will add some checks for `feed_location` to have a domain because it must have it according to the initial logic. 

To the reason why some websites may have `feed_location` w/o a domain: My guess is some website have additional `upload_dir` filters.
Haven't found a place where we could remove the domain part out of `feed_location`.
