### ISSUE TITLE
Store refresh token lifetime.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#848]

**Comment by message-dimke** [comment]
We can continue with this one. Got a message from Adarsha:

> oAuth. I have enabled your clients to get the new beta feature to get infinite refresh tokens (essential for constantly refreshing your refresh tokens) for the API - https://developers.pinterest.com/docs/api/v5/#operation/oauth/token
There is a new `refresh_on` body parameter that's needed. Please take a look.

**Comment by message-dimke** [comment]
Code deployed https://github.com/Automattic/woocommerce-connect-server/pull/2354
