### ISSUE TITLE
Pinterest for WooCommerce Not Loading During Setup

### ISSUE THREAD

**Issue by ahunter-sagemind** [woocommerce/pinterest-for-woocommerce#877]
### Describe the bug:

1. Login to my Wordpress site - https://marshallshoney.com/
2. Navigate to Marketing > Pinterest > Get Started
3. I'm prompted to "Start Verification" of my website. Once I click "Start Verification" the screen goes blank and never reloads. 
![Uploading Screenshot 2024-01-02 at 3.29.33 PM.png…]()

**Comment by ibndawood** [comment]
Hello @ahunter-sagemind, thank you for reaching us. Please note that GitHub is not suitable for support. Please use the [wordpress.org support forums](https://wordpress.org/support/plugin/pinterest-for-woocommerce/) to raise a support request related to this plugin. In view of that, I'll close this issue. Please let us know if you have any other questions.

**Comment by ahunter-sagemind** [comment]
Thanks Kader,

That's strange...the plugin specifically links to your platform for support
issues.

Best,

https://sagemindmarketing.com/
