### ISSUE TITLE
Show event source as `Pinterest for WooCommerce` or `WooCommerce` (not `Manual Javascript`)

### ISSUE THREAD

**Issue by haszari** [woocommerce/pinterest-for-woocommerce#88]
### Is your feature request related to a problem? 
In the event test view on Pinterest (`Business > Ads > Conversions > Test events`), the events show the source as `Manual Javascript`.

<img width="1000" alt="Screen Shot 2021-07-08 at 1 50 03 PM" src="https://user-images.githubusercontent.com/4167300/124849900-bc0dcc80-dff3-11eb-9f2e-ea21fb085e2f.png">

It would be great to show that the events originated from the official Pinterest for WooCommerce plugin / integration. 

Is there an API we can use to set this up?

Not a major priority but would be nice polish :)

**Comment by findingsimple** [comment]
@niketpins wondering if this is possible to be fixed or if we can just close it out? (or any other thoughts)

**Comment by findingsimple** [comment]
@adarshakb  would https://github.com/woocommerce/pinterest-for-woocommerce/issues/393 resolve this?

**Comment by alexiglesias31** [comment]
@jconroy @adarshakb is there any feedback related to this issue?

**Comment by alexiglesias31** [comment]
@jconroy, currently the field 'Source' is empty. Is there any feedback related to some parameter that we can send with the events?
cc @adarshakb

![Screenshot_20220526_180418](https://user-images.githubusercontent.com/40774170/170587558-72beb198-b010-4d67-83be-1ecf6423d3d8.png)

**Comment by findingsimple** [comment]
I've pinged @adarshakb

**Comment by adarshakb** [comment]
Which plugin version they are on and is the np: tag being sent with woocommerce as source?

**Comment by alexiglesias31** [comment]
These tests were using the last version of the plugin.
Yes, the `np: woocommerce` tag is [being sent](https://github.com/woocommerce/pinterest-for-woocommerce/blob/d175407aeebe210af15350061f022d5eadaff485/src/Tracking.php#L47)

**Comment by adarshakb** [comment]
I have pinged the internal team in this matter. Waiting on their answer

**Comment by budzanowski** [comment]
@adarshakb any news?

**Comment by adarshakb** [comment]
This is in team's backlog. No word on when it will be prioritized.  We can close it and let the internal team prioritize it.

**Comment by message-dimke** [comment]
> We can close it and let the internal team prioritize it.
From the previous message by Adarsha.
