### ISSUE TITLE
Replace the middleware URL from `connect.woocommerce.com` to `api.woocommerce.com/integrations`

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/pinterest-for-woocommerce#917]
The `connect.woocommerce.com` server is due to be retired. The `api.woocommerce.com`  server now provides the connect service. The base URL will now be `api.woocommerce.com/integrations`. All other endpoints should now be accessible from the base URL.

## Endpoints

- [ ] `/auth/pinterestv3`
- [ ] `/login/pinterestv3`
- [ ] `/connect/pinterest-v5`
- [ ] `/renew/pinterest-v5`

**Comment by message-dimke** [comment]
Hey, @ibndawood !

Two problems I see with it. 

- `pinterestv3native` renamed to `pinterest-v3`: I must introduce code changes and some backward compatibility if we want to change this.
- despite `pinterestv3native` was replaced with `pinterest-v3` the connect server still uses the `pinterestv3native` here https://github.com/Automattic/woocommerce-connect-server/blob/09851f628172f562f91d2fc26d8cafa37d14ca3c/lib/integrations/pinterest/pinterest-v3/index.js#L3.

**Comment by ibndawood** [comment]
Hey, @message-dimke!

Thank you for looking into this.

> despite pinterestv3native was replaced with pinterest-v3 the connect server still uses the pinterestv3native

Please refer to @rawdreeg's comment here: p1709218902680949-slack-CK365S85V

> We only migrated pinterestv3Native, I just dropped native from the name since the distinction was no longer needed

I think the service name is still `pinterestv3native` in the database and hence we use it to query the service details such as app ID and secret. Can you please confirm @rawdreeg ?

**Comment by message-dimke** [comment]
Yes, this is just about the name and I do agree with having names consistent. It would be beautiful to have it as `pinterest-v3` but then I must update the code of the extension, which with Pinterest is not that easy since we are migrating the plugin to v5 api atm and service name is hardcoded into the extension's code.

**Comment by ibndawood** [comment]
Thank you, @message-dimke for the explanation.

@rawdreeg, is this something that we can handle from the `api.woocommerce.com` server?

**Comment by rawdreeg** [comment]
@ibndawood , The easiest way would be to rename pinterest-v3 service name to the expected pinterestv3native.

**Comment by ibndawood** [comment]
Thank you, @rawdreeg. Would you be able to help with this task? I am a bit confused about the whole naming change.

**Comment by rawdreeg** [comment]
No problem. I think ensuring that the the enpoint hit /pinterestv3native on our service should be enough. I have added this to my todo list.

**Comment by ibndawood** [comment]
Thank you for taking care of this 👍

**Comment by message-dimke** [comment]
Hey, @ibndawood !

Endpoints for v3 application

- [x] `/auth/pinterestv3native`
- [x] `/login/pinterestv3native`

do work when the application is provided with new base URI https://api.woocommerce.com/integrations endpoint.

**Comment by ibndawood** [comment]
Thank you, @message-dimke, for testing and verifying. We'll have to setup rewrites in the `connect.woocommerce.com` server to point to `api.woocommerce.com` for backward compatibility. I'll reach out to the systems. WIth that, we can close this issue as completed.

**Comment by message-dimke** [comment]
I would like to retest when redirect is ready. Could you ping me, please?

**Comment by message-dimke** [comment]
Hey, @ibndawood ! Everything works well with the redirect enabled. 

Thank you!

**Comment by ibndawood** [comment]
Thank you, @message-dimke, for testing. We can close this issue as the middleware URL is replaced in `v1.4.0`.
