### ISSUE TITLE
Overview stats show all 0 but there are issues in the Issues table

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#935]
### Describe the bug:

I was doing testing on a new test site using the code from the develop branch (8251408b26fc5838f76b76518e2942efea8efa84). 

I setup the new site, installed the new v5 plugin (not updating plugin), and went through the onboarding process. At first, all seem okay, but eventually i see the following screenshot: the Overview stats at the stop shows all 0, but there are issues in the bottom table, which does not seem to make sense to me.

![image](https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/bd1038e7-4657-4746-8351-7db6c46a1ec1)

Note that this may be due to my environment issue. I did connect and disconnect Pinterest account a few times.

### Steps to reproduce:

1. Go through the onboarding process.
2. Go to the Catalog tab.

### Expected behavior:

I believe the stats at the top should match with the number of issues in the table below.

### Actual behavior:

The stats at the top show all 0, but there are issues in the table below.

**Comment by ecgan** [comment]
Note that without me doing anything, eventually the Overview stats display some numbers, which is what I was expecting. See screenshot below:

<img width="925" alt="image" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/a68831fe-64ea-44f7-a451-fd89cb515b2a">

**Comment by message-dimke** [comment]
It is fixed somewhere between 1.4.0 and 1.4.8 versions by resetting the feed status when disconnecting.
