### ISSUE TITLE
Overview shows there are errors but there are no details about the errors

### ISSUE THREAD

**Issue by ecgan** [woocommerce/pinterest-for-woocommerce#937]
### Describe the bug:

In my test site, the Overview card shows that there is 1 error, but there are no details about the error in the Overview card or in the Issues table. The issues table has only 40 warning issues. See screenshot below:

<img width="928" alt="image" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/8b3d8641-e54c-4430-8039-cfe34b07c13d">

### Steps to reproduce:

1. Connect Pinterest account, wait for syncing, then look at the stats in the Overview card and the data in the Issues table.

### Expected behavior:

There should be explanation for the errors in the Issues table.

### Actual behavior:

There are no explanation for the errors in the Issues table.

**Comment by ecgan** [comment]
I was doing another round of testing and I see another similar issue.

The screenshot below shows that I have 41 warning issues in Overview, but the Issues table contain only 40 issues:

<img width="966" alt="image" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/3ec87a2e-50b4-4dd4-813f-fd8c8c4f1f31">

I looked into Pinterest site and it seems like the 1 missing warning issue is related to the "Alert 2" issue below. Notice that it has "Occurrences: -", which is probably why it does not show up in the Issues table in our plugin because it is not related to any specific product:

<img width="1439" alt="image" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/417342/6ec4e37a-3963-44f9-a08c-36066263804c">

**Comment by message-dimke** [comment]
I believe it was fixed with #1048
