### ISSUE TITLE
Ads credit was not claimed even with valid billing profile.

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#942]
### Describe the bug:

When a user connects to woocommerce we should claim the Ads credit. This tests the public v3/4 API version of the APP

API returns  "status":"ACTIVE","billing_profile_status":"VALID", "name":"Footy","billing_type":"CREDIT_CARD"

![Screenshot 2024-03-18 at 2 35 09 PM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/6a6b5400-b671-4726-90be-1c25cea9502f)
![Screenshot 2024-03-18 at 2 35 01 PM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/81b73345-e638-4991-ace4-6a7ad3b15950)
![Screenshot 2024-03-18 at 2 34 55 PM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/c43084d8-a550-4539-aa3a-c3f3bf5e146b)
![Screenshot 2024-03-18 at 2 34 50 PM](https://github.com/woocommerce/pinterest-for-woocommerce/assets/1510328/a566369e-1cc3-4ecb-a780-95f1aeca7405)

### Steps to reproduce:

1. Connect a user
2. Add billing
3. Refresh page to claim ads credit

### Expected behavior:
Ads credit to be claimed

### Actual behavior:
Ads credit was not claimed

### Additional details:
Shared the logs on slack channel as its sensitive data

**Comment by budzanowski** [comment]
This was closed by #926
