### ISSUE TITLE
4xx error  on v5_feeds_delete

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/pinterest-for-woocommerce#992]
Code 2625 - Merchant has been disapproved
Code 4162 - CATALOGS_FEED_HAS_ACTIVE_PROMOTIONS
Code 2626 - MERCHANT_UNDER_REVIEW

**Comment by message-dimke** [comment]
I reproduced `Code 2626` when disconnecting my account from Pinterest, having a feed ingested, and the account being under review. Not waiting for the account approval, I hit disconnect and got the error deleting the feed from Pinterest. The feed stayed at Pinterest with an INACTIVE status and moved to DISABLED after a while. I imagine `Codes 2625` and `Code 4162` are of the same nature.
